// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Kind of a [MediaSourceMessage]. / [MediaSourceMessage] 的种类。
enum SourceKindMessage {
  /// Local filesystem path. / 本地文件路径。
  file,
  /// In-memory bytes. / 内存字节。
  bytes,
  /// Flutter asset key (already resolved). / 已解析的 Flutter Asset 键。
  asset,
}

/// Detected media kind. / 检测到的媒体种类。
enum MediaKindMessage {
  /// Still image. / 静态图片。
  image,
  /// Container with a video track. / 含视频轨的容器。
  video,
  /// Audio-only container. / 纯音频容器。
  audio,
}

/// Wire representation of a media source. / 媒体源的跨端传输结构。
class MediaSourceMessage {
  MediaSourceMessage({
    required this.kind,
    this.uri,
    this.bytes,
  });

  /// Discriminator. / 种类。
  SourceKindMessage kind;

  /// File path or resolved asset key. / 文件路径或已解析的 asset 键。
  String? uri;

  /// In-memory payload for [SourceKindMessage.bytes]. / 字节源载荷。
  Uint8List? bytes;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      uri,
      bytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaSourceMessage decode(Object result) {
    result as List<Object?>;
    return MediaSourceMessage(
      kind: result[0]! as SourceKindMessage,
      uri: result[1] as String?,
      bytes: result[2] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaSourceMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(uri, other.uri) && _deepEquals(bytes, other.bytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaSourceMessage(kind: $kind, uri: $uri, bytes: $bytes)';
  }
}

/// Wire pixel size. / 像素尺寸传输结构。
class PixelSizeMessage {
  PixelSizeMessage({
    required this.width,
    required this.height,
  });

  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static PixelSizeMessage decode(Object result) {
    result as List<Object?>;
    return PixelSizeMessage(
      width: result[0]! as int,
      height: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PixelSizeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PixelSizeMessage(width: $width, height: $height)';
  }
}

/// Wire GPS. / GPS 传输结构。
class GpsLocationMessage {
  GpsLocationMessage({
    required this.latitude,
    required this.longitude,
    this.altitudeMeters,
  });

  double latitude;

  double longitude;

  double? altitudeMeters;

  List<Object?> _toList() {
    return <Object?>[
      latitude,
      longitude,
      altitudeMeters,
    ];
  }

  Object encode() {
    return _toList();  }

  static GpsLocationMessage decode(Object result) {
    result as List<Object?>;
    return GpsLocationMessage(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
      altitudeMeters: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GpsLocationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) && _deepEquals(longitude, other.longitude) && _deepEquals(altitudeMeters, other.altitudeMeters);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GpsLocationMessage(latitude: $latitude, longitude: $longitude, altitudeMeters: $altitudeMeters)';
  }
}

/// Wire leftover tag. / 残留标签传输结构。
class MetadataTagMessage {
  MetadataTagMessage({
    required this.name,
    required this.displayValue,
    this.stringValue,
    this.intValue,
    this.doubleValue,
  });

  String name;

  String displayValue;

  String? stringValue;

  int? intValue;

  double? doubleValue;

  List<Object?> _toList() {
    return <Object?>[
      name,
      displayValue,
      stringValue,
      intValue,
      doubleValue,
    ];
  }

  Object encode() {
    return _toList();  }

  static MetadataTagMessage decode(Object result) {
    result as List<Object?>;
    return MetadataTagMessage(
      name: result[0]! as String,
      displayValue: result[1]! as String,
      stringValue: result[2] as String?,
      intValue: result[3] as int?,
      doubleValue: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MetadataTagMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) && _deepEquals(displayValue, other.displayValue) && _deepEquals(stringValue, other.stringValue) && _deepEquals(intValue, other.intValue) && _deepEquals(doubleValue, other.doubleValue);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MetadataTagMessage(name: $name, displayValue: $displayValue, stringValue: $stringValue, intValue: $intValue, doubleValue: $doubleValue)';
  }
}

/// Wire PNG text chunk. / PNG 文本块传输结构。
class PngTextChunkMessage {
  PngTextChunkMessage({
    required this.key,
    required this.value,
  });

  String key;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      key,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static PngTextChunkMessage decode(Object result) {
    result as List<Object?>;
    return PngTextChunkMessage(
      key: result[0]! as String,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PngTextChunkMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) && _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PngTextChunkMessage(key: $key, value: $value)';
  }
}

/// Wire image metadata. Dates are ISO-8601 (no timezone) or empty.
/// 图片元数据传输结构。日期为无时区 ISO-8601 或空。
class ImageMetadataMessage {
  ImageMetadataMessage({
    this.make,
    this.model,
    this.software,
    this.size,
    this.orientation,
    this.dateTimeOriginal,
    this.dateTimeDigitized,
    this.dateTimeModified,
    this.gps,
    required this.hasMotionPhoto,
    required this.pngText,
    required this.extraTags,
  });

  String? make;

  String? model;

  String? software;

  PixelSizeMessage? size;

  int? orientation;

  String? dateTimeOriginal;

  String? dateTimeDigitized;

  String? dateTimeModified;

  GpsLocationMessage? gps;

  bool hasMotionPhoto;

  List<PngTextChunkMessage> pngText;

  List<MetadataTagMessage> extraTags;

  List<Object?> _toList() {
    return <Object?>[
      make,
      model,
      software,
      size,
      orientation,
      dateTimeOriginal,
      dateTimeDigitized,
      dateTimeModified,
      gps,
      hasMotionPhoto,
      pngText,
      extraTags,
    ];
  }

  Object encode() {
    return _toList();  }

  static ImageMetadataMessage decode(Object result) {
    result as List<Object?>;
    return ImageMetadataMessage(
      make: result[0] as String?,
      model: result[1] as String?,
      software: result[2] as String?,
      size: result[3] as PixelSizeMessage?,
      orientation: result[4] as int?,
      dateTimeOriginal: result[5] as String?,
      dateTimeDigitized: result[6] as String?,
      dateTimeModified: result[7] as String?,
      gps: result[8] as GpsLocationMessage?,
      hasMotionPhoto: result[9]! as bool,
      pngText: (result[10]! as List<Object?>).cast<PngTextChunkMessage>(),
      extraTags: (result[11]! as List<Object?>).cast<MetadataTagMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ImageMetadataMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(make, other.make) && _deepEquals(model, other.model) && _deepEquals(software, other.software) && _deepEquals(size, other.size) && _deepEquals(orientation, other.orientation) && _deepEquals(dateTimeOriginal, other.dateTimeOriginal) && _deepEquals(dateTimeDigitized, other.dateTimeDigitized) && _deepEquals(dateTimeModified, other.dateTimeModified) && _deepEquals(gps, other.gps) && _deepEquals(hasMotionPhoto, other.hasMotionPhoto) && _deepEquals(pngText, other.pngText) && _deepEquals(extraTags, other.extraTags);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ImageMetadataMessage(make: $make, model: $model, software: $software, size: $size, orientation: $orientation, dateTimeOriginal: $dateTimeOriginal, dateTimeDigitized: $dateTimeDigitized, dateTimeModified: $dateTimeModified, gps: $gps, hasMotionPhoto: $hasMotionPhoto, pngText: $pngText, extraTags: $extraTags)';
  }
}

/// Wire video metadata. / 视频元数据传输结构。
class VideoMetadataMessage {
  VideoMetadataMessage({
    this.durationMs,
    this.size,
    this.bitrate,
    this.rotationDegrees,
    this.make,
    this.model,
    this.gps,
    required this.extraTags,
  });

  int? durationMs;

  PixelSizeMessage? size;

  int? bitrate;

  int? rotationDegrees;

  String? make;

  String? model;

  GpsLocationMessage? gps;

  List<MetadataTagMessage> extraTags;

  List<Object?> _toList() {
    return <Object?>[
      durationMs,
      size,
      bitrate,
      rotationDegrees,
      make,
      model,
      gps,
      extraTags,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoMetadataMessage decode(Object result) {
    result as List<Object?>;
    return VideoMetadataMessage(
      durationMs: result[0] as int?,
      size: result[1] as PixelSizeMessage?,
      bitrate: result[2] as int?,
      rotationDegrees: result[3] as int?,
      make: result[4] as String?,
      model: result[5] as String?,
      gps: result[6] as GpsLocationMessage?,
      extraTags: (result[7]! as List<Object?>).cast<MetadataTagMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoMetadataMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(durationMs, other.durationMs) && _deepEquals(size, other.size) && _deepEquals(bitrate, other.bitrate) && _deepEquals(rotationDegrees, other.rotationDegrees) && _deepEquals(make, other.make) && _deepEquals(model, other.model) && _deepEquals(gps, other.gps) && _deepEquals(extraTags, other.extraTags);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoMetadataMessage(durationMs: $durationMs, size: $size, bitrate: $bitrate, rotationDegrees: $rotationDegrees, make: $make, model: $model, gps: $gps, extraTags: $extraTags)';
  }
}

/// Wire audio metadata. / 音频元数据传输结构。
class AudioMetadataMessage {
  AudioMetadataMessage({
    this.durationMs,
    this.bitrate,
    this.sampleRate,
    this.channelCount,
    this.make,
    this.model,
    this.gps,
    required this.extraTags,
  });

  int? durationMs;

  int? bitrate;

  int? sampleRate;

  int? channelCount;

  String? make;

  String? model;

  GpsLocationMessage? gps;

  List<MetadataTagMessage> extraTags;

  List<Object?> _toList() {
    return <Object?>[
      durationMs,
      bitrate,
      sampleRate,
      channelCount,
      make,
      model,
      gps,
      extraTags,
    ];
  }

  Object encode() {
    return _toList();  }

  static AudioMetadataMessage decode(Object result) {
    result as List<Object?>;
    return AudioMetadataMessage(
      durationMs: result[0] as int?,
      bitrate: result[1] as int?,
      sampleRate: result[2] as int?,
      channelCount: result[3] as int?,
      make: result[4] as String?,
      model: result[5] as String?,
      gps: result[6] as GpsLocationMessage?,
      extraTags: (result[7]! as List<Object?>).cast<MetadataTagMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AudioMetadataMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(durationMs, other.durationMs) && _deepEquals(bitrate, other.bitrate) && _deepEquals(sampleRate, other.sampleRate) && _deepEquals(channelCount, other.channelCount) && _deepEquals(make, other.make) && _deepEquals(model, other.model) && _deepEquals(gps, other.gps) && _deepEquals(extraTags, other.extraTags);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AudioMetadataMessage(durationMs: $durationMs, bitrate: $bitrate, sampleRate: $sampleRate, channelCount: $channelCount, make: $make, model: $model, gps: $gps, extraTags: $extraTags)';
  }
}

/// Tagged union of metadata results. / 带种类判别的元数据联合。
class MediaMetadataMessage {
  MediaMetadataMessage({
    required this.kind,
    this.image,
    this.video,
    this.audio,
  });

  MediaKindMessage kind;

  ImageMetadataMessage? image;

  VideoMetadataMessage? video;

  AudioMetadataMessage? audio;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      image,
      video,
      audio,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaMetadataMessage decode(Object result) {
    result as List<Object?>;
    return MediaMetadataMessage(
      kind: result[0]! as MediaKindMessage,
      image: result[1] as ImageMetadataMessage?,
      video: result[2] as VideoMetadataMessage?,
      audio: result[3] as AudioMetadataMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaMetadataMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(image, other.image) && _deepEquals(video, other.video) && _deepEquals(audio, other.audio);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaMetadataMessage(kind: $kind, image: $image, video: $video, audio: $audio)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SourceKindMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is MediaKindMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is MediaSourceMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PixelSizeMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GpsLocationMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is MetadataTagMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PngTextChunkMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is ImageMetadataMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is VideoMetadataMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is AudioMetadataMessage) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is MediaMetadataMessage) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SourceKindMessage.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaKindMessage.values[value];
      case 131:
        return MediaSourceMessage.decode(readValue(buffer)!);
      case 132:
        return PixelSizeMessage.decode(readValue(buffer)!);
      case 133:
        return GpsLocationMessage.decode(readValue(buffer)!);
      case 134:
        return MetadataTagMessage.decode(readValue(buffer)!);
      case 135:
        return PngTextChunkMessage.decode(readValue(buffer)!);
      case 136:
        return ImageMetadataMessage.decode(readValue(buffer)!);
      case 137:
        return VideoMetadataMessage.decode(readValue(buffer)!);
      case 138:
        return AudioMetadataMessage.decode(readValue(buffer)!);
      case 139:
        return MediaMetadataMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API implemented natively for media metadata reads.
/// 由原生端实现的媒体元数据读取接口。
class MediaInfoHostApi {
  /// Constructor for [MediaInfoHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MediaInfoHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Auto-detect and read in one I/O. / 一次 I/O 自动识别并读取。
  Future<MediaMetadataMessage> read(MediaSourceMessage source) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.read$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MediaMetadataMessage;
  }

  /// Read still-image metadata. / 读取静态图片元数据。
  Future<ImageMetadataMessage> readImage(MediaSourceMessage source) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ImageMetadataMessage;
  }

  /// Read a video or audio-only container. / 读取视频或纯音频容器。
  Future<MediaMetadataMessage> readAv(MediaSourceMessage source) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readAv$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MediaMetadataMessage;
  }

  /// Header-only kind detection. / 仅检查文件头。
  Future<MediaKindMessage> probe(MediaSourceMessage source) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.probe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MediaKindMessage;
  }

  /// Extract Motion Photo embedded MP4 metadata. / 提取动态照片内嵌 MP4。
  Future<VideoMetadataMessage> readMotionPhoto(MediaSourceMessage source) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readMotionPhoto$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VideoMetadataMessage;
  }
}
