name: xue_hua_media_info_web
description: "Web implementation of the xue_hua_media_info plugin. / xue_hua_media_info 插件的 Web 实现。"
version: 2.0.0
repository: https://github.com/Matkurban/xue_hua_media_info
issue_tracker: https://github.com/Matkurban/xue_hua_media_info/issues
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  xue_hua_media_info_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: xue_hua_media_info
    platforms:
      web:
        pluginClass: XueHuaMediaInfoWebPlugin
        fileName: xue_hua_media_info_web.dart
