name: xue_hua_media_info_example
description: "Demonstrates how to use the xue_hua_media_info plugin. / 演示如何使用 xue_hua_media_info 插件。"
publish_to: "none"
version: 2.0.0+1
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  xue_hua_media_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/testdata/
