// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/parser.dart';
import 'api/parser_async.dart';
import 'api/reader.dart';
import 'api/reader_async.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MediaMetadataParserPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser;

  @protected
  MediaMetadataParser
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  );

  @protected
  MediaMetadataParser
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  );

  @protected
  MediaMetadataParser
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AltitudeRef dco_decode_altitude_ref(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GpsLocation dco_decode_box_autoadd_gps_location(dynamic raw);

  @protected
  ImageExif dco_decode_box_autoadd_image_exif(dynamic raw);

  @protected
  MetadataValue dco_decode_box_autoadd_metadata_value(dynamic raw);

  @protected
  Rational dco_decode_box_autoadd_rational(dynamic raw);

  @protected
  VideoTrack dco_decode_box_autoadd_video_track(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FullImageMetadata dco_decode_full_image_metadata(dynamic raw);

  @protected
  GpsLocation dco_decode_gps_location(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageExif dco_decode_image_exif(dynamic raw);

  @protected
  LatitudeRef dco_decode_latitude_ref(dynamic raw);

  @protected
  List<MetadataEntry> dco_decode_list_metadata_entry(dynamic raw);

  @protected
  List<ParseError> dco_decode_list_parse_error(dynamic raw);

  @protected
  List<PngTextMetadata> dco_decode_list_png_text_metadata(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Rational> dco_decode_list_rational(dynamic raw);

  @protected
  LongitudeRef dco_decode_longitude_ref(dynamic raw);

  @protected
  MediaInfoError dco_decode_media_info_error(dynamic raw);

  @protected
  MediaInfoErrorCode dco_decode_media_info_error_code(dynamic raw);

  @protected
  MediaKind dco_decode_media_kind(dynamic raw);

  @protected
  MediaMetadata dco_decode_media_metadata(dynamic raw);

  @protected
  MetadataEntry dco_decode_metadata_entry(dynamic raw);

  @protected
  MetadataValue dco_decode_metadata_value(dynamic raw);

  @protected
  MetadataValueKind dco_decode_metadata_value_kind(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GpsLocation? dco_decode_opt_box_autoadd_gps_location(dynamic raw);

  @protected
  ImageExif? dco_decode_opt_box_autoadd_image_exif(dynamic raw);

  @protected
  MetadataValue? dco_decode_opt_box_autoadd_metadata_value(dynamic raw);

  @protected
  ParseError dco_decode_parse_error(dynamic raw);

  @protected
  PngTextMetadata dco_decode_png_text_metadata(dynamic raw);

  @protected
  Rational dco_decode_rational(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoTrack dco_decode_video_track(dynamic raw);

  @protected
  MediaMetadataParser
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  );

  @protected
  MediaMetadataParser
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  );

  @protected
  MediaMetadataParser
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AltitudeRef sse_decode_altitude_ref(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GpsLocation sse_decode_box_autoadd_gps_location(SseDeserializer deserializer);

  @protected
  ImageExif sse_decode_box_autoadd_image_exif(SseDeserializer deserializer);

  @protected
  MetadataValue sse_decode_box_autoadd_metadata_value(
    SseDeserializer deserializer,
  );

  @protected
  Rational sse_decode_box_autoadd_rational(SseDeserializer deserializer);

  @protected
  VideoTrack sse_decode_box_autoadd_video_track(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FullImageMetadata sse_decode_full_image_metadata(
    SseDeserializer deserializer,
  );

  @protected
  GpsLocation sse_decode_gps_location(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageExif sse_decode_image_exif(SseDeserializer deserializer);

  @protected
  LatitudeRef sse_decode_latitude_ref(SseDeserializer deserializer);

  @protected
  List<MetadataEntry> sse_decode_list_metadata_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<ParseError> sse_decode_list_parse_error(SseDeserializer deserializer);

  @protected
  List<PngTextMetadata> sse_decode_list_png_text_metadata(
    SseDeserializer deserializer,
  );

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Rational> sse_decode_list_rational(SseDeserializer deserializer);

  @protected
  LongitudeRef sse_decode_longitude_ref(SseDeserializer deserializer);

  @protected
  MediaInfoError sse_decode_media_info_error(SseDeserializer deserializer);

  @protected
  MediaInfoErrorCode sse_decode_media_info_error_code(
    SseDeserializer deserializer,
  );

  @protected
  MediaKind sse_decode_media_kind(SseDeserializer deserializer);

  @protected
  MediaMetadata sse_decode_media_metadata(SseDeserializer deserializer);

  @protected
  MetadataEntry sse_decode_metadata_entry(SseDeserializer deserializer);

  @protected
  MetadataValue sse_decode_metadata_value(SseDeserializer deserializer);

  @protected
  MetadataValueKind sse_decode_metadata_value_kind(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GpsLocation? sse_decode_opt_box_autoadd_gps_location(
    SseDeserializer deserializer,
  );

  @protected
  ImageExif? sse_decode_opt_box_autoadd_image_exif(
    SseDeserializer deserializer,
  );

  @protected
  MetadataValue? sse_decode_opt_box_autoadd_metadata_value(
    SseDeserializer deserializer,
  );

  @protected
  ParseError sse_decode_parse_error(SseDeserializer deserializer);

  @protected
  PngTextMetadata sse_decode_png_text_metadata(SseDeserializer deserializer);

  @protected
  Rational sse_decode_rational(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoTrack sse_decode_video_track(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_altitude_ref(AltitudeRef self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gps_location(
    GpsLocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_exif(
    ImageExif self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_metadata_value(
    MetadataValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rational(Rational self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_video_track(
    VideoTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_full_image_metadata(
    FullImageMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gps_location(GpsLocation self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_exif(ImageExif self, SseSerializer serializer);

  @protected
  void sse_encode_latitude_ref(LatitudeRef self, SseSerializer serializer);

  @protected
  void sse_encode_list_metadata_entry(
    List<MetadataEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_parse_error(
    List<ParseError> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_png_text_metadata(
    List<PngTextMetadata> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rational(List<Rational> self, SseSerializer serializer);

  @protected
  void sse_encode_longitude_ref(LongitudeRef self, SseSerializer serializer);

  @protected
  void sse_encode_media_info_error(
    MediaInfoError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_info_error_code(
    MediaInfoErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_kind(MediaKind self, SseSerializer serializer);

  @protected
  void sse_encode_media_metadata(MediaMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_metadata_entry(MetadataEntry self, SseSerializer serializer);

  @protected
  void sse_encode_metadata_value(MetadataValue self, SseSerializer serializer);

  @protected
  void sse_encode_metadata_value_kind(
    MetadataValueKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_gps_location(
    GpsLocation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_image_exif(
    ImageExif? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_metadata_value(
    MetadataValue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parse_error(ParseError self, SseSerializer serializer);

  @protected
  void sse_encode_png_text_metadata(
    PngTextMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rational(Rational self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_track(VideoTrack self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    int ptr,
  );
}
