// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/parser.dart';
import 'api/reader.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1713241567;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'xue_hua_media_info',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  MediaMetadataParser crateApiParserCreateMediaMetadataParser();

  MediaKindDto crateApiReaderDetectMediaKindFromBytes({
    required List<int> data,
  });

  MediaKindDto crateApiReaderDetectMediaKindFromFile({required String path});

  Future<void> crateApiInitApp();

  VideoTrackDto crateApiParserParseEmbeddedVideoFromBytes({
    required MediaMetadataParser parser,
    required List<int> data,
  });

  VideoTrackDto crateApiParserParseEmbeddedVideoFromFile({
    required MediaMetadataParser parser,
    required String path,
  });

  FullImageMetadataDto crateApiParserParseFullImageMetadataFromBytes({
    required MediaMetadataParser parser,
    required List<int> data,
  });

  FullImageMetadataDto crateApiParserParseFullImageMetadataFromFile({
    required MediaMetadataParser parser,
    required String path,
  });

  ImageExifDto crateApiParserParseImageExifFromBytes({
    required MediaMetadataParser parser,
    required List<int> data,
  });

  ImageExifDto crateApiParserParseImageExifFromFile({
    required MediaMetadataParser parser,
    required String path,
  });

  VideoTrackDto crateApiParserParseVideoMetadataFromBytes({
    required MediaMetadataParser parser,
    required List<int> data,
  });

  VideoTrackDto crateApiParserParseVideoMetadataFromFile({
    required MediaMetadataParser parser,
    required String path,
  });

  VideoTrackDto crateApiReaderReadEmbeddedVideoFromBytes({
    required List<int> data,
  });

  VideoTrackDto crateApiReaderReadEmbeddedVideoFromFile({required String path});

  FullImageMetadataDto crateApiReaderReadFullImageMetadataFromBytes({
    required List<int> data,
  });

  FullImageMetadataDto crateApiReaderReadFullImageMetadataFromFile({
    required String path,
  });

  ImageExifDto crateApiReaderReadImageExifFromBytes({required List<int> data});

  ImageExifDto crateApiReaderReadImageExifFromFile({required String path});

  ImageExifDto crateApiReaderReadImageExifLazyFromBytes({
    required List<int> data,
  });

  ImageExifDto crateApiReaderReadImageExifLazyFromFile({required String path});

  MediaMetadataDto crateApiReaderReadMediaMetadataFromBytes({
    required List<int> data,
  });

  MediaMetadataDto crateApiReaderReadMediaMetadataFromFile({
    required String path,
  });

  VideoTrackDto crateApiReaderReadVideoMetadataFromBytes({
    required List<int> data,
  });

  VideoTrackDto crateApiReaderReadVideoMetadataFromFile({required String path});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MediaMetadataParser;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MediaMetadataParser;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MediaMetadataParserPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  MediaMetadataParser crateApiParserCreateMediaMetadataParser() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParserCreateMediaMetadataParserConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserCreateMediaMetadataParserConstMeta =>
      const TaskConstMeta(
        debugName: "create_media_metadata_parser",
        argNames: [],
      );

  @override
  MediaKindDto crateApiReaderDetectMediaKindFromBytes({
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_kind_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderDetectMediaKindFromBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderDetectMediaKindFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "detect_media_kind_from_bytes",
        argNames: ["data"],
      );

  @override
  MediaKindDto crateApiReaderDetectMediaKindFromFile({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_kind_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderDetectMediaKindFromFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderDetectMediaKindFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "detect_media_kind_from_file",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  VideoTrackDto crateApiParserParseEmbeddedVideoFromBytes({
    required MediaMetadataParser parser,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
            parser,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_track_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiParserParseEmbeddedVideoFromBytesConstMeta,
        argValues: [parser, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserParseEmbeddedVideoFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "parse_embedded_video_from_bytes",
        argNames: ["parser", "data"],
      );

  @override
  VideoTrackDto crateApiParserParseEmbeddedVideoFromFile({
    required MediaMetadataParser parser,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
            parser,
            serializer,
          );
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_track_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiParserParseEmbeddedVideoFromFileConstMeta,
        argValues: [parser, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserParseEmbeddedVideoFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "parse_embedded_video_from_file",
        argNames: ["parser", "path"],
      );

  @override
  FullImageMetadataDto crateApiParserParseFullImageMetadataFromBytes({
    required MediaMetadataParser parser,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
            parser,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_full_image_metadata_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiParserParseFullImageMetadataFromBytesConstMeta,
        argValues: [parser, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserParseFullImageMetadataFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "parse_full_image_metadata_from_bytes",
        argNames: ["parser", "data"],
      );

  @override
  FullImageMetadataDto crateApiParserParseFullImageMetadataFromFile({
    required MediaMetadataParser parser,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
            parser,
            serializer,
          );
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_full_image_metadata_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiParserParseFullImageMetadataFromFileConstMeta,
        argValues: [parser, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserParseFullImageMetadataFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "parse_full_image_metadata_from_file",
        argNames: ["parser", "path"],
      );

  @override
  ImageExifDto crateApiParserParseImageExifFromBytes({
    required MediaMetadataParser parser,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
            parser,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_exif_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiParserParseImageExifFromBytesConstMeta,
        argValues: [parser, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserParseImageExifFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "parse_image_exif_from_bytes",
        argNames: ["parser", "data"],
      );

  @override
  ImageExifDto crateApiParserParseImageExifFromFile({
    required MediaMetadataParser parser,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
            parser,
            serializer,
          );
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_exif_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiParserParseImageExifFromFileConstMeta,
        argValues: [parser, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserParseImageExifFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "parse_image_exif_from_file",
        argNames: ["parser", "path"],
      );

  @override
  VideoTrackDto crateApiParserParseVideoMetadataFromBytes({
    required MediaMetadataParser parser,
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
            parser,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_track_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiParserParseVideoMetadataFromBytesConstMeta,
        argValues: [parser, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserParseVideoMetadataFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "parse_video_metadata_from_bytes",
        argNames: ["parser", "data"],
      );

  @override
  VideoTrackDto crateApiParserParseVideoMetadataFromFile({
    required MediaMetadataParser parser,
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
            parser,
            serializer,
          );
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_track_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiParserParseVideoMetadataFromFileConstMeta,
        argValues: [parser, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParserParseVideoMetadataFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "parse_video_metadata_from_file",
        argNames: ["parser", "path"],
      );

  @override
  VideoTrackDto crateApiReaderReadEmbeddedVideoFromBytes({
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_track_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadEmbeddedVideoFromBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadEmbeddedVideoFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_embedded_video_from_bytes",
        argNames: ["data"],
      );

  @override
  VideoTrackDto crateApiReaderReadEmbeddedVideoFromFile({
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_track_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadEmbeddedVideoFromFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadEmbeddedVideoFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "read_embedded_video_from_file",
        argNames: ["path"],
      );

  @override
  FullImageMetadataDto crateApiReaderReadFullImageMetadataFromBytes({
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_full_image_metadata_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadFullImageMetadataFromBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadFullImageMetadataFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_full_image_metadata_from_bytes",
        argNames: ["data"],
      );

  @override
  FullImageMetadataDto crateApiReaderReadFullImageMetadataFromFile({
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_full_image_metadata_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadFullImageMetadataFromFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadFullImageMetadataFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "read_full_image_metadata_from_file",
        argNames: ["path"],
      );

  @override
  ImageExifDto crateApiReaderReadImageExifFromBytes({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_exif_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadImageExifFromBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadImageExifFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_image_exif_from_bytes",
        argNames: ["data"],
      );

  @override
  ImageExifDto crateApiReaderReadImageExifFromFile({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_exif_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadImageExifFromFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadImageExifFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "read_image_exif_from_file",
        argNames: ["path"],
      );

  @override
  ImageExifDto crateApiReaderReadImageExifLazyFromBytes({
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_exif_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadImageExifLazyFromBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadImageExifLazyFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_image_exif_lazy_from_bytes",
        argNames: ["data"],
      );

  @override
  ImageExifDto crateApiReaderReadImageExifLazyFromFile({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_image_exif_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadImageExifLazyFromFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadImageExifLazyFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "read_image_exif_lazy_from_file",
        argNames: ["path"],
      );

  @override
  MediaMetadataDto crateApiReaderReadMediaMetadataFromBytes({
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_metadata_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadMediaMetadataFromBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadMediaMetadataFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_media_metadata_from_bytes",
        argNames: ["data"],
      );

  @override
  MediaMetadataDto crateApiReaderReadMediaMetadataFromFile({
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_media_metadata_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadMediaMetadataFromFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadMediaMetadataFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "read_media_metadata_from_file",
        argNames: ["path"],
      );

  @override
  VideoTrackDto crateApiReaderReadVideoMetadataFromBytes({
    required List<int> data,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_track_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadVideoMetadataFromBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadVideoMetadataFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_video_metadata_from_bytes",
        argNames: ["data"],
      );

  @override
  VideoTrackDto crateApiReaderReadVideoMetadataFromFile({
    required String path,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_track_dto,
          decodeErrorData: sse_decode_media_info_error,
        ),
        constMeta: kCrateApiReaderReadVideoMetadataFromFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReaderReadVideoMetadataFromFileConstMeta =>
      const TaskConstMeta(
        debugName: "read_video_metadata_from_file",
        argNames: ["path"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MediaMetadataParser => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MediaMetadataParser => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser;

  @protected
  MediaMetadataParser
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaMetadataParserImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MediaMetadataParser
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaMetadataParserImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MediaMetadataParser
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaMetadataParserImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AltitudeRefDto dco_decode_altitude_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AltitudeRefDto.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GpsLocationDto dco_decode_box_autoadd_gps_location_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gps_location_dto(raw);
  }

  @protected
  ImageExifDto dco_decode_box_autoadd_image_exif_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_exif_dto(raw);
  }

  @protected
  MetadataValueDto dco_decode_box_autoadd_metadata_value_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_metadata_value_dto(raw);
  }

  @protected
  RationalDto dco_decode_box_autoadd_rational_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rational_dto(raw);
  }

  @protected
  VideoTrackDto dco_decode_box_autoadd_video_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_video_track_dto(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FullImageMetadataDto dco_decode_full_image_metadata_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FullImageMetadataDto(
      exif: dco_decode_opt_box_autoadd_image_exif_dto(arr[0]),
      pngTextChunks: dco_decode_list_png_text_metadata_dto(arr[1]),
    );
  }

  @protected
  GpsLocationDto dco_decode_gps_location_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return GpsLocationDto(
      latitude: dco_decode_opt_box_autoadd_f_64(arr[0]),
      longitude: dco_decode_opt_box_autoadd_f_64(arr[1]),
      altitudeMeters: dco_decode_opt_box_autoadd_f_64(arr[2]),
      latitudeRef: dco_decode_latitude_ref_dto(arr[3]),
      longitudeRef: dco_decode_longitude_ref_dto(arr[4]),
      altitudeRef: dco_decode_altitude_ref_dto(arr[5]),
      iso6709: dco_decode_String(arr[6]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImageExifDto dco_decode_image_exif_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ImageExifDto(
      entries: dco_decode_list_metadata_entry_dto(arr[0]),
      gps: dco_decode_opt_box_autoadd_gps_location_dto(arr[1]),
      hasEmbeddedVideo: dco_decode_bool(arr[2]),
      parseErrors: dco_decode_list_parse_error_dto(arr[3]),
    );
  }

  @protected
  LatitudeRefDto dco_decode_latitude_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LatitudeRefDto.values[raw as int];
  }

  @protected
  List<MetadataEntryDto> dco_decode_list_metadata_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_metadata_entry_dto).toList();
  }

  @protected
  List<ParseErrorDto> dco_decode_list_parse_error_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_parse_error_dto).toList();
  }

  @protected
  List<PngTextMetadataDto> dco_decode_list_png_text_metadata_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_png_text_metadata_dto)
        .toList();
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RationalDto> dco_decode_list_rational_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rational_dto).toList();
  }

  @protected
  LongitudeRefDto dco_decode_longitude_ref_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LongitudeRefDto.values[raw as int];
  }

  @protected
  MediaInfoError dco_decode_media_info_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MediaInfoError(
      code: dco_decode_media_info_error_code(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  MediaInfoErrorCode dco_decode_media_info_error_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaInfoErrorCode.values[raw as int];
  }

  @protected
  MediaKindDto dco_decode_media_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MediaKindDto.values[raw as int];
  }

  @protected
  MediaMetadataDto dco_decode_media_metadata_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MediaMetadataDto_ImageExif(
          dco_decode_box_autoadd_image_exif_dto(raw[1]),
        );
      case 1:
        return MediaMetadataDto_VideoTrack(
          dco_decode_box_autoadd_video_track_dto(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  MetadataEntryDto dco_decode_metadata_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MetadataEntryDto(
      tagName: dco_decode_String(arr[0]),
      tagCode: dco_decode_i_32(arr[1]),
      ifdIndex: dco_decode_i_32(arr[2]),
      valueKind: dco_decode_metadata_value_kind(arr[3]),
      displayValue: dco_decode_String(arr[4]),
      rawValue: dco_decode_opt_box_autoadd_metadata_value_dto(arr[5]),
    );
  }

  @protected
  MetadataValueDto dco_decode_metadata_value_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MetadataValueDto_Text(dco_decode_String(raw[1]));
      case 1:
        return MetadataValueDto_Integer(dco_decode_i_64(raw[1]));
      case 2:
        return MetadataValueDto_Float(dco_decode_f_64(raw[1]));
      case 3:
        return MetadataValueDto_Rational(
          dco_decode_box_autoadd_rational_dto(raw[1]),
        );
      case 4:
        return MetadataValueDto_SignedRational(
          dco_decode_box_autoadd_rational_dto(raw[1]),
        );
      case 5:
        return MetadataValueDto_DateTime(dco_decode_String(raw[1]));
      case 6:
        return MetadataValueDto_NaiveDateTime(dco_decode_String(raw[1]));
      case 7:
        return MetadataValueDto_Bytes(dco_decode_String(raw[1]));
      case 8:
        return MetadataValueDto_RationalArray(
          dco_decode_list_rational_dto(raw[1]),
        );
      case 9:
        return MetadataValueDto_SignedRationalArray(
          dco_decode_list_rational_dto(raw[1]),
        );
      case 10:
        return MetadataValueDto_U8Array(
          dco_decode_list_prim_u_8_strict(raw[1]),
        );
      case 11:
        return MetadataValueDto_U16Array(
          dco_decode_list_prim_i_32_strict(raw[1]),
        );
      case 12:
        return MetadataValueDto_U32Array(
          dco_decode_list_prim_i_64_strict(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  MetadataValueKind dco_decode_metadata_value_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MetadataValueKind.values[raw as int];
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  GpsLocationDto? dco_decode_opt_box_autoadd_gps_location_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_gps_location_dto(raw);
  }

  @protected
  ImageExifDto? dco_decode_opt_box_autoadd_image_exif_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_image_exif_dto(raw);
  }

  @protected
  MetadataValueDto? dco_decode_opt_box_autoadd_metadata_value_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_metadata_value_dto(raw);
  }

  @protected
  ParseErrorDto dco_decode_parse_error_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ParseErrorDto(
      ifdIndex: dco_decode_i_32(arr[0]),
      tagName: dco_decode_String(arr[1]),
      tagCode: dco_decode_i_32(arr[2]),
      message: dco_decode_String(arr[3]),
    );
  }

  @protected
  PngTextMetadataDto dco_decode_png_text_metadata_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PngTextMetadataDto(
      key: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  RationalDto dco_decode_rational_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RationalDto(
      numerator: dco_decode_i_64(arr[0]),
      denominator: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VideoTrackDto dco_decode_video_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VideoTrackDto(
      entries: dco_decode_list_metadata_entry_dto(arr[0]),
      gps: dco_decode_opt_box_autoadd_gps_location_dto(arr[1]),
      parseErrors: dco_decode_list_parse_error_dto(arr[2]),
    );
  }

  @protected
  MediaMetadataParser
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MediaMetadataParserImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MediaMetadataParser
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MediaMetadataParserImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MediaMetadataParser
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MediaMetadataParserImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AltitudeRefDto sse_decode_altitude_ref_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AltitudeRefDto.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  GpsLocationDto sse_decode_box_autoadd_gps_location_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gps_location_dto(deserializer));
  }

  @protected
  ImageExifDto sse_decode_box_autoadd_image_exif_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_exif_dto(deserializer));
  }

  @protected
  MetadataValueDto sse_decode_box_autoadd_metadata_value_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_metadata_value_dto(deserializer));
  }

  @protected
  RationalDto sse_decode_box_autoadd_rational_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rational_dto(deserializer));
  }

  @protected
  VideoTrackDto sse_decode_box_autoadd_video_track_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_video_track_dto(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FullImageMetadataDto sse_decode_full_image_metadata_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exif = sse_decode_opt_box_autoadd_image_exif_dto(deserializer);
    var var_pngTextChunks = sse_decode_list_png_text_metadata_dto(deserializer);
    return FullImageMetadataDto(
      exif: var_exif,
      pngTextChunks: var_pngTextChunks,
    );
  }

  @protected
  GpsLocationDto sse_decode_gps_location_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_latitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_longitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_altitudeMeters = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_latitudeRef = sse_decode_latitude_ref_dto(deserializer);
    var var_longitudeRef = sse_decode_longitude_ref_dto(deserializer);
    var var_altitudeRef = sse_decode_altitude_ref_dto(deserializer);
    var var_iso6709 = sse_decode_String(deserializer);
    return GpsLocationDto(
      latitude: var_latitude,
      longitude: var_longitude,
      altitudeMeters: var_altitudeMeters,
      latitudeRef: var_latitudeRef,
      longitudeRef: var_longitudeRef,
      altitudeRef: var_altitudeRef,
      iso6709: var_iso6709,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImageExifDto sse_decode_image_exif_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entries = sse_decode_list_metadata_entry_dto(deserializer);
    var var_gps = sse_decode_opt_box_autoadd_gps_location_dto(deserializer);
    var var_hasEmbeddedVideo = sse_decode_bool(deserializer);
    var var_parseErrors = sse_decode_list_parse_error_dto(deserializer);
    return ImageExifDto(
      entries: var_entries,
      gps: var_gps,
      hasEmbeddedVideo: var_hasEmbeddedVideo,
      parseErrors: var_parseErrors,
    );
  }

  @protected
  LatitudeRefDto sse_decode_latitude_ref_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LatitudeRefDto.values[inner];
  }

  @protected
  List<MetadataEntryDto> sse_decode_list_metadata_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MetadataEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_metadata_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ParseErrorDto> sse_decode_list_parse_error_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ParseErrorDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_parse_error_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PngTextMetadataDto> sse_decode_list_png_text_metadata_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PngTextMetadataDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_png_text_metadata_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RationalDto> sse_decode_list_rational_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RationalDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rational_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LongitudeRefDto sse_decode_longitude_ref_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LongitudeRefDto.values[inner];
  }

  @protected
  MediaInfoError sse_decode_media_info_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_media_info_error_code(deserializer);
    var var_message = sse_decode_String(deserializer);
    return MediaInfoError(code: var_code, message: var_message);
  }

  @protected
  MediaInfoErrorCode sse_decode_media_info_error_code(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MediaInfoErrorCode.values[inner];
  }

  @protected
  MediaKindDto sse_decode_media_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MediaKindDto.values[inner];
  }

  @protected
  MediaMetadataDto sse_decode_media_metadata_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_image_exif_dto(deserializer);
        return MediaMetadataDto_ImageExif(var_field0);
      case 1:
        var var_field0 = sse_decode_box_autoadd_video_track_dto(deserializer);
        return MediaMetadataDto_VideoTrack(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  MetadataEntryDto sse_decode_metadata_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tagName = sse_decode_String(deserializer);
    var var_tagCode = sse_decode_i_32(deserializer);
    var var_ifdIndex = sse_decode_i_32(deserializer);
    var var_valueKind = sse_decode_metadata_value_kind(deserializer);
    var var_displayValue = sse_decode_String(deserializer);
    var var_rawValue = sse_decode_opt_box_autoadd_metadata_value_dto(
      deserializer,
    );
    return MetadataEntryDto(
      tagName: var_tagName,
      tagCode: var_tagCode,
      ifdIndex: var_ifdIndex,
      valueKind: var_valueKind,
      displayValue: var_displayValue,
      rawValue: var_rawValue,
    );
  }

  @protected
  MetadataValueDto sse_decode_metadata_value_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return MetadataValueDto_Text(var_field0);
      case 1:
        var var_field0 = sse_decode_i_64(deserializer);
        return MetadataValueDto_Integer(var_field0);
      case 2:
        var var_field0 = sse_decode_f_64(deserializer);
        return MetadataValueDto_Float(var_field0);
      case 3:
        var var_field0 = sse_decode_box_autoadd_rational_dto(deserializer);
        return MetadataValueDto_Rational(var_field0);
      case 4:
        var var_field0 = sse_decode_box_autoadd_rational_dto(deserializer);
        return MetadataValueDto_SignedRational(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return MetadataValueDto_DateTime(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return MetadataValueDto_NaiveDateTime(var_field0);
      case 7:
        var var_field0 = sse_decode_String(deserializer);
        return MetadataValueDto_Bytes(var_field0);
      case 8:
        var var_field0 = sse_decode_list_rational_dto(deserializer);
        return MetadataValueDto_RationalArray(var_field0);
      case 9:
        var var_field0 = sse_decode_list_rational_dto(deserializer);
        return MetadataValueDto_SignedRationalArray(var_field0);
      case 10:
        var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
        return MetadataValueDto_U8Array(var_field0);
      case 11:
        var var_field0 = sse_decode_list_prim_i_32_strict(deserializer);
        return MetadataValueDto_U16Array(var_field0);
      case 12:
        var var_field0 = sse_decode_list_prim_i_64_strict(deserializer);
        return MetadataValueDto_U32Array(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  MetadataValueKind sse_decode_metadata_value_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MetadataValueKind.values[inner];
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GpsLocationDto? sse_decode_opt_box_autoadd_gps_location_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_gps_location_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ImageExifDto? sse_decode_opt_box_autoadd_image_exif_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_image_exif_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MetadataValueDto? sse_decode_opt_box_autoadd_metadata_value_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_metadata_value_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParseErrorDto sse_decode_parse_error_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ifdIndex = sse_decode_i_32(deserializer);
    var var_tagName = sse_decode_String(deserializer);
    var var_tagCode = sse_decode_i_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ParseErrorDto(
      ifdIndex: var_ifdIndex,
      tagName: var_tagName,
      tagCode: var_tagCode,
      message: var_message,
    );
  }

  @protected
  PngTextMetadataDto sse_decode_png_text_metadata_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return PngTextMetadataDto(key: var_key, value: var_value);
  }

  @protected
  RationalDto sse_decode_rational_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_numerator = sse_decode_i_64(deserializer);
    var var_denominator = sse_decode_i_64(deserializer);
    return RationalDto(numerator: var_numerator, denominator: var_denominator);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VideoTrackDto sse_decode_video_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entries = sse_decode_list_metadata_entry_dto(deserializer);
    var var_gps = sse_decode_opt_box_autoadd_gps_location_dto(deserializer);
    var var_parseErrors = sse_decode_list_parse_error_dto(deserializer);
    return VideoTrackDto(
      entries: var_entries,
      gps: var_gps,
      parseErrors: var_parseErrors,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MediaMetadataParserImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MediaMetadataParserImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MediaMetadataParserImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_altitude_ref_dto(
    AltitudeRefDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_gps_location_dto(
    GpsLocationDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gps_location_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_image_exif_dto(
    ImageExifDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_exif_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_metadata_value_dto(
    MetadataValueDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_metadata_value_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rational_dto(
    RationalDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rational_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_video_track_dto(
    VideoTrackDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_track_dto(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_full_image_metadata_dto(
    FullImageMetadataDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_image_exif_dto(self.exif, serializer);
    sse_encode_list_png_text_metadata_dto(self.pngTextChunks, serializer);
  }

  @protected
  void sse_encode_gps_location_dto(
    GpsLocationDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_64(self.latitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.longitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.altitudeMeters, serializer);
    sse_encode_latitude_ref_dto(self.latitudeRef, serializer);
    sse_encode_longitude_ref_dto(self.longitudeRef, serializer);
    sse_encode_altitude_ref_dto(self.altitudeRef, serializer);
    sse_encode_String(self.iso6709, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_image_exif_dto(ImageExifDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_metadata_entry_dto(self.entries, serializer);
    sse_encode_opt_box_autoadd_gps_location_dto(self.gps, serializer);
    sse_encode_bool(self.hasEmbeddedVideo, serializer);
    sse_encode_list_parse_error_dto(self.parseErrors, serializer);
  }

  @protected
  void sse_encode_latitude_ref_dto(
    LatitudeRefDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_metadata_entry_dto(
    List<MetadataEntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_metadata_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_parse_error_dto(
    List<ParseErrorDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_parse_error_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_png_text_metadata_dto(
    List<PngTextMetadataDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_png_text_metadata_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rational_dto(
    List<RationalDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rational_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_longitude_ref_dto(
    LongitudeRefDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_media_info_error(
    MediaInfoError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_media_info_error_code(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_media_info_error_code(
    MediaInfoErrorCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_media_kind_dto(MediaKindDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_media_metadata_dto(
    MediaMetadataDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MediaMetadataDto_ImageExif(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_image_exif_dto(field0, serializer);
      case MediaMetadataDto_VideoTrack(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_video_track_dto(field0, serializer);
    }
  }

  @protected
  void sse_encode_metadata_entry_dto(
    MetadataEntryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tagName, serializer);
    sse_encode_i_32(self.tagCode, serializer);
    sse_encode_i_32(self.ifdIndex, serializer);
    sse_encode_metadata_value_kind(self.valueKind, serializer);
    sse_encode_String(self.displayValue, serializer);
    sse_encode_opt_box_autoadd_metadata_value_dto(self.rawValue, serializer);
  }

  @protected
  void sse_encode_metadata_value_dto(
    MetadataValueDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MetadataValueDto_Text(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case MetadataValueDto_Integer(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(field0, serializer);
      case MetadataValueDto_Float(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_f_64(field0, serializer);
      case MetadataValueDto_Rational(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_rational_dto(field0, serializer);
      case MetadataValueDto_SignedRational(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_rational_dto(field0, serializer);
      case MetadataValueDto_DateTime(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case MetadataValueDto_NaiveDateTime(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
      case MetadataValueDto_Bytes(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_String(field0, serializer);
      case MetadataValueDto_RationalArray(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_list_rational_dto(field0, serializer);
      case MetadataValueDto_SignedRationalArray(field0: final field0):
        sse_encode_i_32(9, serializer);
        sse_encode_list_rational_dto(field0, serializer);
      case MetadataValueDto_U8Array(field0: final field0):
        sse_encode_i_32(10, serializer);
        sse_encode_list_prim_u_8_strict(field0, serializer);
      case MetadataValueDto_U16Array(field0: final field0):
        sse_encode_i_32(11, serializer);
        sse_encode_list_prim_i_32_strict(field0, serializer);
      case MetadataValueDto_U32Array(field0: final field0):
        sse_encode_i_32(12, serializer);
        sse_encode_list_prim_i_64_strict(field0, serializer);
    }
  }

  @protected
  void sse_encode_metadata_value_kind(
    MetadataValueKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_gps_location_dto(
    GpsLocationDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_gps_location_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_image_exif_dto(
    ImageExifDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_image_exif_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_metadata_value_dto(
    MetadataValueDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_metadata_value_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_parse_error_dto(
    ParseErrorDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.ifdIndex, serializer);
    sse_encode_String(self.tagName, serializer);
    sse_encode_i_32(self.tagCode, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_png_text_metadata_dto(
    PngTextMetadataDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_rational_dto(RationalDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.numerator, serializer);
    sse_encode_i_64(self.denominator, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_video_track_dto(
    VideoTrackDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_metadata_entry_dto(self.entries, serializer);
    sse_encode_opt_box_autoadd_gps_location_dto(self.gps, serializer);
    sse_encode_list_parse_error_dto(self.parseErrors, serializer);
  }
}

@sealed
class MediaMetadataParserImpl extends RustOpaque
    implements MediaMetadataParser {
  // Not to be used by end users
  MediaMetadataParserImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MediaMetadataParserImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_MediaMetadataParser,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_MediaMetadataParser,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_MediaMetadataParserPtr,
  );
}
