// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/parser.dart';
import 'api/reader.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MediaMetadataParserPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParserPtr;

  @protected
  MediaMetadataParser
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  );

  @protected
  MediaMetadataParser
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  );

  @protected
  MediaMetadataParser
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AltitudeRefDto dco_decode_altitude_ref_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GpsLocationDto dco_decode_box_autoadd_gps_location_dto(dynamic raw);

  @protected
  ImageExifDto dco_decode_box_autoadd_image_exif_dto(dynamic raw);

  @protected
  MetadataValueDto dco_decode_box_autoadd_metadata_value_dto(dynamic raw);

  @protected
  RationalDto dco_decode_box_autoadd_rational_dto(dynamic raw);

  @protected
  VideoTrackDto dco_decode_box_autoadd_video_track_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FullImageMetadataDto dco_decode_full_image_metadata_dto(dynamic raw);

  @protected
  GpsLocationDto dco_decode_gps_location_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageExifDto dco_decode_image_exif_dto(dynamic raw);

  @protected
  LatitudeRefDto dco_decode_latitude_ref_dto(dynamic raw);

  @protected
  List<MetadataEntryDto> dco_decode_list_metadata_entry_dto(dynamic raw);

  @protected
  List<ParseErrorDto> dco_decode_list_parse_error_dto(dynamic raw);

  @protected
  List<PngTextMetadataDto> dco_decode_list_png_text_metadata_dto(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RationalDto> dco_decode_list_rational_dto(dynamic raw);

  @protected
  LongitudeRefDto dco_decode_longitude_ref_dto(dynamic raw);

  @protected
  MediaInfoError dco_decode_media_info_error(dynamic raw);

  @protected
  MediaInfoErrorCode dco_decode_media_info_error_code(dynamic raw);

  @protected
  MediaKindDto dco_decode_media_kind_dto(dynamic raw);

  @protected
  MediaMetadataDto dco_decode_media_metadata_dto(dynamic raw);

  @protected
  MetadataEntryDto dco_decode_metadata_entry_dto(dynamic raw);

  @protected
  MetadataValueDto dco_decode_metadata_value_dto(dynamic raw);

  @protected
  MetadataValueKind dco_decode_metadata_value_kind(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GpsLocationDto? dco_decode_opt_box_autoadd_gps_location_dto(dynamic raw);

  @protected
  ImageExifDto? dco_decode_opt_box_autoadd_image_exif_dto(dynamic raw);

  @protected
  MetadataValueDto? dco_decode_opt_box_autoadd_metadata_value_dto(dynamic raw);

  @protected
  ParseErrorDto dco_decode_parse_error_dto(dynamic raw);

  @protected
  PngTextMetadataDto dco_decode_png_text_metadata_dto(dynamic raw);

  @protected
  RationalDto dco_decode_rational_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoTrackDto dco_decode_video_track_dto(dynamic raw);

  @protected
  MediaMetadataParser
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  );

  @protected
  MediaMetadataParser
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  );

  @protected
  MediaMetadataParser
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AltitudeRefDto sse_decode_altitude_ref_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GpsLocationDto sse_decode_box_autoadd_gps_location_dto(
    SseDeserializer deserializer,
  );

  @protected
  ImageExifDto sse_decode_box_autoadd_image_exif_dto(
    SseDeserializer deserializer,
  );

  @protected
  MetadataValueDto sse_decode_box_autoadd_metadata_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  RationalDto sse_decode_box_autoadd_rational_dto(SseDeserializer deserializer);

  @protected
  VideoTrackDto sse_decode_box_autoadd_video_track_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FullImageMetadataDto sse_decode_full_image_metadata_dto(
    SseDeserializer deserializer,
  );

  @protected
  GpsLocationDto sse_decode_gps_location_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageExifDto sse_decode_image_exif_dto(SseDeserializer deserializer);

  @protected
  LatitudeRefDto sse_decode_latitude_ref_dto(SseDeserializer deserializer);

  @protected
  List<MetadataEntryDto> sse_decode_list_metadata_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ParseErrorDto> sse_decode_list_parse_error_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PngTextMetadataDto> sse_decode_list_png_text_metadata_dto(
    SseDeserializer deserializer,
  );

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RationalDto> sse_decode_list_rational_dto(SseDeserializer deserializer);

  @protected
  LongitudeRefDto sse_decode_longitude_ref_dto(SseDeserializer deserializer);

  @protected
  MediaInfoError sse_decode_media_info_error(SseDeserializer deserializer);

  @protected
  MediaInfoErrorCode sse_decode_media_info_error_code(
    SseDeserializer deserializer,
  );

  @protected
  MediaKindDto sse_decode_media_kind_dto(SseDeserializer deserializer);

  @protected
  MediaMetadataDto sse_decode_media_metadata_dto(SseDeserializer deserializer);

  @protected
  MetadataEntryDto sse_decode_metadata_entry_dto(SseDeserializer deserializer);

  @protected
  MetadataValueDto sse_decode_metadata_value_dto(SseDeserializer deserializer);

  @protected
  MetadataValueKind sse_decode_metadata_value_kind(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GpsLocationDto? sse_decode_opt_box_autoadd_gps_location_dto(
    SseDeserializer deserializer,
  );

  @protected
  ImageExifDto? sse_decode_opt_box_autoadd_image_exif_dto(
    SseDeserializer deserializer,
  );

  @protected
  MetadataValueDto? sse_decode_opt_box_autoadd_metadata_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  ParseErrorDto sse_decode_parse_error_dto(SseDeserializer deserializer);

  @protected
  PngTextMetadataDto sse_decode_png_text_metadata_dto(
    SseDeserializer deserializer,
  );

  @protected
  RationalDto sse_decode_rational_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoTrackDto sse_decode_video_track_dto(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    MediaMetadataParser self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_altitude_ref_dto(
    AltitudeRefDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gps_location_dto(
    GpsLocationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_exif_dto(
    ImageExifDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_metadata_value_dto(
    MetadataValueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rational_dto(
    RationalDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_video_track_dto(
    VideoTrackDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_full_image_metadata_dto(
    FullImageMetadataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gps_location_dto(
    GpsLocationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_exif_dto(ImageExifDto self, SseSerializer serializer);

  @protected
  void sse_encode_latitude_ref_dto(
    LatitudeRefDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_metadata_entry_dto(
    List<MetadataEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_parse_error_dto(
    List<ParseErrorDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_png_text_metadata_dto(
    List<PngTextMetadataDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rational_dto(
    List<RationalDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_longitude_ref_dto(
    LongitudeRefDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_info_error(
    MediaInfoError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_info_error_code(
    MediaInfoErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_kind_dto(MediaKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_media_metadata_dto(
    MediaMetadataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_entry_dto(
    MetadataEntryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_value_dto(
    MetadataValueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_value_kind(
    MetadataValueKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_gps_location_dto(
    GpsLocationDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_image_exif_dto(
    ImageExifDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_metadata_value_dto(
    MetadataValueDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parse_error_dto(ParseErrorDto self, SseSerializer serializer);

  @protected
  void sse_encode_png_text_metadata_dto(
    PngTextMetadataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rational_dto(RationalDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_track_dto(VideoTrackDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParserPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_xue_hua_media_info_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParserPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParserPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_xue_hua_media_info_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParser =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMediaMetadataParserPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
