// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <sstream>
#include <string>

namespace xue_hua_media_info_windows {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

template <typename T>
std::string PigeonInternalToString(const T& v);

std::string PigeonInternalToString(const bool& v);

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v);

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v);

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v);

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v);

std::string PigeonInternalToString(const ::flutter::EncodableValue& v);

template <typename T>
std::string PigeonInternalToString(const T& v) {
  std::stringstream ss;
  if constexpr (std::is_enum_v<T>) {
    ss << static_cast<int>(v);
  } else {
    ss << v;
  }
  return ss.str();
}

std::string PigeonInternalToString(const bool& v) {
  return v ? "true" : "false";
}

template <typename T>
std::string PigeonInternalToString(const std::vector<T>& v) {
  std::stringstream ss;
  ss << "[";
  for (size_t i = 0; i < v.size(); ++i) {
    if (i > 0) {
      ss << ", ";
    }
    ss << PigeonInternalToString(v[i]);
  }
  ss << "]";
  return ss.str();
}

template <typename K, typename V>
std::string PigeonInternalToString(const std::map<K, V>& v) {
  std::stringstream ss;
  ss << "{";
  bool first = true;
  for (const auto& kv : v) {
    if (!first) {
      ss << ", ";
    }
    first = false;
    ss << PigeonInternalToString(kv.first) << ": " << PigeonInternalToString(kv.second);
  }
  ss << "}";
  return ss.str();
}

template <typename T>
std::string PigeonInternalToString(const std::optional<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

template <typename T>
std::string PigeonInternalToString(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalToString(*v) : "null";
}

std::string PigeonInternalToString(const ::flutter::EncodableValue& v) {
  return std::visit(
      [](const auto& val) {
        using T = std::decay_t<decltype(val)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
          return std::string("null");
        } else if constexpr (std::is_same_v<T, bool>) {
          return val ? std::string("true") : std::string("false");
        } else if constexpr (std::is_same_v<T, std::string>) {
          return "\"" + val + "\"";
        } else if constexpr (std::is_same_v<T, ::flutter::CustomEncodableValue>) {
          return std::string("[custom]");
        } else {
          return PigeonInternalToString(val);
        }
      },
      v);
}

}  // namespace
// MediaSourceMessage

MediaSourceMessage::MediaSourceMessage(const SourceKindMessage& kind)
 : kind_(kind) {}

MediaSourceMessage::MediaSourceMessage(
  const SourceKindMessage& kind,
  const std::string* uri,
  const std::vector<uint8_t>* bytes)
 : kind_(kind),
    uri_(uri ? std::optional<std::string>(*uri) : std::nullopt),
    bytes_(bytes ? std::optional<std::vector<uint8_t>>(*bytes) : std::nullopt) {}

const SourceKindMessage& MediaSourceMessage::kind() const {
  return kind_;
}

void MediaSourceMessage::set_kind(const SourceKindMessage& value_arg) {
  kind_ = value_arg;
}


const std::string* MediaSourceMessage::uri() const {
  return uri_ ? &(*uri_) : nullptr;
}

void MediaSourceMessage::set_uri(const std::string_view* value_arg) {
  uri_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void MediaSourceMessage::set_uri(std::string_view value_arg) {
  uri_ = value_arg;
}


const std::vector<uint8_t>* MediaSourceMessage::bytes() const {
  return bytes_ ? &(*bytes_) : nullptr;
}

void MediaSourceMessage::set_bytes(const std::vector<uint8_t>* value_arg) {
  bytes_ = value_arg ? std::optional<std::vector<uint8_t>>(*value_arg) : std::nullopt;
}

void MediaSourceMessage::set_bytes(const std::vector<uint8_t>& value_arg) {
  bytes_ = value_arg;
}


EncodableList MediaSourceMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(CustomEncodableValue(kind_));
  list.push_back(uri_ ? EncodableValue(*uri_) : EncodableValue());
  list.push_back(bytes_ ? EncodableValue(*bytes_) : EncodableValue());
  return list;
}

MediaSourceMessage MediaSourceMessage::FromEncodableList(const EncodableList& list) {
  MediaSourceMessage decoded(
    std::any_cast<const SourceKindMessage&>(std::get<CustomEncodableValue>(list[0])));
  auto& encodable_uri = list[1];
  if (!encodable_uri.IsNull()) {
    decoded.set_uri(std::get<std::string>(encodable_uri));
  }
  auto& encodable_bytes = list[2];
  if (!encodable_bytes.IsNull()) {
    decoded.set_bytes(std::get<std::vector<uint8_t>>(encodable_bytes));
  }
  return decoded;
}

bool MediaSourceMessage::operator==(const MediaSourceMessage& other) const {
  return PigeonInternalDeepEquals(kind_, other.kind_) && PigeonInternalDeepEquals(uri_, other.uri_) && PigeonInternalDeepEquals(bytes_, other.bytes_);
}

bool MediaSourceMessage::operator!=(const MediaSourceMessage& other) const {
  return !(*this == other);
}

size_t MediaSourceMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(kind_);
  result = result * 31 + PigeonInternalDeepHash(uri_);
  result = result * 31 + PigeonInternalDeepHash(bytes_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const MediaSourceMessage& obj) {
  os << "MediaSourceMessage(";
  os << "kind: ";
  os << PigeonInternalToString(obj.kind_);
  os << ", uri: ";
  if (obj.uri_) {
    os << PigeonInternalToString(*obj.uri_);
  }
  else {
    os << "null";
  }
  os << ", bytes: ";
  if (obj.bytes_) {
    os << PigeonInternalToString(*obj.bytes_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const MediaSourceMessage& v) {
  return v.Hash();
}

// PixelSizeMessage

PixelSizeMessage::PixelSizeMessage(
  int64_t width,
  int64_t height)
 : width_(width),
    height_(height) {}

int64_t PixelSizeMessage::width() const {
  return width_;
}

void PixelSizeMessage::set_width(int64_t value_arg) {
  width_ = value_arg;
}


int64_t PixelSizeMessage::height() const {
  return height_;
}

void PixelSizeMessage::set_height(int64_t value_arg) {
  height_ = value_arg;
}


EncodableList PixelSizeMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(width_));
  list.push_back(EncodableValue(height_));
  return list;
}

PixelSizeMessage PixelSizeMessage::FromEncodableList(const EncodableList& list) {
  PixelSizeMessage decoded(
    std::get<int64_t>(list[0]),
    std::get<int64_t>(list[1]));
  return decoded;
}

bool PixelSizeMessage::operator==(const PixelSizeMessage& other) const {
  return PigeonInternalDeepEquals(width_, other.width_) && PigeonInternalDeepEquals(height_, other.height_);
}

bool PixelSizeMessage::operator!=(const PixelSizeMessage& other) const {
  return !(*this == other);
}

size_t PixelSizeMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(width_);
  result = result * 31 + PigeonInternalDeepHash(height_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PixelSizeMessage& obj) {
  os << "PixelSizeMessage(";
  os << "width: ";
  os << PigeonInternalToString(obj.width_);
  os << ", height: ";
  os << PigeonInternalToString(obj.height_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PixelSizeMessage& v) {
  return v.Hash();
}

// GpsLocationMessage

GpsLocationMessage::GpsLocationMessage(
  double latitude,
  double longitude)
 : latitude_(latitude),
    longitude_(longitude) {}

GpsLocationMessage::GpsLocationMessage(
  double latitude,
  double longitude,
  const double* altitude_meters)
 : latitude_(latitude),
    longitude_(longitude),
    altitude_meters_(altitude_meters ? std::optional<double>(*altitude_meters) : std::nullopt) {}

double GpsLocationMessage::latitude() const {
  return latitude_;
}

void GpsLocationMessage::set_latitude(double value_arg) {
  latitude_ = value_arg;
}


double GpsLocationMessage::longitude() const {
  return longitude_;
}

void GpsLocationMessage::set_longitude(double value_arg) {
  longitude_ = value_arg;
}


const double* GpsLocationMessage::altitude_meters() const {
  return altitude_meters_ ? &(*altitude_meters_) : nullptr;
}

void GpsLocationMessage::set_altitude_meters(const double* value_arg) {
  altitude_meters_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void GpsLocationMessage::set_altitude_meters(double value_arg) {
  altitude_meters_ = value_arg;
}


EncodableList GpsLocationMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(latitude_));
  list.push_back(EncodableValue(longitude_));
  list.push_back(altitude_meters_ ? EncodableValue(*altitude_meters_) : EncodableValue());
  return list;
}

GpsLocationMessage GpsLocationMessage::FromEncodableList(const EncodableList& list) {
  GpsLocationMessage decoded(
    std::get<double>(list[0]),
    std::get<double>(list[1]));
  auto& encodable_altitude_meters = list[2];
  if (!encodable_altitude_meters.IsNull()) {
    decoded.set_altitude_meters(std::get<double>(encodable_altitude_meters));
  }
  return decoded;
}

bool GpsLocationMessage::operator==(const GpsLocationMessage& other) const {
  return PigeonInternalDeepEquals(latitude_, other.latitude_) && PigeonInternalDeepEquals(longitude_, other.longitude_) && PigeonInternalDeepEquals(altitude_meters_, other.altitude_meters_);
}

bool GpsLocationMessage::operator!=(const GpsLocationMessage& other) const {
  return !(*this == other);
}

size_t GpsLocationMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(latitude_);
  result = result * 31 + PigeonInternalDeepHash(longitude_);
  result = result * 31 + PigeonInternalDeepHash(altitude_meters_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const GpsLocationMessage& obj) {
  os << "GpsLocationMessage(";
  os << "latitude: ";
  os << PigeonInternalToString(obj.latitude_);
  os << ", longitude: ";
  os << PigeonInternalToString(obj.longitude_);
  os << ", altitude_meters: ";
  if (obj.altitude_meters_) {
    os << PigeonInternalToString(*obj.altitude_meters_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const GpsLocationMessage& v) {
  return v.Hash();
}

// MetadataTagMessage

MetadataTagMessage::MetadataTagMessage(
  const std::string& name,
  const std::string& display_value)
 : name_(name),
    display_value_(display_value) {}

MetadataTagMessage::MetadataTagMessage(
  const std::string& name,
  const std::string& display_value,
  const std::string* string_value,
  const int64_t* int_value,
  const double* double_value)
 : name_(name),
    display_value_(display_value),
    string_value_(string_value ? std::optional<std::string>(*string_value) : std::nullopt),
    int_value_(int_value ? std::optional<int64_t>(*int_value) : std::nullopt),
    double_value_(double_value ? std::optional<double>(*double_value) : std::nullopt) {}

const std::string& MetadataTagMessage::name() const {
  return name_;
}

void MetadataTagMessage::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const std::string& MetadataTagMessage::display_value() const {
  return display_value_;
}

void MetadataTagMessage::set_display_value(std::string_view value_arg) {
  display_value_ = value_arg;
}


const std::string* MetadataTagMessage::string_value() const {
  return string_value_ ? &(*string_value_) : nullptr;
}

void MetadataTagMessage::set_string_value(const std::string_view* value_arg) {
  string_value_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void MetadataTagMessage::set_string_value(std::string_view value_arg) {
  string_value_ = value_arg;
}


const int64_t* MetadataTagMessage::int_value() const {
  return int_value_ ? &(*int_value_) : nullptr;
}

void MetadataTagMessage::set_int_value(const int64_t* value_arg) {
  int_value_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void MetadataTagMessage::set_int_value(int64_t value_arg) {
  int_value_ = value_arg;
}


const double* MetadataTagMessage::double_value() const {
  return double_value_ ? &(*double_value_) : nullptr;
}

void MetadataTagMessage::set_double_value(const double* value_arg) {
  double_value_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void MetadataTagMessage::set_double_value(double value_arg) {
  double_value_ = value_arg;
}


EncodableList MetadataTagMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(5);
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(display_value_));
  list.push_back(string_value_ ? EncodableValue(*string_value_) : EncodableValue());
  list.push_back(int_value_ ? EncodableValue(*int_value_) : EncodableValue());
  list.push_back(double_value_ ? EncodableValue(*double_value_) : EncodableValue());
  return list;
}

MetadataTagMessage MetadataTagMessage::FromEncodableList(const EncodableList& list) {
  MetadataTagMessage decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  auto& encodable_string_value = list[2];
  if (!encodable_string_value.IsNull()) {
    decoded.set_string_value(std::get<std::string>(encodable_string_value));
  }
  auto& encodable_int_value = list[3];
  if (!encodable_int_value.IsNull()) {
    decoded.set_int_value(std::get<int64_t>(encodable_int_value));
  }
  auto& encodable_double_value = list[4];
  if (!encodable_double_value.IsNull()) {
    decoded.set_double_value(std::get<double>(encodable_double_value));
  }
  return decoded;
}

bool MetadataTagMessage::operator==(const MetadataTagMessage& other) const {
  return PigeonInternalDeepEquals(name_, other.name_) && PigeonInternalDeepEquals(display_value_, other.display_value_) && PigeonInternalDeepEquals(string_value_, other.string_value_) && PigeonInternalDeepEquals(int_value_, other.int_value_) && PigeonInternalDeepEquals(double_value_, other.double_value_);
}

bool MetadataTagMessage::operator!=(const MetadataTagMessage& other) const {
  return !(*this == other);
}

size_t MetadataTagMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(name_);
  result = result * 31 + PigeonInternalDeepHash(display_value_);
  result = result * 31 + PigeonInternalDeepHash(string_value_);
  result = result * 31 + PigeonInternalDeepHash(int_value_);
  result = result * 31 + PigeonInternalDeepHash(double_value_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const MetadataTagMessage& obj) {
  os << "MetadataTagMessage(";
  os << "name: ";
  os << PigeonInternalToString(obj.name_);
  os << ", display_value: ";
  os << PigeonInternalToString(obj.display_value_);
  os << ", string_value: ";
  if (obj.string_value_) {
    os << PigeonInternalToString(*obj.string_value_);
  }
  else {
    os << "null";
  }
  os << ", int_value: ";
  if (obj.int_value_) {
    os << PigeonInternalToString(*obj.int_value_);
  }
  else {
    os << "null";
  }
  os << ", double_value: ";
  if (obj.double_value_) {
    os << PigeonInternalToString(*obj.double_value_);
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const MetadataTagMessage& v) {
  return v.Hash();
}

// PngTextChunkMessage

PngTextChunkMessage::PngTextChunkMessage(
  const std::string& key,
  const std::string& value)
 : key_(key),
    value_(value) {}

const std::string& PngTextChunkMessage::key() const {
  return key_;
}

void PngTextChunkMessage::set_key(std::string_view value_arg) {
  key_ = value_arg;
}


const std::string& PngTextChunkMessage::value() const {
  return value_;
}

void PngTextChunkMessage::set_value(std::string_view value_arg) {
  value_ = value_arg;
}


EncodableList PngTextChunkMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(key_));
  list.push_back(EncodableValue(value_));
  return list;
}

PngTextChunkMessage PngTextChunkMessage::FromEncodableList(const EncodableList& list) {
  PngTextChunkMessage decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  return decoded;
}

bool PngTextChunkMessage::operator==(const PngTextChunkMessage& other) const {
  return PigeonInternalDeepEquals(key_, other.key_) && PigeonInternalDeepEquals(value_, other.value_);
}

bool PngTextChunkMessage::operator!=(const PngTextChunkMessage& other) const {
  return !(*this == other);
}

size_t PngTextChunkMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(key_);
  result = result * 31 + PigeonInternalDeepHash(value_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const PngTextChunkMessage& obj) {
  os << "PngTextChunkMessage(";
  os << "key: ";
  os << PigeonInternalToString(obj.key_);
  os << ", value: ";
  os << PigeonInternalToString(obj.value_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const PngTextChunkMessage& v) {
  return v.Hash();
}

// ImageMetadataMessage

ImageMetadataMessage::ImageMetadataMessage(
  bool has_motion_photo,
  const EncodableList& png_text,
  const EncodableList& extra_tags)
 : has_motion_photo_(has_motion_photo),
    png_text_(png_text),
    extra_tags_(extra_tags) {}

ImageMetadataMessage::ImageMetadataMessage(
  const std::string* make,
  const std::string* model,
  const std::string* software,
  const PixelSizeMessage* size,
  const int64_t* orientation,
  const std::string* date_time_original,
  const std::string* date_time_digitized,
  const std::string* date_time_modified,
  const GpsLocationMessage* gps,
  bool has_motion_photo,
  const EncodableList& png_text,
  const EncodableList& extra_tags)
 : make_(make ? std::optional<std::string>(*make) : std::nullopt),
    model_(model ? std::optional<std::string>(*model) : std::nullopt),
    software_(software ? std::optional<std::string>(*software) : std::nullopt),
    size_(size ? std::make_unique<PixelSizeMessage>(*size) : nullptr),
    orientation_(orientation ? std::optional<int64_t>(*orientation) : std::nullopt),
    date_time_original_(date_time_original ? std::optional<std::string>(*date_time_original) : std::nullopt),
    date_time_digitized_(date_time_digitized ? std::optional<std::string>(*date_time_digitized) : std::nullopt),
    date_time_modified_(date_time_modified ? std::optional<std::string>(*date_time_modified) : std::nullopt),
    gps_(gps ? std::make_unique<GpsLocationMessage>(*gps) : nullptr),
    has_motion_photo_(has_motion_photo),
    png_text_(png_text),
    extra_tags_(extra_tags) {}

ImageMetadataMessage::ImageMetadataMessage(const ImageMetadataMessage& other)
 : make_(other.make_ ? std::optional<std::string>(*other.make_) : std::nullopt),
    model_(other.model_ ? std::optional<std::string>(*other.model_) : std::nullopt),
    software_(other.software_ ? std::optional<std::string>(*other.software_) : std::nullopt),
    size_(other.size_ ? std::make_unique<PixelSizeMessage>(*other.size_) : nullptr),
    orientation_(other.orientation_ ? std::optional<int64_t>(*other.orientation_) : std::nullopt),
    date_time_original_(other.date_time_original_ ? std::optional<std::string>(*other.date_time_original_) : std::nullopt),
    date_time_digitized_(other.date_time_digitized_ ? std::optional<std::string>(*other.date_time_digitized_) : std::nullopt),
    date_time_modified_(other.date_time_modified_ ? std::optional<std::string>(*other.date_time_modified_) : std::nullopt),
    gps_(other.gps_ ? std::make_unique<GpsLocationMessage>(*other.gps_) : nullptr),
    has_motion_photo_(other.has_motion_photo_),
    png_text_(other.png_text_),
    extra_tags_(other.extra_tags_) {}

ImageMetadataMessage& ImageMetadataMessage::operator=(const ImageMetadataMessage& other) {
  make_ = other.make_;
  model_ = other.model_;
  software_ = other.software_;
  size_ = other.size_ ? std::make_unique<PixelSizeMessage>(*other.size_) : nullptr;
  orientation_ = other.orientation_;
  date_time_original_ = other.date_time_original_;
  date_time_digitized_ = other.date_time_digitized_;
  date_time_modified_ = other.date_time_modified_;
  gps_ = other.gps_ ? std::make_unique<GpsLocationMessage>(*other.gps_) : nullptr;
  has_motion_photo_ = other.has_motion_photo_;
  png_text_ = other.png_text_;
  extra_tags_ = other.extra_tags_;
  return *this;
}

const std::string* ImageMetadataMessage::make() const {
  return make_ ? &(*make_) : nullptr;
}

void ImageMetadataMessage::set_make(const std::string_view* value_arg) {
  make_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ImageMetadataMessage::set_make(std::string_view value_arg) {
  make_ = value_arg;
}


const std::string* ImageMetadataMessage::model() const {
  return model_ ? &(*model_) : nullptr;
}

void ImageMetadataMessage::set_model(const std::string_view* value_arg) {
  model_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ImageMetadataMessage::set_model(std::string_view value_arg) {
  model_ = value_arg;
}


const std::string* ImageMetadataMessage::software() const {
  return software_ ? &(*software_) : nullptr;
}

void ImageMetadataMessage::set_software(const std::string_view* value_arg) {
  software_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ImageMetadataMessage::set_software(std::string_view value_arg) {
  software_ = value_arg;
}


const PixelSizeMessage* ImageMetadataMessage::size() const {
  return size_.get();
}

void ImageMetadataMessage::set_size(const PixelSizeMessage* value_arg) {
  size_ = value_arg ? std::make_unique<PixelSizeMessage>(*value_arg) : nullptr;
}

void ImageMetadataMessage::set_size(const PixelSizeMessage& value_arg) {
  size_ = std::make_unique<PixelSizeMessage>(value_arg);
}


const int64_t* ImageMetadataMessage::orientation() const {
  return orientation_ ? &(*orientation_) : nullptr;
}

void ImageMetadataMessage::set_orientation(const int64_t* value_arg) {
  orientation_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ImageMetadataMessage::set_orientation(int64_t value_arg) {
  orientation_ = value_arg;
}


const std::string* ImageMetadataMessage::date_time_original() const {
  return date_time_original_ ? &(*date_time_original_) : nullptr;
}

void ImageMetadataMessage::set_date_time_original(const std::string_view* value_arg) {
  date_time_original_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ImageMetadataMessage::set_date_time_original(std::string_view value_arg) {
  date_time_original_ = value_arg;
}


const std::string* ImageMetadataMessage::date_time_digitized() const {
  return date_time_digitized_ ? &(*date_time_digitized_) : nullptr;
}

void ImageMetadataMessage::set_date_time_digitized(const std::string_view* value_arg) {
  date_time_digitized_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ImageMetadataMessage::set_date_time_digitized(std::string_view value_arg) {
  date_time_digitized_ = value_arg;
}


const std::string* ImageMetadataMessage::date_time_modified() const {
  return date_time_modified_ ? &(*date_time_modified_) : nullptr;
}

void ImageMetadataMessage::set_date_time_modified(const std::string_view* value_arg) {
  date_time_modified_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ImageMetadataMessage::set_date_time_modified(std::string_view value_arg) {
  date_time_modified_ = value_arg;
}


const GpsLocationMessage* ImageMetadataMessage::gps() const {
  return gps_.get();
}

void ImageMetadataMessage::set_gps(const GpsLocationMessage* value_arg) {
  gps_ = value_arg ? std::make_unique<GpsLocationMessage>(*value_arg) : nullptr;
}

void ImageMetadataMessage::set_gps(const GpsLocationMessage& value_arg) {
  gps_ = std::make_unique<GpsLocationMessage>(value_arg);
}


bool ImageMetadataMessage::has_motion_photo() const {
  return has_motion_photo_;
}

void ImageMetadataMessage::set_has_motion_photo(bool value_arg) {
  has_motion_photo_ = value_arg;
}


const EncodableList& ImageMetadataMessage::png_text() const {
  return png_text_;
}

void ImageMetadataMessage::set_png_text(const EncodableList& value_arg) {
  png_text_ = value_arg;
}


const EncodableList& ImageMetadataMessage::extra_tags() const {
  return extra_tags_;
}

void ImageMetadataMessage::set_extra_tags(const EncodableList& value_arg) {
  extra_tags_ = value_arg;
}


EncodableList ImageMetadataMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(12);
  list.push_back(make_ ? EncodableValue(*make_) : EncodableValue());
  list.push_back(model_ ? EncodableValue(*model_) : EncodableValue());
  list.push_back(software_ ? EncodableValue(*software_) : EncodableValue());
  list.push_back(size_ ? CustomEncodableValue(*size_) : EncodableValue());
  list.push_back(orientation_ ? EncodableValue(*orientation_) : EncodableValue());
  list.push_back(date_time_original_ ? EncodableValue(*date_time_original_) : EncodableValue());
  list.push_back(date_time_digitized_ ? EncodableValue(*date_time_digitized_) : EncodableValue());
  list.push_back(date_time_modified_ ? EncodableValue(*date_time_modified_) : EncodableValue());
  list.push_back(gps_ ? CustomEncodableValue(*gps_) : EncodableValue());
  list.push_back(EncodableValue(has_motion_photo_));
  list.push_back(EncodableValue(png_text_));
  list.push_back(EncodableValue(extra_tags_));
  return list;
}

ImageMetadataMessage ImageMetadataMessage::FromEncodableList(const EncodableList& list) {
  ImageMetadataMessage decoded(
    std::get<bool>(list[9]),
    std::get<EncodableList>(list[10]),
    std::get<EncodableList>(list[11]));
  auto& encodable_make = list[0];
  if (!encodable_make.IsNull()) {
    decoded.set_make(std::get<std::string>(encodable_make));
  }
  auto& encodable_model = list[1];
  if (!encodable_model.IsNull()) {
    decoded.set_model(std::get<std::string>(encodable_model));
  }
  auto& encodable_software = list[2];
  if (!encodable_software.IsNull()) {
    decoded.set_software(std::get<std::string>(encodable_software));
  }
  auto& encodable_size = list[3];
  if (!encodable_size.IsNull()) {
    decoded.set_size(std::any_cast<const PixelSizeMessage&>(std::get<CustomEncodableValue>(encodable_size)));
  }
  auto& encodable_orientation = list[4];
  if (!encodable_orientation.IsNull()) {
    decoded.set_orientation(std::get<int64_t>(encodable_orientation));
  }
  auto& encodable_date_time_original = list[5];
  if (!encodable_date_time_original.IsNull()) {
    decoded.set_date_time_original(std::get<std::string>(encodable_date_time_original));
  }
  auto& encodable_date_time_digitized = list[6];
  if (!encodable_date_time_digitized.IsNull()) {
    decoded.set_date_time_digitized(std::get<std::string>(encodable_date_time_digitized));
  }
  auto& encodable_date_time_modified = list[7];
  if (!encodable_date_time_modified.IsNull()) {
    decoded.set_date_time_modified(std::get<std::string>(encodable_date_time_modified));
  }
  auto& encodable_gps = list[8];
  if (!encodable_gps.IsNull()) {
    decoded.set_gps(std::any_cast<const GpsLocationMessage&>(std::get<CustomEncodableValue>(encodable_gps)));
  }
  return decoded;
}

bool ImageMetadataMessage::operator==(const ImageMetadataMessage& other) const {
  return PigeonInternalDeepEquals(make_, other.make_) && PigeonInternalDeepEquals(model_, other.model_) && PigeonInternalDeepEquals(software_, other.software_) && PigeonInternalDeepEquals(size_, other.size_) && PigeonInternalDeepEquals(orientation_, other.orientation_) && PigeonInternalDeepEquals(date_time_original_, other.date_time_original_) && PigeonInternalDeepEquals(date_time_digitized_, other.date_time_digitized_) && PigeonInternalDeepEquals(date_time_modified_, other.date_time_modified_) && PigeonInternalDeepEquals(gps_, other.gps_) && PigeonInternalDeepEquals(has_motion_photo_, other.has_motion_photo_) && PigeonInternalDeepEquals(png_text_, other.png_text_) && PigeonInternalDeepEquals(extra_tags_, other.extra_tags_);
}

bool ImageMetadataMessage::operator!=(const ImageMetadataMessage& other) const {
  return !(*this == other);
}

size_t ImageMetadataMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(make_);
  result = result * 31 + PigeonInternalDeepHash(model_);
  result = result * 31 + PigeonInternalDeepHash(software_);
  result = result * 31 + PigeonInternalDeepHash(size_);
  result = result * 31 + PigeonInternalDeepHash(orientation_);
  result = result * 31 + PigeonInternalDeepHash(date_time_original_);
  result = result * 31 + PigeonInternalDeepHash(date_time_digitized_);
  result = result * 31 + PigeonInternalDeepHash(date_time_modified_);
  result = result * 31 + PigeonInternalDeepHash(gps_);
  result = result * 31 + PigeonInternalDeepHash(has_motion_photo_);
  result = result * 31 + PigeonInternalDeepHash(png_text_);
  result = result * 31 + PigeonInternalDeepHash(extra_tags_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const ImageMetadataMessage& obj) {
  os << "ImageMetadataMessage(";
  os << "make: ";
  if (obj.make_) {
    os << PigeonInternalToString(*obj.make_);
  }
  else {
    os << "null";
  }
  os << ", model: ";
  if (obj.model_) {
    os << PigeonInternalToString(*obj.model_);
  }
  else {
    os << "null";
  }
  os << ", software: ";
  if (obj.software_) {
    os << PigeonInternalToString(*obj.software_);
  }
  else {
    os << "null";
  }
  os << ", size: ";
  if (obj.size_) {
    os << *obj.size_;
  }
  else {
    os << "null";
  }
  os << ", orientation: ";
  if (obj.orientation_) {
    os << PigeonInternalToString(*obj.orientation_);
  }
  else {
    os << "null";
  }
  os << ", date_time_original: ";
  if (obj.date_time_original_) {
    os << PigeonInternalToString(*obj.date_time_original_);
  }
  else {
    os << "null";
  }
  os << ", date_time_digitized: ";
  if (obj.date_time_digitized_) {
    os << PigeonInternalToString(*obj.date_time_digitized_);
  }
  else {
    os << "null";
  }
  os << ", date_time_modified: ";
  if (obj.date_time_modified_) {
    os << PigeonInternalToString(*obj.date_time_modified_);
  }
  else {
    os << "null";
  }
  os << ", gps: ";
  if (obj.gps_) {
    os << *obj.gps_;
  }
  else {
    os << "null";
  }
  os << ", has_motion_photo: ";
  os << PigeonInternalToString(obj.has_motion_photo_);
  os << ", png_text: ";
  os << PigeonInternalToString(obj.png_text_);
  os << ", extra_tags: ";
  os << PigeonInternalToString(obj.extra_tags_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const ImageMetadataMessage& v) {
  return v.Hash();
}

// VideoMetadataMessage

VideoMetadataMessage::VideoMetadataMessage(const EncodableList& extra_tags)
 : extra_tags_(extra_tags) {}

VideoMetadataMessage::VideoMetadataMessage(
  const int64_t* duration_ms,
  const PixelSizeMessage* size,
  const int64_t* bitrate,
  const int64_t* rotation_degrees,
  const std::string* make,
  const std::string* model,
  const GpsLocationMessage* gps,
  const EncodableList& extra_tags)
 : duration_ms_(duration_ms ? std::optional<int64_t>(*duration_ms) : std::nullopt),
    size_(size ? std::make_unique<PixelSizeMessage>(*size) : nullptr),
    bitrate_(bitrate ? std::optional<int64_t>(*bitrate) : std::nullopt),
    rotation_degrees_(rotation_degrees ? std::optional<int64_t>(*rotation_degrees) : std::nullopt),
    make_(make ? std::optional<std::string>(*make) : std::nullopt),
    model_(model ? std::optional<std::string>(*model) : std::nullopt),
    gps_(gps ? std::make_unique<GpsLocationMessage>(*gps) : nullptr),
    extra_tags_(extra_tags) {}

VideoMetadataMessage::VideoMetadataMessage(const VideoMetadataMessage& other)
 : duration_ms_(other.duration_ms_ ? std::optional<int64_t>(*other.duration_ms_) : std::nullopt),
    size_(other.size_ ? std::make_unique<PixelSizeMessage>(*other.size_) : nullptr),
    bitrate_(other.bitrate_ ? std::optional<int64_t>(*other.bitrate_) : std::nullopt),
    rotation_degrees_(other.rotation_degrees_ ? std::optional<int64_t>(*other.rotation_degrees_) : std::nullopt),
    make_(other.make_ ? std::optional<std::string>(*other.make_) : std::nullopt),
    model_(other.model_ ? std::optional<std::string>(*other.model_) : std::nullopt),
    gps_(other.gps_ ? std::make_unique<GpsLocationMessage>(*other.gps_) : nullptr),
    extra_tags_(other.extra_tags_) {}

VideoMetadataMessage& VideoMetadataMessage::operator=(const VideoMetadataMessage& other) {
  duration_ms_ = other.duration_ms_;
  size_ = other.size_ ? std::make_unique<PixelSizeMessage>(*other.size_) : nullptr;
  bitrate_ = other.bitrate_;
  rotation_degrees_ = other.rotation_degrees_;
  make_ = other.make_;
  model_ = other.model_;
  gps_ = other.gps_ ? std::make_unique<GpsLocationMessage>(*other.gps_) : nullptr;
  extra_tags_ = other.extra_tags_;
  return *this;
}

const int64_t* VideoMetadataMessage::duration_ms() const {
  return duration_ms_ ? &(*duration_ms_) : nullptr;
}

void VideoMetadataMessage::set_duration_ms(const int64_t* value_arg) {
  duration_ms_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void VideoMetadataMessage::set_duration_ms(int64_t value_arg) {
  duration_ms_ = value_arg;
}


const PixelSizeMessage* VideoMetadataMessage::size() const {
  return size_.get();
}

void VideoMetadataMessage::set_size(const PixelSizeMessage* value_arg) {
  size_ = value_arg ? std::make_unique<PixelSizeMessage>(*value_arg) : nullptr;
}

void VideoMetadataMessage::set_size(const PixelSizeMessage& value_arg) {
  size_ = std::make_unique<PixelSizeMessage>(value_arg);
}


const int64_t* VideoMetadataMessage::bitrate() const {
  return bitrate_ ? &(*bitrate_) : nullptr;
}

void VideoMetadataMessage::set_bitrate(const int64_t* value_arg) {
  bitrate_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void VideoMetadataMessage::set_bitrate(int64_t value_arg) {
  bitrate_ = value_arg;
}


const int64_t* VideoMetadataMessage::rotation_degrees() const {
  return rotation_degrees_ ? &(*rotation_degrees_) : nullptr;
}

void VideoMetadataMessage::set_rotation_degrees(const int64_t* value_arg) {
  rotation_degrees_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void VideoMetadataMessage::set_rotation_degrees(int64_t value_arg) {
  rotation_degrees_ = value_arg;
}


const std::string* VideoMetadataMessage::make() const {
  return make_ ? &(*make_) : nullptr;
}

void VideoMetadataMessage::set_make(const std::string_view* value_arg) {
  make_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void VideoMetadataMessage::set_make(std::string_view value_arg) {
  make_ = value_arg;
}


const std::string* VideoMetadataMessage::model() const {
  return model_ ? &(*model_) : nullptr;
}

void VideoMetadataMessage::set_model(const std::string_view* value_arg) {
  model_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void VideoMetadataMessage::set_model(std::string_view value_arg) {
  model_ = value_arg;
}


const GpsLocationMessage* VideoMetadataMessage::gps() const {
  return gps_.get();
}

void VideoMetadataMessage::set_gps(const GpsLocationMessage* value_arg) {
  gps_ = value_arg ? std::make_unique<GpsLocationMessage>(*value_arg) : nullptr;
}

void VideoMetadataMessage::set_gps(const GpsLocationMessage& value_arg) {
  gps_ = std::make_unique<GpsLocationMessage>(value_arg);
}


const EncodableList& VideoMetadataMessage::extra_tags() const {
  return extra_tags_;
}

void VideoMetadataMessage::set_extra_tags(const EncodableList& value_arg) {
  extra_tags_ = value_arg;
}


EncodableList VideoMetadataMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(duration_ms_ ? EncodableValue(*duration_ms_) : EncodableValue());
  list.push_back(size_ ? CustomEncodableValue(*size_) : EncodableValue());
  list.push_back(bitrate_ ? EncodableValue(*bitrate_) : EncodableValue());
  list.push_back(rotation_degrees_ ? EncodableValue(*rotation_degrees_) : EncodableValue());
  list.push_back(make_ ? EncodableValue(*make_) : EncodableValue());
  list.push_back(model_ ? EncodableValue(*model_) : EncodableValue());
  list.push_back(gps_ ? CustomEncodableValue(*gps_) : EncodableValue());
  list.push_back(EncodableValue(extra_tags_));
  return list;
}

VideoMetadataMessage VideoMetadataMessage::FromEncodableList(const EncodableList& list) {
  VideoMetadataMessage decoded(
    std::get<EncodableList>(list[7]));
  auto& encodable_duration_ms = list[0];
  if (!encodable_duration_ms.IsNull()) {
    decoded.set_duration_ms(std::get<int64_t>(encodable_duration_ms));
  }
  auto& encodable_size = list[1];
  if (!encodable_size.IsNull()) {
    decoded.set_size(std::any_cast<const PixelSizeMessage&>(std::get<CustomEncodableValue>(encodable_size)));
  }
  auto& encodable_bitrate = list[2];
  if (!encodable_bitrate.IsNull()) {
    decoded.set_bitrate(std::get<int64_t>(encodable_bitrate));
  }
  auto& encodable_rotation_degrees = list[3];
  if (!encodable_rotation_degrees.IsNull()) {
    decoded.set_rotation_degrees(std::get<int64_t>(encodable_rotation_degrees));
  }
  auto& encodable_make = list[4];
  if (!encodable_make.IsNull()) {
    decoded.set_make(std::get<std::string>(encodable_make));
  }
  auto& encodable_model = list[5];
  if (!encodable_model.IsNull()) {
    decoded.set_model(std::get<std::string>(encodable_model));
  }
  auto& encodable_gps = list[6];
  if (!encodable_gps.IsNull()) {
    decoded.set_gps(std::any_cast<const GpsLocationMessage&>(std::get<CustomEncodableValue>(encodable_gps)));
  }
  return decoded;
}

bool VideoMetadataMessage::operator==(const VideoMetadataMessage& other) const {
  return PigeonInternalDeepEquals(duration_ms_, other.duration_ms_) && PigeonInternalDeepEquals(size_, other.size_) && PigeonInternalDeepEquals(bitrate_, other.bitrate_) && PigeonInternalDeepEquals(rotation_degrees_, other.rotation_degrees_) && PigeonInternalDeepEquals(make_, other.make_) && PigeonInternalDeepEquals(model_, other.model_) && PigeonInternalDeepEquals(gps_, other.gps_) && PigeonInternalDeepEquals(extra_tags_, other.extra_tags_);
}

bool VideoMetadataMessage::operator!=(const VideoMetadataMessage& other) const {
  return !(*this == other);
}

size_t VideoMetadataMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(duration_ms_);
  result = result * 31 + PigeonInternalDeepHash(size_);
  result = result * 31 + PigeonInternalDeepHash(bitrate_);
  result = result * 31 + PigeonInternalDeepHash(rotation_degrees_);
  result = result * 31 + PigeonInternalDeepHash(make_);
  result = result * 31 + PigeonInternalDeepHash(model_);
  result = result * 31 + PigeonInternalDeepHash(gps_);
  result = result * 31 + PigeonInternalDeepHash(extra_tags_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const VideoMetadataMessage& obj) {
  os << "VideoMetadataMessage(";
  os << "duration_ms: ";
  if (obj.duration_ms_) {
    os << PigeonInternalToString(*obj.duration_ms_);
  }
  else {
    os << "null";
  }
  os << ", size: ";
  if (obj.size_) {
    os << *obj.size_;
  }
  else {
    os << "null";
  }
  os << ", bitrate: ";
  if (obj.bitrate_) {
    os << PigeonInternalToString(*obj.bitrate_);
  }
  else {
    os << "null";
  }
  os << ", rotation_degrees: ";
  if (obj.rotation_degrees_) {
    os << PigeonInternalToString(*obj.rotation_degrees_);
  }
  else {
    os << "null";
  }
  os << ", make: ";
  if (obj.make_) {
    os << PigeonInternalToString(*obj.make_);
  }
  else {
    os << "null";
  }
  os << ", model: ";
  if (obj.model_) {
    os << PigeonInternalToString(*obj.model_);
  }
  else {
    os << "null";
  }
  os << ", gps: ";
  if (obj.gps_) {
    os << *obj.gps_;
  }
  else {
    os << "null";
  }
  os << ", extra_tags: ";
  os << PigeonInternalToString(obj.extra_tags_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const VideoMetadataMessage& v) {
  return v.Hash();
}

// AudioMetadataMessage

AudioMetadataMessage::AudioMetadataMessage(const EncodableList& extra_tags)
 : extra_tags_(extra_tags) {}

AudioMetadataMessage::AudioMetadataMessage(
  const int64_t* duration_ms,
  const int64_t* bitrate,
  const int64_t* sample_rate,
  const int64_t* channel_count,
  const std::string* make,
  const std::string* model,
  const GpsLocationMessage* gps,
  const EncodableList& extra_tags)
 : duration_ms_(duration_ms ? std::optional<int64_t>(*duration_ms) : std::nullopt),
    bitrate_(bitrate ? std::optional<int64_t>(*bitrate) : std::nullopt),
    sample_rate_(sample_rate ? std::optional<int64_t>(*sample_rate) : std::nullopt),
    channel_count_(channel_count ? std::optional<int64_t>(*channel_count) : std::nullopt),
    make_(make ? std::optional<std::string>(*make) : std::nullopt),
    model_(model ? std::optional<std::string>(*model) : std::nullopt),
    gps_(gps ? std::make_unique<GpsLocationMessage>(*gps) : nullptr),
    extra_tags_(extra_tags) {}

AudioMetadataMessage::AudioMetadataMessage(const AudioMetadataMessage& other)
 : duration_ms_(other.duration_ms_ ? std::optional<int64_t>(*other.duration_ms_) : std::nullopt),
    bitrate_(other.bitrate_ ? std::optional<int64_t>(*other.bitrate_) : std::nullopt),
    sample_rate_(other.sample_rate_ ? std::optional<int64_t>(*other.sample_rate_) : std::nullopt),
    channel_count_(other.channel_count_ ? std::optional<int64_t>(*other.channel_count_) : std::nullopt),
    make_(other.make_ ? std::optional<std::string>(*other.make_) : std::nullopt),
    model_(other.model_ ? std::optional<std::string>(*other.model_) : std::nullopt),
    gps_(other.gps_ ? std::make_unique<GpsLocationMessage>(*other.gps_) : nullptr),
    extra_tags_(other.extra_tags_) {}

AudioMetadataMessage& AudioMetadataMessage::operator=(const AudioMetadataMessage& other) {
  duration_ms_ = other.duration_ms_;
  bitrate_ = other.bitrate_;
  sample_rate_ = other.sample_rate_;
  channel_count_ = other.channel_count_;
  make_ = other.make_;
  model_ = other.model_;
  gps_ = other.gps_ ? std::make_unique<GpsLocationMessage>(*other.gps_) : nullptr;
  extra_tags_ = other.extra_tags_;
  return *this;
}

const int64_t* AudioMetadataMessage::duration_ms() const {
  return duration_ms_ ? &(*duration_ms_) : nullptr;
}

void AudioMetadataMessage::set_duration_ms(const int64_t* value_arg) {
  duration_ms_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void AudioMetadataMessage::set_duration_ms(int64_t value_arg) {
  duration_ms_ = value_arg;
}


const int64_t* AudioMetadataMessage::bitrate() const {
  return bitrate_ ? &(*bitrate_) : nullptr;
}

void AudioMetadataMessage::set_bitrate(const int64_t* value_arg) {
  bitrate_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void AudioMetadataMessage::set_bitrate(int64_t value_arg) {
  bitrate_ = value_arg;
}


const int64_t* AudioMetadataMessage::sample_rate() const {
  return sample_rate_ ? &(*sample_rate_) : nullptr;
}

void AudioMetadataMessage::set_sample_rate(const int64_t* value_arg) {
  sample_rate_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void AudioMetadataMessage::set_sample_rate(int64_t value_arg) {
  sample_rate_ = value_arg;
}


const int64_t* AudioMetadataMessage::channel_count() const {
  return channel_count_ ? &(*channel_count_) : nullptr;
}

void AudioMetadataMessage::set_channel_count(const int64_t* value_arg) {
  channel_count_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void AudioMetadataMessage::set_channel_count(int64_t value_arg) {
  channel_count_ = value_arg;
}


const std::string* AudioMetadataMessage::make() const {
  return make_ ? &(*make_) : nullptr;
}

void AudioMetadataMessage::set_make(const std::string_view* value_arg) {
  make_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void AudioMetadataMessage::set_make(std::string_view value_arg) {
  make_ = value_arg;
}


const std::string* AudioMetadataMessage::model() const {
  return model_ ? &(*model_) : nullptr;
}

void AudioMetadataMessage::set_model(const std::string_view* value_arg) {
  model_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void AudioMetadataMessage::set_model(std::string_view value_arg) {
  model_ = value_arg;
}


const GpsLocationMessage* AudioMetadataMessage::gps() const {
  return gps_.get();
}

void AudioMetadataMessage::set_gps(const GpsLocationMessage* value_arg) {
  gps_ = value_arg ? std::make_unique<GpsLocationMessage>(*value_arg) : nullptr;
}

void AudioMetadataMessage::set_gps(const GpsLocationMessage& value_arg) {
  gps_ = std::make_unique<GpsLocationMessage>(value_arg);
}


const EncodableList& AudioMetadataMessage::extra_tags() const {
  return extra_tags_;
}

void AudioMetadataMessage::set_extra_tags(const EncodableList& value_arg) {
  extra_tags_ = value_arg;
}


EncodableList AudioMetadataMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(duration_ms_ ? EncodableValue(*duration_ms_) : EncodableValue());
  list.push_back(bitrate_ ? EncodableValue(*bitrate_) : EncodableValue());
  list.push_back(sample_rate_ ? EncodableValue(*sample_rate_) : EncodableValue());
  list.push_back(channel_count_ ? EncodableValue(*channel_count_) : EncodableValue());
  list.push_back(make_ ? EncodableValue(*make_) : EncodableValue());
  list.push_back(model_ ? EncodableValue(*model_) : EncodableValue());
  list.push_back(gps_ ? CustomEncodableValue(*gps_) : EncodableValue());
  list.push_back(EncodableValue(extra_tags_));
  return list;
}

AudioMetadataMessage AudioMetadataMessage::FromEncodableList(const EncodableList& list) {
  AudioMetadataMessage decoded(
    std::get<EncodableList>(list[7]));
  auto& encodable_duration_ms = list[0];
  if (!encodable_duration_ms.IsNull()) {
    decoded.set_duration_ms(std::get<int64_t>(encodable_duration_ms));
  }
  auto& encodable_bitrate = list[1];
  if (!encodable_bitrate.IsNull()) {
    decoded.set_bitrate(std::get<int64_t>(encodable_bitrate));
  }
  auto& encodable_sample_rate = list[2];
  if (!encodable_sample_rate.IsNull()) {
    decoded.set_sample_rate(std::get<int64_t>(encodable_sample_rate));
  }
  auto& encodable_channel_count = list[3];
  if (!encodable_channel_count.IsNull()) {
    decoded.set_channel_count(std::get<int64_t>(encodable_channel_count));
  }
  auto& encodable_make = list[4];
  if (!encodable_make.IsNull()) {
    decoded.set_make(std::get<std::string>(encodable_make));
  }
  auto& encodable_model = list[5];
  if (!encodable_model.IsNull()) {
    decoded.set_model(std::get<std::string>(encodable_model));
  }
  auto& encodable_gps = list[6];
  if (!encodable_gps.IsNull()) {
    decoded.set_gps(std::any_cast<const GpsLocationMessage&>(std::get<CustomEncodableValue>(encodable_gps)));
  }
  return decoded;
}

bool AudioMetadataMessage::operator==(const AudioMetadataMessage& other) const {
  return PigeonInternalDeepEquals(duration_ms_, other.duration_ms_) && PigeonInternalDeepEquals(bitrate_, other.bitrate_) && PigeonInternalDeepEquals(sample_rate_, other.sample_rate_) && PigeonInternalDeepEquals(channel_count_, other.channel_count_) && PigeonInternalDeepEquals(make_, other.make_) && PigeonInternalDeepEquals(model_, other.model_) && PigeonInternalDeepEquals(gps_, other.gps_) && PigeonInternalDeepEquals(extra_tags_, other.extra_tags_);
}

bool AudioMetadataMessage::operator!=(const AudioMetadataMessage& other) const {
  return !(*this == other);
}

size_t AudioMetadataMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(duration_ms_);
  result = result * 31 + PigeonInternalDeepHash(bitrate_);
  result = result * 31 + PigeonInternalDeepHash(sample_rate_);
  result = result * 31 + PigeonInternalDeepHash(channel_count_);
  result = result * 31 + PigeonInternalDeepHash(make_);
  result = result * 31 + PigeonInternalDeepHash(model_);
  result = result * 31 + PigeonInternalDeepHash(gps_);
  result = result * 31 + PigeonInternalDeepHash(extra_tags_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const AudioMetadataMessage& obj) {
  os << "AudioMetadataMessage(";
  os << "duration_ms: ";
  if (obj.duration_ms_) {
    os << PigeonInternalToString(*obj.duration_ms_);
  }
  else {
    os << "null";
  }
  os << ", bitrate: ";
  if (obj.bitrate_) {
    os << PigeonInternalToString(*obj.bitrate_);
  }
  else {
    os << "null";
  }
  os << ", sample_rate: ";
  if (obj.sample_rate_) {
    os << PigeonInternalToString(*obj.sample_rate_);
  }
  else {
    os << "null";
  }
  os << ", channel_count: ";
  if (obj.channel_count_) {
    os << PigeonInternalToString(*obj.channel_count_);
  }
  else {
    os << "null";
  }
  os << ", make: ";
  if (obj.make_) {
    os << PigeonInternalToString(*obj.make_);
  }
  else {
    os << "null";
  }
  os << ", model: ";
  if (obj.model_) {
    os << PigeonInternalToString(*obj.model_);
  }
  else {
    os << "null";
  }
  os << ", gps: ";
  if (obj.gps_) {
    os << *obj.gps_;
  }
  else {
    os << "null";
  }
  os << ", extra_tags: ";
  os << PigeonInternalToString(obj.extra_tags_);
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const AudioMetadataMessage& v) {
  return v.Hash();
}

// MediaMetadataMessage

MediaMetadataMessage::MediaMetadataMessage(const MediaKindMessage& kind)
 : kind_(kind) {}

MediaMetadataMessage::MediaMetadataMessage(
  const MediaKindMessage& kind,
  const ImageMetadataMessage* image,
  const VideoMetadataMessage* video,
  const AudioMetadataMessage* audio)
 : kind_(kind),
    image_(image ? std::make_unique<ImageMetadataMessage>(*image) : nullptr),
    video_(video ? std::make_unique<VideoMetadataMessage>(*video) : nullptr),
    audio_(audio ? std::make_unique<AudioMetadataMessage>(*audio) : nullptr) {}

MediaMetadataMessage::MediaMetadataMessage(const MediaMetadataMessage& other)
 : kind_(other.kind_),
    image_(other.image_ ? std::make_unique<ImageMetadataMessage>(*other.image_) : nullptr),
    video_(other.video_ ? std::make_unique<VideoMetadataMessage>(*other.video_) : nullptr),
    audio_(other.audio_ ? std::make_unique<AudioMetadataMessage>(*other.audio_) : nullptr) {}

MediaMetadataMessage& MediaMetadataMessage::operator=(const MediaMetadataMessage& other) {
  kind_ = other.kind_;
  image_ = other.image_ ? std::make_unique<ImageMetadataMessage>(*other.image_) : nullptr;
  video_ = other.video_ ? std::make_unique<VideoMetadataMessage>(*other.video_) : nullptr;
  audio_ = other.audio_ ? std::make_unique<AudioMetadataMessage>(*other.audio_) : nullptr;
  return *this;
}

const MediaKindMessage& MediaMetadataMessage::kind() const {
  return kind_;
}

void MediaMetadataMessage::set_kind(const MediaKindMessage& value_arg) {
  kind_ = value_arg;
}


const ImageMetadataMessage* MediaMetadataMessage::image() const {
  return image_.get();
}

void MediaMetadataMessage::set_image(const ImageMetadataMessage* value_arg) {
  image_ = value_arg ? std::make_unique<ImageMetadataMessage>(*value_arg) : nullptr;
}

void MediaMetadataMessage::set_image(const ImageMetadataMessage& value_arg) {
  image_ = std::make_unique<ImageMetadataMessage>(value_arg);
}


const VideoMetadataMessage* MediaMetadataMessage::video() const {
  return video_.get();
}

void MediaMetadataMessage::set_video(const VideoMetadataMessage* value_arg) {
  video_ = value_arg ? std::make_unique<VideoMetadataMessage>(*value_arg) : nullptr;
}

void MediaMetadataMessage::set_video(const VideoMetadataMessage& value_arg) {
  video_ = std::make_unique<VideoMetadataMessage>(value_arg);
}


const AudioMetadataMessage* MediaMetadataMessage::audio() const {
  return audio_.get();
}

void MediaMetadataMessage::set_audio(const AudioMetadataMessage* value_arg) {
  audio_ = value_arg ? std::make_unique<AudioMetadataMessage>(*value_arg) : nullptr;
}

void MediaMetadataMessage::set_audio(const AudioMetadataMessage& value_arg) {
  audio_ = std::make_unique<AudioMetadataMessage>(value_arg);
}


EncodableList MediaMetadataMessage::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(CustomEncodableValue(kind_));
  list.push_back(image_ ? CustomEncodableValue(*image_) : EncodableValue());
  list.push_back(video_ ? CustomEncodableValue(*video_) : EncodableValue());
  list.push_back(audio_ ? CustomEncodableValue(*audio_) : EncodableValue());
  return list;
}

MediaMetadataMessage MediaMetadataMessage::FromEncodableList(const EncodableList& list) {
  MediaMetadataMessage decoded(
    std::any_cast<const MediaKindMessage&>(std::get<CustomEncodableValue>(list[0])));
  auto& encodable_image = list[1];
  if (!encodable_image.IsNull()) {
    decoded.set_image(std::any_cast<const ImageMetadataMessage&>(std::get<CustomEncodableValue>(encodable_image)));
  }
  auto& encodable_video = list[2];
  if (!encodable_video.IsNull()) {
    decoded.set_video(std::any_cast<const VideoMetadataMessage&>(std::get<CustomEncodableValue>(encodable_video)));
  }
  auto& encodable_audio = list[3];
  if (!encodable_audio.IsNull()) {
    decoded.set_audio(std::any_cast<const AudioMetadataMessage&>(std::get<CustomEncodableValue>(encodable_audio)));
  }
  return decoded;
}

bool MediaMetadataMessage::operator==(const MediaMetadataMessage& other) const {
  return PigeonInternalDeepEquals(kind_, other.kind_) && PigeonInternalDeepEquals(image_, other.image_) && PigeonInternalDeepEquals(video_, other.video_) && PigeonInternalDeepEquals(audio_, other.audio_);
}

bool MediaMetadataMessage::operator!=(const MediaMetadataMessage& other) const {
  return !(*this == other);
}

size_t MediaMetadataMessage::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(kind_);
  result = result * 31 + PigeonInternalDeepHash(image_);
  result = result * 31 + PigeonInternalDeepHash(video_);
  result = result * 31 + PigeonInternalDeepHash(audio_);
  return result;
}

std::ostream& operator<<(
  std::ostream& os,
  const MediaMetadataMessage& obj) {
  os << "MediaMetadataMessage(";
  os << "kind: ";
  os << PigeonInternalToString(obj.kind_);
  os << ", image: ";
  if (obj.image_) {
    os << *obj.image_;
  }
  else {
    os << "null";
  }
  os << ", video: ";
  if (obj.video_) {
    os << *obj.video_;
  }
  else {
    os << "null";
  }
  os << ", audio: ";
  if (obj.audio_) {
    os << *obj.audio_;
  }
  else {
    os << "null";
  }
  os << ")";
  return os;
}

size_t PigeonInternalDeepHash(const MediaMetadataMessage& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<SourceKindMessage>(enum_arg_value));
      }
    case 130: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<MediaKindMessage>(enum_arg_value));
      }
    case 131: {
        return CustomEncodableValue(MediaSourceMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(PixelSizeMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(GpsLocationMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(MetadataTagMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(PngTextChunkMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(ImageMetadataMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 137: {
        return CustomEncodableValue(VideoMetadataMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 138: {
        return CustomEncodableValue(AudioMetadataMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 139: {
        return CustomEncodableValue(MediaMetadataMessage::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(SourceKindMessage)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<SourceKindMessage>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(MediaKindMessage)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<MediaKindMessage>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(MediaSourceMessage)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<MediaSourceMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PixelSizeMessage)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<PixelSizeMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(GpsLocationMessage)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<GpsLocationMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(MetadataTagMessage)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<MetadataTagMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PngTextChunkMessage)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<PngTextChunkMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ImageMetadataMessage)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<ImageMetadataMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(VideoMetadataMessage)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<VideoMetadataMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(AudioMetadataMessage)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(std::any_cast<AudioMetadataMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(MediaMetadataMessage)) {
      stream->WriteByte(139);
      WriteValue(EncodableValue(std::any_cast<MediaMetadataMessage>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by MediaInfoHostApi.
const ::flutter::StandardMessageCodec& MediaInfoHostApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `MediaInfoHostApi` to handle messages through the `binary_messenger`.
void MediaInfoHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  MediaInfoHostApi* api) {
  MediaInfoHostApi::SetUp(binary_messenger, api, "");
}

void MediaInfoHostApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  MediaInfoHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.read" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_source_arg = args.at(0);
          if (encodable_source_arg.IsNull()) {
            reply(WrapError("source_arg unexpectedly null."));
            return;
          }
          const auto& source_arg = std::any_cast<const MediaSourceMessage&>(std::get<CustomEncodableValue>(encodable_source_arg));
          api->Read(source_arg, [reply](ErrorOr<MediaMetadataMessage>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readImage" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_source_arg = args.at(0);
          if (encodable_source_arg.IsNull()) {
            reply(WrapError("source_arg unexpectedly null."));
            return;
          }
          const auto& source_arg = std::any_cast<const MediaSourceMessage&>(std::get<CustomEncodableValue>(encodable_source_arg));
          api->ReadImage(source_arg, [reply](ErrorOr<ImageMetadataMessage>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readAv" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_source_arg = args.at(0);
          if (encodable_source_arg.IsNull()) {
            reply(WrapError("source_arg unexpectedly null."));
            return;
          }
          const auto& source_arg = std::any_cast<const MediaSourceMessage&>(std::get<CustomEncodableValue>(encodable_source_arg));
          api->ReadAv(source_arg, [reply](ErrorOr<MediaMetadataMessage>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.probe" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_source_arg = args.at(0);
          if (encodable_source_arg.IsNull()) {
            reply(WrapError("source_arg unexpectedly null."));
            return;
          }
          const auto& source_arg = std::any_cast<const MediaSourceMessage&>(std::get<CustomEncodableValue>(encodable_source_arg));
          api->Probe(source_arg, [reply](ErrorOr<MediaKindMessage>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readMotionPhoto" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_source_arg = args.at(0);
          if (encodable_source_arg.IsNull()) {
            reply(WrapError("source_arg unexpectedly null."));
            return;
          }
          const auto& source_arg = std::any_cast<const MediaSourceMessage&>(std::get<CustomEncodableValue>(encodable_source_arg));
          api->ReadMotionPhoto(source_arg, [reply](ErrorOr<VideoMetadataMessage>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue MediaInfoHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue MediaInfoHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace xue_hua_media_info_windows
