// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <ostream>
#include <string>

namespace xue_hua_media_info_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class MediaInfoHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Kind of a [MediaSourceMessage]. / [MediaSourceMessage] 的种类。
enum class SourceKindMessage {
  // Local filesystem path. / 本地文件路径。
  kFile = 0,
  // In-memory bytes. / 内存字节。
  kBytes = 1,
  // Flutter asset key (already resolved). / 已解析的 Flutter Asset 键。
  kAsset = 2
};

// Detected media kind. / 检测到的媒体种类。
enum class MediaKindMessage {
  // Still image. / 静态图片。
  kImage = 0,
  // Container with a video track. / 含视频轨的容器。
  kVideo = 1,
  // Audio-only container. / 纯音频容器。
  kAudio = 2
};


// Wire representation of a media source. / 媒体源的跨端传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class MediaSourceMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MediaSourceMessage(const SourceKindMessage& kind);

  // Constructs an object setting all fields.
  explicit MediaSourceMessage(
    const SourceKindMessage& kind,
    const std::string* uri,
    const std::vector<uint8_t>* bytes);

  // Discriminator. / 种类。
  const SourceKindMessage& kind() const;
  void set_kind(const SourceKindMessage& value_arg);

  // File path or resolved asset key. / 文件路径或已解析的 asset 键。
  const std::string* uri() const;
  void set_uri(const std::string_view* value_arg);
  void set_uri(std::string_view value_arg);

  // In-memory payload for [SourceKindMessage.bytes]. / 字节源载荷。
  const std::vector<uint8_t>* bytes() const;
  void set_bytes(const std::vector<uint8_t>* value_arg);
  void set_bytes(const std::vector<uint8_t>& value_arg);

  bool operator==(const MediaSourceMessage& other) const;
  bool operator!=(const MediaSourceMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const MediaSourceMessage& obj);
 private:
  static MediaSourceMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  SourceKindMessage kind_;
  std::optional<std::string> uri_;
  std::optional<std::vector<uint8_t>> bytes_;
};


// Wire pixel size. / 像素尺寸传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class PixelSizeMessage {
 public:
  // Constructs an object setting all fields.
  explicit PixelSizeMessage(
    int64_t width,
    int64_t height);

  int64_t width() const;
  void set_width(int64_t value_arg);

  int64_t height() const;
  void set_height(int64_t value_arg);

  bool operator==(const PixelSizeMessage& other) const;
  bool operator!=(const PixelSizeMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PixelSizeMessage& obj);
 private:
  static PixelSizeMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class ImageMetadataMessage;
  friend class VideoMetadataMessage;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t width_;
  int64_t height_;
};


// Wire GPS. / GPS 传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class GpsLocationMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit GpsLocationMessage(
    double latitude,
    double longitude);

  // Constructs an object setting all fields.
  explicit GpsLocationMessage(
    double latitude,
    double longitude,
    const double* altitude_meters);

  double latitude() const;
  void set_latitude(double value_arg);

  double longitude() const;
  void set_longitude(double value_arg);

  const double* altitude_meters() const;
  void set_altitude_meters(const double* value_arg);
  void set_altitude_meters(double value_arg);

  bool operator==(const GpsLocationMessage& other) const;
  bool operator!=(const GpsLocationMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const GpsLocationMessage& obj);
 private:
  static GpsLocationMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class ImageMetadataMessage;
  friend class VideoMetadataMessage;
  friend class AudioMetadataMessage;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  double latitude_;
  double longitude_;
  std::optional<double> altitude_meters_;
};


// Wire leftover tag. / 残留标签传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class MetadataTagMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MetadataTagMessage(
    const std::string& name,
    const std::string& display_value);

  // Constructs an object setting all fields.
  explicit MetadataTagMessage(
    const std::string& name,
    const std::string& display_value,
    const std::string* string_value,
    const int64_t* int_value,
    const double* double_value);

  const std::string& name() const;
  void set_name(std::string_view value_arg);

  const std::string& display_value() const;
  void set_display_value(std::string_view value_arg);

  const std::string* string_value() const;
  void set_string_value(const std::string_view* value_arg);
  void set_string_value(std::string_view value_arg);

  const int64_t* int_value() const;
  void set_int_value(const int64_t* value_arg);
  void set_int_value(int64_t value_arg);

  const double* double_value() const;
  void set_double_value(const double* value_arg);
  void set_double_value(double value_arg);

  bool operator==(const MetadataTagMessage& other) const;
  bool operator!=(const MetadataTagMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const MetadataTagMessage& obj);
 private:
  static MetadataTagMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string name_;
  std::string display_value_;
  std::optional<std::string> string_value_;
  std::optional<int64_t> int_value_;
  std::optional<double> double_value_;
};


// Wire PNG text chunk. / PNG 文本块传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class PngTextChunkMessage {
 public:
  // Constructs an object setting all fields.
  explicit PngTextChunkMessage(
    const std::string& key,
    const std::string& value);

  const std::string& key() const;
  void set_key(std::string_view value_arg);

  const std::string& value() const;
  void set_value(std::string_view value_arg);

  bool operator==(const PngTextChunkMessage& other) const;
  bool operator!=(const PngTextChunkMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const PngTextChunkMessage& obj);
 private:
  static PngTextChunkMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string key_;
  std::string value_;
};


// Wire image metadata. Dates are ISO-8601 (no timezone) or empty.
// 图片元数据传输结构。日期为无时区 ISO-8601 或空。
//
// Generated class from Pigeon that represents data sent in messages.
class ImageMetadataMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ImageMetadataMessage(
    bool has_motion_photo,
    const ::flutter::EncodableList& png_text,
    const ::flutter::EncodableList& extra_tags);

  // Constructs an object setting all fields.
  explicit ImageMetadataMessage(
    const std::string* make,
    const std::string* model,
    const std::string* software,
    const PixelSizeMessage* size,
    const int64_t* orientation,
    const std::string* date_time_original,
    const std::string* date_time_digitized,
    const std::string* date_time_modified,
    const GpsLocationMessage* gps,
    bool has_motion_photo,
    const ::flutter::EncodableList& png_text,
    const ::flutter::EncodableList& extra_tags);

  ~ImageMetadataMessage() = default;
  ImageMetadataMessage(const ImageMetadataMessage& other);
  ImageMetadataMessage& operator=(const ImageMetadataMessage& other);
  ImageMetadataMessage(ImageMetadataMessage&& other) = default;
  ImageMetadataMessage& operator=(ImageMetadataMessage&& other) noexcept = default;
  const std::string* make() const;
  void set_make(const std::string_view* value_arg);
  void set_make(std::string_view value_arg);

  const std::string* model() const;
  void set_model(const std::string_view* value_arg);
  void set_model(std::string_view value_arg);

  const std::string* software() const;
  void set_software(const std::string_view* value_arg);
  void set_software(std::string_view value_arg);

  const PixelSizeMessage* size() const;
  void set_size(const PixelSizeMessage* value_arg);
  void set_size(const PixelSizeMessage& value_arg);

  const int64_t* orientation() const;
  void set_orientation(const int64_t* value_arg);
  void set_orientation(int64_t value_arg);

  const std::string* date_time_original() const;
  void set_date_time_original(const std::string_view* value_arg);
  void set_date_time_original(std::string_view value_arg);

  const std::string* date_time_digitized() const;
  void set_date_time_digitized(const std::string_view* value_arg);
  void set_date_time_digitized(std::string_view value_arg);

  const std::string* date_time_modified() const;
  void set_date_time_modified(const std::string_view* value_arg);
  void set_date_time_modified(std::string_view value_arg);

  const GpsLocationMessage* gps() const;
  void set_gps(const GpsLocationMessage* value_arg);
  void set_gps(const GpsLocationMessage& value_arg);

  bool has_motion_photo() const;
  void set_has_motion_photo(bool value_arg);

  const ::flutter::EncodableList& png_text() const;
  void set_png_text(const ::flutter::EncodableList& value_arg);

  const ::flutter::EncodableList& extra_tags() const;
  void set_extra_tags(const ::flutter::EncodableList& value_arg);

  bool operator==(const ImageMetadataMessage& other) const;
  bool operator!=(const ImageMetadataMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const ImageMetadataMessage& obj);
 private:
  static ImageMetadataMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaMetadataMessage;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> make_;
  std::optional<std::string> model_;
  std::optional<std::string> software_;
  std::unique_ptr<PixelSizeMessage> size_;
  std::optional<int64_t> orientation_;
  std::optional<std::string> date_time_original_;
  std::optional<std::string> date_time_digitized_;
  std::optional<std::string> date_time_modified_;
  std::unique_ptr<GpsLocationMessage> gps_;
  bool has_motion_photo_;
  ::flutter::EncodableList png_text_;
  ::flutter::EncodableList extra_tags_;
};


// Wire video metadata. / 视频元数据传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class VideoMetadataMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit VideoMetadataMessage(const ::flutter::EncodableList& extra_tags);

  // Constructs an object setting all fields.
  explicit VideoMetadataMessage(
    const int64_t* duration_ms,
    const PixelSizeMessage* size,
    const int64_t* bitrate,
    const int64_t* rotation_degrees,
    const std::string* make,
    const std::string* model,
    const GpsLocationMessage* gps,
    const ::flutter::EncodableList& extra_tags);

  ~VideoMetadataMessage() = default;
  VideoMetadataMessage(const VideoMetadataMessage& other);
  VideoMetadataMessage& operator=(const VideoMetadataMessage& other);
  VideoMetadataMessage(VideoMetadataMessage&& other) = default;
  VideoMetadataMessage& operator=(VideoMetadataMessage&& other) noexcept = default;
  const int64_t* duration_ms() const;
  void set_duration_ms(const int64_t* value_arg);
  void set_duration_ms(int64_t value_arg);

  const PixelSizeMessage* size() const;
  void set_size(const PixelSizeMessage* value_arg);
  void set_size(const PixelSizeMessage& value_arg);

  const int64_t* bitrate() const;
  void set_bitrate(const int64_t* value_arg);
  void set_bitrate(int64_t value_arg);

  const int64_t* rotation_degrees() const;
  void set_rotation_degrees(const int64_t* value_arg);
  void set_rotation_degrees(int64_t value_arg);

  const std::string* make() const;
  void set_make(const std::string_view* value_arg);
  void set_make(std::string_view value_arg);

  const std::string* model() const;
  void set_model(const std::string_view* value_arg);
  void set_model(std::string_view value_arg);

  const GpsLocationMessage* gps() const;
  void set_gps(const GpsLocationMessage* value_arg);
  void set_gps(const GpsLocationMessage& value_arg);

  const ::flutter::EncodableList& extra_tags() const;
  void set_extra_tags(const ::flutter::EncodableList& value_arg);

  bool operator==(const VideoMetadataMessage& other) const;
  bool operator!=(const VideoMetadataMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const VideoMetadataMessage& obj);
 private:
  static VideoMetadataMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaMetadataMessage;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> duration_ms_;
  std::unique_ptr<PixelSizeMessage> size_;
  std::optional<int64_t> bitrate_;
  std::optional<int64_t> rotation_degrees_;
  std::optional<std::string> make_;
  std::optional<std::string> model_;
  std::unique_ptr<GpsLocationMessage> gps_;
  ::flutter::EncodableList extra_tags_;
};


// Wire audio metadata. / 音频元数据传输结构。
//
// Generated class from Pigeon that represents data sent in messages.
class AudioMetadataMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit AudioMetadataMessage(const ::flutter::EncodableList& extra_tags);

  // Constructs an object setting all fields.
  explicit AudioMetadataMessage(
    const int64_t* duration_ms,
    const int64_t* bitrate,
    const int64_t* sample_rate,
    const int64_t* channel_count,
    const std::string* make,
    const std::string* model,
    const GpsLocationMessage* gps,
    const ::flutter::EncodableList& extra_tags);

  ~AudioMetadataMessage() = default;
  AudioMetadataMessage(const AudioMetadataMessage& other);
  AudioMetadataMessage& operator=(const AudioMetadataMessage& other);
  AudioMetadataMessage(AudioMetadataMessage&& other) = default;
  AudioMetadataMessage& operator=(AudioMetadataMessage&& other) noexcept = default;
  const int64_t* duration_ms() const;
  void set_duration_ms(const int64_t* value_arg);
  void set_duration_ms(int64_t value_arg);

  const int64_t* bitrate() const;
  void set_bitrate(const int64_t* value_arg);
  void set_bitrate(int64_t value_arg);

  const int64_t* sample_rate() const;
  void set_sample_rate(const int64_t* value_arg);
  void set_sample_rate(int64_t value_arg);

  const int64_t* channel_count() const;
  void set_channel_count(const int64_t* value_arg);
  void set_channel_count(int64_t value_arg);

  const std::string* make() const;
  void set_make(const std::string_view* value_arg);
  void set_make(std::string_view value_arg);

  const std::string* model() const;
  void set_model(const std::string_view* value_arg);
  void set_model(std::string_view value_arg);

  const GpsLocationMessage* gps() const;
  void set_gps(const GpsLocationMessage* value_arg);
  void set_gps(const GpsLocationMessage& value_arg);

  const ::flutter::EncodableList& extra_tags() const;
  void set_extra_tags(const ::flutter::EncodableList& value_arg);

  bool operator==(const AudioMetadataMessage& other) const;
  bool operator!=(const AudioMetadataMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const AudioMetadataMessage& obj);
 private:
  static AudioMetadataMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaMetadataMessage;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> duration_ms_;
  std::optional<int64_t> bitrate_;
  std::optional<int64_t> sample_rate_;
  std::optional<int64_t> channel_count_;
  std::optional<std::string> make_;
  std::optional<std::string> model_;
  std::unique_ptr<GpsLocationMessage> gps_;
  ::flutter::EncodableList extra_tags_;
};


// Tagged union of metadata results. / 带种类判别的元数据联合。
//
// Generated class from Pigeon that represents data sent in messages.
class MediaMetadataMessage {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit MediaMetadataMessage(const MediaKindMessage& kind);

  // Constructs an object setting all fields.
  explicit MediaMetadataMessage(
    const MediaKindMessage& kind,
    const ImageMetadataMessage* image,
    const VideoMetadataMessage* video,
    const AudioMetadataMessage* audio);

  ~MediaMetadataMessage() = default;
  MediaMetadataMessage(const MediaMetadataMessage& other);
  MediaMetadataMessage& operator=(const MediaMetadataMessage& other);
  MediaMetadataMessage(MediaMetadataMessage&& other) = default;
  MediaMetadataMessage& operator=(MediaMetadataMessage&& other) noexcept = default;
  const MediaKindMessage& kind() const;
  void set_kind(const MediaKindMessage& value_arg);

  const ImageMetadataMessage* image() const;
  void set_image(const ImageMetadataMessage* value_arg);
  void set_image(const ImageMetadataMessage& value_arg);

  const VideoMetadataMessage* video() const;
  void set_video(const VideoMetadataMessage* value_arg);
  void set_video(const VideoMetadataMessage& value_arg);

  const AudioMetadataMessage* audio() const;
  void set_audio(const AudioMetadataMessage* value_arg);
  void set_audio(const AudioMetadataMessage& value_arg);

  bool operator==(const MediaMetadataMessage& other) const;
  bool operator!=(const MediaMetadataMessage& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
  /// Stream output operator for formatted string representation.
  friend std::ostream& operator<<(std::ostream& os, const MediaMetadataMessage& obj);
 private:
  static MediaMetadataMessage FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class MediaInfoHostApi;
  friend class PigeonInternalCodecSerializer;
  MediaKindMessage kind_;
  std::unique_ptr<ImageMetadataMessage> image_;
  std::unique_ptr<VideoMetadataMessage> video_;
  std::unique_ptr<AudioMetadataMessage> audio_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Host API implemented natively for media metadata reads.
// 由原生端实现的媒体元数据读取接口。
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class MediaInfoHostApi {
 public:
  MediaInfoHostApi(const MediaInfoHostApi&) = delete;
  MediaInfoHostApi& operator=(const MediaInfoHostApi&) = delete;
  virtual ~MediaInfoHostApi() {}
  // Auto-detect and read in one I/O. / 一次 I/O 自动识别并读取。
  virtual void Read(
    const MediaSourceMessage& source,
    std::function<void(ErrorOr<MediaMetadataMessage> reply)> result) = 0;
  // Read still-image metadata. / 读取静态图片元数据。
  virtual void ReadImage(
    const MediaSourceMessage& source,
    std::function<void(ErrorOr<ImageMetadataMessage> reply)> result) = 0;
  // Read a video or audio-only container. / 读取视频或纯音频容器。
  virtual void ReadAv(
    const MediaSourceMessage& source,
    std::function<void(ErrorOr<MediaMetadataMessage> reply)> result) = 0;
  // Header-only kind detection. / 仅检查文件头。
  virtual void Probe(
    const MediaSourceMessage& source,
    std::function<void(ErrorOr<MediaKindMessage> reply)> result) = 0;
  // Extract Motion Photo embedded MP4 metadata. / 提取动态照片内嵌 MP4。
  virtual void ReadMotionPhoto(
    const MediaSourceMessage& source,
    std::function<void(ErrorOr<VideoMetadataMessage> reply)> result) = 0;

  // The codec used by MediaInfoHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `MediaInfoHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    MediaInfoHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    MediaInfoHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  MediaInfoHostApi() = default;
};
}  // namespace xue_hua_media_info_windows
#endif  // PIGEON_MESSAGES_G_H_
