// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Kind of a [MediaSourceMessage]. / [MediaSourceMessage] 的种类。
enum SourceKindMessage: Int, CaseIterable {
  /// Local filesystem path. / 本地文件路径。
  case file = 0
  /// In-memory bytes. / 内存字节。
  case bytes = 1
  /// Flutter asset key (already resolved). / 已解析的 Flutter Asset 键。
  case asset = 2
}

/// Detected media kind. / 检测到的媒体种类。
enum MediaKindMessage: Int, CaseIterable {
  /// Still image. / 静态图片。
  case image = 0
  /// Container with a video track. / 含视频轨的容器。
  case video = 1
  /// Audio-only container. / 纯音频容器。
  case audio = 2
}

/// Wire representation of a media source. / 媒体源的跨端传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaSourceMessage: Hashable, CustomStringConvertible {
  /// Discriminator. / 种类。
  var kind: SourceKindMessage
  /// File path or resolved asset key. / 文件路径或已解析的 asset 键。
  var uri: String? = nil
  /// In-memory payload for [SourceKindMessage.bytes]. / 字节源载荷。
  var bytes: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaSourceMessage? {
    let kind = pigeonVar_list[0] as! SourceKindMessage
    let uri: String? = nilOrValue(pigeonVar_list[1])
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])

    return MediaSourceMessage(
      kind: kind,
      uri: uri,
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      uri,
      bytes,
    ]
  }
  static func == (lhs: MediaSourceMessage, rhs: MediaSourceMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.uri, rhs.uri) && MessagesPigeonInternal.deepEquals(lhs.bytes, rhs.bytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaSourceMessage")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bytes, hasher: &hasher)
  }

  public var description: String {
    return "MediaSourceMessage(kind: \(String(describing: kind)), uri: \(String(describing: uri)), bytes: \(String(describing: bytes)))"
  }
}

/// Wire pixel size. / 像素尺寸传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct PixelSizeMessage: Hashable, CustomStringConvertible {
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PixelSizeMessage? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64

    return PixelSizeMessage(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
  static func == (lhs: PixelSizeMessage, rhs: PixelSizeMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PixelSizeMessage")
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "PixelSizeMessage(width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Wire GPS. / GPS 传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct GpsLocationMessage: Hashable, CustomStringConvertible {
  var latitude: Double
  var longitude: Double
  var altitudeMeters: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GpsLocationMessage? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double
    let altitudeMeters: Double? = nilOrValue(pigeonVar_list[2])

    return GpsLocationMessage(
      latitude: latitude,
      longitude: longitude,
      altitudeMeters: altitudeMeters
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
      altitudeMeters,
    ]
  }
  static func == (lhs: GpsLocationMessage, rhs: GpsLocationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && MessagesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude) && MessagesPigeonInternal.deepEquals(lhs.altitudeMeters, rhs.altitudeMeters)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GpsLocationMessage")
    MessagesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: altitudeMeters, hasher: &hasher)
  }

  public var description: String {
    return "GpsLocationMessage(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)), altitudeMeters: \(String(describing: altitudeMeters)))"
  }
}

/// Wire leftover tag. / 残留标签传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct MetadataTagMessage: Hashable, CustomStringConvertible {
  var name: String
  var displayValue: String
  var stringValue: String? = nil
  var intValue: Int64? = nil
  var doubleValue: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MetadataTagMessage? {
    let name = pigeonVar_list[0] as! String
    let displayValue = pigeonVar_list[1] as! String
    let stringValue: String? = nilOrValue(pigeonVar_list[2])
    let intValue: Int64? = nilOrValue(pigeonVar_list[3])
    let doubleValue: Double? = nilOrValue(pigeonVar_list[4])

    return MetadataTagMessage(
      name: name,
      displayValue: displayValue,
      stringValue: stringValue,
      intValue: intValue,
      doubleValue: doubleValue
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      displayValue,
      stringValue,
      intValue,
      doubleValue,
    ]
  }
  static func == (lhs: MetadataTagMessage, rhs: MetadataTagMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.displayValue, rhs.displayValue) && MessagesPigeonInternal.deepEquals(lhs.stringValue, rhs.stringValue) && MessagesPigeonInternal.deepEquals(lhs.intValue, rhs.intValue) && MessagesPigeonInternal.deepEquals(lhs.doubleValue, rhs.doubleValue)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MetadataTagMessage")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: displayValue, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stringValue, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: intValue, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: doubleValue, hasher: &hasher)
  }

  public var description: String {
    return "MetadataTagMessage(name: \(String(describing: name)), displayValue: \(String(describing: displayValue)), stringValue: \(String(describing: stringValue)), intValue: \(String(describing: intValue)), doubleValue: \(String(describing: doubleValue)))"
  }
}

/// Wire PNG text chunk. / PNG 文本块传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct PngTextChunkMessage: Hashable, CustomStringConvertible {
  var key: String
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PngTextChunkMessage? {
    let key = pigeonVar_list[0] as! String
    let value = pigeonVar_list[1] as! String

    return PngTextChunkMessage(
      key: key,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      key,
      value,
    ]
  }
  static func == (lhs: PngTextChunkMessage, rhs: PngTextChunkMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.key, rhs.key) && MessagesPigeonInternal.deepEquals(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PngTextChunkMessage")
    MessagesPigeonInternal.deepHash(value: key, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: value, hasher: &hasher)
  }

  public var description: String {
    return "PngTextChunkMessage(key: \(String(describing: key)), value: \(String(describing: value)))"
  }
}

/// Wire image metadata. Dates are ISO-8601 (no timezone) or empty.
/// 图片元数据传输结构。日期为无时区 ISO-8601 或空。
///
/// Generated class from Pigeon that represents data sent in messages.
struct ImageMetadataMessage: Hashable, CustomStringConvertible {
  var make: String? = nil
  var model: String? = nil
  var software: String? = nil
  var size: PixelSizeMessage? = nil
  var orientation: Int64? = nil
  var dateTimeOriginal: String? = nil
  var dateTimeDigitized: String? = nil
  var dateTimeModified: String? = nil
  var gps: GpsLocationMessage? = nil
  var hasMotionPhoto: Bool
  var pngText: [PngTextChunkMessage]
  var extraTags: [MetadataTagMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageMetadataMessage? {
    let make: String? = nilOrValue(pigeonVar_list[0])
    let model: String? = nilOrValue(pigeonVar_list[1])
    let software: String? = nilOrValue(pigeonVar_list[2])
    let size: PixelSizeMessage? = nilOrValue(pigeonVar_list[3])
    let orientation: Int64? = nilOrValue(pigeonVar_list[4])
    let dateTimeOriginal: String? = nilOrValue(pigeonVar_list[5])
    let dateTimeDigitized: String? = nilOrValue(pigeonVar_list[6])
    let dateTimeModified: String? = nilOrValue(pigeonVar_list[7])
    let gps: GpsLocationMessage? = nilOrValue(pigeonVar_list[8])
    let hasMotionPhoto = pigeonVar_list[9] as! Bool
    let pngText = pigeonVar_list[10] as! [PngTextChunkMessage]
    let extraTags = pigeonVar_list[11] as! [MetadataTagMessage]

    return ImageMetadataMessage(
      make: make,
      model: model,
      software: software,
      size: size,
      orientation: orientation,
      dateTimeOriginal: dateTimeOriginal,
      dateTimeDigitized: dateTimeDigitized,
      dateTimeModified: dateTimeModified,
      gps: gps,
      hasMotionPhoto: hasMotionPhoto,
      pngText: pngText,
      extraTags: extraTags
    )
  }
  func toList() -> [Any?] {
    return [
      make,
      model,
      software,
      size,
      orientation,
      dateTimeOriginal,
      dateTimeDigitized,
      dateTimeModified,
      gps,
      hasMotionPhoto,
      pngText,
      extraTags,
    ]
  }
  static func == (lhs: ImageMetadataMessage, rhs: ImageMetadataMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.make, rhs.make) && MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.software, rhs.software) && MessagesPigeonInternal.deepEquals(lhs.size, rhs.size) && MessagesPigeonInternal.deepEquals(lhs.orientation, rhs.orientation) && MessagesPigeonInternal.deepEquals(lhs.dateTimeOriginal, rhs.dateTimeOriginal) && MessagesPigeonInternal.deepEquals(lhs.dateTimeDigitized, rhs.dateTimeDigitized) && MessagesPigeonInternal.deepEquals(lhs.dateTimeModified, rhs.dateTimeModified) && MessagesPigeonInternal.deepEquals(lhs.gps, rhs.gps) && MessagesPigeonInternal.deepEquals(lhs.hasMotionPhoto, rhs.hasMotionPhoto) && MessagesPigeonInternal.deepEquals(lhs.pngText, rhs.pngText) && MessagesPigeonInternal.deepEquals(lhs.extraTags, rhs.extraTags)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageMetadataMessage")
    MessagesPigeonInternal.deepHash(value: make, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: software, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: size, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: orientation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: dateTimeOriginal, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: dateTimeDigitized, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: dateTimeModified, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: gps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasMotionPhoto, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pngText, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: extraTags, hasher: &hasher)
  }

  public var description: String {
    return "ImageMetadataMessage(make: \(String(describing: make)), model: \(String(describing: model)), software: \(String(describing: software)), size: \(String(describing: size)), orientation: \(String(describing: orientation)), dateTimeOriginal: \(String(describing: dateTimeOriginal)), dateTimeDigitized: \(String(describing: dateTimeDigitized)), dateTimeModified: \(String(describing: dateTimeModified)), gps: \(String(describing: gps)), hasMotionPhoto: \(String(describing: hasMotionPhoto)), pngText: \(String(describing: pngText)), extraTags: \(String(describing: extraTags)))"
  }
}

/// Wire video metadata. / 视频元数据传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct VideoMetadataMessage: Hashable, CustomStringConvertible {
  var durationMs: Int64? = nil
  var size: PixelSizeMessage? = nil
  var bitrate: Int64? = nil
  var rotationDegrees: Int64? = nil
  var make: String? = nil
  var model: String? = nil
  var gps: GpsLocationMessage? = nil
  var extraTags: [MetadataTagMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoMetadataMessage? {
    let durationMs: Int64? = nilOrValue(pigeonVar_list[0])
    let size: PixelSizeMessage? = nilOrValue(pigeonVar_list[1])
    let bitrate: Int64? = nilOrValue(pigeonVar_list[2])
    let rotationDegrees: Int64? = nilOrValue(pigeonVar_list[3])
    let make: String? = nilOrValue(pigeonVar_list[4])
    let model: String? = nilOrValue(pigeonVar_list[5])
    let gps: GpsLocationMessage? = nilOrValue(pigeonVar_list[6])
    let extraTags = pigeonVar_list[7] as! [MetadataTagMessage]

    return VideoMetadataMessage(
      durationMs: durationMs,
      size: size,
      bitrate: bitrate,
      rotationDegrees: rotationDegrees,
      make: make,
      model: model,
      gps: gps,
      extraTags: extraTags
    )
  }
  func toList() -> [Any?] {
    return [
      durationMs,
      size,
      bitrate,
      rotationDegrees,
      make,
      model,
      gps,
      extraTags,
    ]
  }
  static func == (lhs: VideoMetadataMessage, rhs: VideoMetadataMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.size, rhs.size) && MessagesPigeonInternal.deepEquals(lhs.bitrate, rhs.bitrate) && MessagesPigeonInternal.deepEquals(lhs.rotationDegrees, rhs.rotationDegrees) && MessagesPigeonInternal.deepEquals(lhs.make, rhs.make) && MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.gps, rhs.gps) && MessagesPigeonInternal.deepEquals(lhs.extraTags, rhs.extraTags)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoMetadataMessage")
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: size, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitrate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotationDegrees, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: make, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: gps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: extraTags, hasher: &hasher)
  }

  public var description: String {
    return "VideoMetadataMessage(durationMs: \(String(describing: durationMs)), size: \(String(describing: size)), bitrate: \(String(describing: bitrate)), rotationDegrees: \(String(describing: rotationDegrees)), make: \(String(describing: make)), model: \(String(describing: model)), gps: \(String(describing: gps)), extraTags: \(String(describing: extraTags)))"
  }
}

/// Wire audio metadata. / 音频元数据传输结构。
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioMetadataMessage: Hashable, CustomStringConvertible {
  var durationMs: Int64? = nil
  var bitrate: Int64? = nil
  var sampleRate: Int64? = nil
  var channelCount: Int64? = nil
  var make: String? = nil
  var model: String? = nil
  var gps: GpsLocationMessage? = nil
  var extraTags: [MetadataTagMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioMetadataMessage? {
    let durationMs: Int64? = nilOrValue(pigeonVar_list[0])
    let bitrate: Int64? = nilOrValue(pigeonVar_list[1])
    let sampleRate: Int64? = nilOrValue(pigeonVar_list[2])
    let channelCount: Int64? = nilOrValue(pigeonVar_list[3])
    let make: String? = nilOrValue(pigeonVar_list[4])
    let model: String? = nilOrValue(pigeonVar_list[5])
    let gps: GpsLocationMessage? = nilOrValue(pigeonVar_list[6])
    let extraTags = pigeonVar_list[7] as! [MetadataTagMessage]

    return AudioMetadataMessage(
      durationMs: durationMs,
      bitrate: bitrate,
      sampleRate: sampleRate,
      channelCount: channelCount,
      make: make,
      model: model,
      gps: gps,
      extraTags: extraTags
    )
  }
  func toList() -> [Any?] {
    return [
      durationMs,
      bitrate,
      sampleRate,
      channelCount,
      make,
      model,
      gps,
      extraTags,
    ]
  }
  static func == (lhs: AudioMetadataMessage, rhs: AudioMetadataMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.bitrate, rhs.bitrate) && MessagesPigeonInternal.deepEquals(lhs.sampleRate, rhs.sampleRate) && MessagesPigeonInternal.deepEquals(lhs.channelCount, rhs.channelCount) && MessagesPigeonInternal.deepEquals(lhs.make, rhs.make) && MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.gps, rhs.gps) && MessagesPigeonInternal.deepEquals(lhs.extraTags, rhs.extraTags)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AudioMetadataMessage")
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bitrate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sampleRate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: channelCount, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: make, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: gps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: extraTags, hasher: &hasher)
  }

  public var description: String {
    return "AudioMetadataMessage(durationMs: \(String(describing: durationMs)), bitrate: \(String(describing: bitrate)), sampleRate: \(String(describing: sampleRate)), channelCount: \(String(describing: channelCount)), make: \(String(describing: make)), model: \(String(describing: model)), gps: \(String(describing: gps)), extraTags: \(String(describing: extraTags)))"
  }
}

/// Tagged union of metadata results. / 带种类判别的元数据联合。
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaMetadataMessage: Hashable, CustomStringConvertible {
  var kind: MediaKindMessage
  var image: ImageMetadataMessage? = nil
  var video: VideoMetadataMessage? = nil
  var audio: AudioMetadataMessage? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaMetadataMessage? {
    let kind = pigeonVar_list[0] as! MediaKindMessage
    let image: ImageMetadataMessage? = nilOrValue(pigeonVar_list[1])
    let video: VideoMetadataMessage? = nilOrValue(pigeonVar_list[2])
    let audio: AudioMetadataMessage? = nilOrValue(pigeonVar_list[3])

    return MediaMetadataMessage(
      kind: kind,
      image: image,
      video: video,
      audio: audio
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      image,
      video,
      audio,
    ]
  }
  static func == (lhs: MediaMetadataMessage, rhs: MediaMetadataMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.image, rhs.image) && MessagesPigeonInternal.deepEquals(lhs.video, rhs.video) && MessagesPigeonInternal.deepEquals(lhs.audio, rhs.audio)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaMetadataMessage")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: image, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: video, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audio, hasher: &hasher)
  }

  public var description: String {
    return "MediaMetadataMessage(kind: \(String(describing: kind)), image: \(String(describing: image)), video: \(String(describing: video)), audio: \(String(describing: audio)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SourceKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MediaKindMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return MediaSourceMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return PixelSizeMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return GpsLocationMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return MetadataTagMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return PngTextChunkMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return ImageMetadataMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return VideoMetadataMessage.fromList(self.readValue() as! [Any?])
    case 138:
      return AudioMetadataMessage.fromList(self.readValue() as! [Any?])
    case 139:
      return MediaMetadataMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SourceKindMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? MediaKindMessage {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MediaSourceMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PixelSizeMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? GpsLocationMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? MetadataTagMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PngTextChunkMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ImageMetadataMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? VideoMetadataMessage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? AudioMetadataMessage {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? MediaMetadataMessage {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host API implemented natively for media metadata reads.
/// 由原生端实现的媒体元数据读取接口。
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MediaInfoHostApi {
  /// Auto-detect and read in one I/O. / 一次 I/O 自动识别并读取。
  func read(source: MediaSourceMessage, completion: @escaping (Result<MediaMetadataMessage, Error>) -> Void)
  /// Read still-image metadata. / 读取静态图片元数据。
  func readImage(source: MediaSourceMessage, completion: @escaping (Result<ImageMetadataMessage, Error>) -> Void)
  /// Read a video or audio-only container. / 读取视频或纯音频容器。
  func readAv(source: MediaSourceMessage, completion: @escaping (Result<MediaMetadataMessage, Error>) -> Void)
  /// Header-only kind detection. / 仅检查文件头。
  func probe(source: MediaSourceMessage, completion: @escaping (Result<MediaKindMessage, Error>) -> Void)
  /// Extract Motion Photo embedded MP4 metadata. / 提取动态照片内嵌 MP4。
  func readMotionPhoto(source: MediaSourceMessage, completion: @escaping (Result<VideoMetadataMessage, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MediaInfoHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MediaInfoHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MediaInfoHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Auto-detect and read in one I/O. / 一次 I/O 自动识别并读取。
    let readChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.read\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! MediaSourceMessage
        api.read(source: sourceArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readChannel.setMessageHandler(nil)
    }
    /// Read still-image metadata. / 读取静态图片元数据。
    let readImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! MediaSourceMessage
        api.readImage(source: sourceArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readImageChannel.setMessageHandler(nil)
    }
    /// Read a video or audio-only container. / 读取视频或纯音频容器。
    let readAvChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readAv\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readAvChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! MediaSourceMessage
        api.readAv(source: sourceArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readAvChannel.setMessageHandler(nil)
    }
    /// Header-only kind detection. / 仅检查文件头。
    let probeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.probe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! MediaSourceMessage
        api.probe(source: sourceArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeChannel.setMessageHandler(nil)
    }
    /// Extract Motion Photo embedded MP4 metadata. / 提取动态照片内嵌 MP4。
    let readMotionPhotoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readMotionPhoto\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readMotionPhotoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! MediaSourceMessage
        api.readMotionPhoto(source: sourceArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readMotionPhotoChannel.setMessageHandler(nil)
    }
  }
}
