// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * XhmiMessagesSourceKindMessage:
 * XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_SOURCE_KIND_MESSAGE_FILE:
 * Local filesystem path. / 本地文件路径。
 * XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_SOURCE_KIND_MESSAGE_BYTES:
 * In-memory bytes. / 内存字节。
 * XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_SOURCE_KIND_MESSAGE_ASSET:
 * Flutter asset key (already resolved). / 已解析的 Flutter Asset 键。
 *
 * Kind of a [MediaSourceMessage]. / [MediaSourceMessage] 的种类。
 */
typedef enum {
  XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_SOURCE_KIND_MESSAGE_FILE = 0,
  XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_SOURCE_KIND_MESSAGE_BYTES = 1,
  XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_SOURCE_KIND_MESSAGE_ASSET = 2
} XhmiMessagesSourceKindMessage;

/**
 * XhmiMessagesMediaKindMessage:
 * XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_MEDIA_KIND_MESSAGE_IMAGE:
 * Still image. / 静态图片。
 * XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_MEDIA_KIND_MESSAGE_VIDEO:
 * Container with a video track. / 含视频轨的容器。
 * XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_MEDIA_KIND_MESSAGE_AUDIO:
 * Audio-only container. / 纯音频容器。
 *
 * Detected media kind. / 检测到的媒体种类。
 */
typedef enum {
  XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_MEDIA_KIND_MESSAGE_IMAGE = 0,
  XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_MEDIA_KIND_MESSAGE_VIDEO = 1,
  XUE_HUA_MEDIA_INFO_PLATFORM_INTERFACE_MEDIA_KIND_MESSAGE_AUDIO = 2
} XhmiMessagesMediaKindMessage;

/**
 * XhmiMessagesMediaSourceMessage:
 *
 * Wire representation of a media source. / 媒体源的跨端传输结构。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesMediaSourceMessage, xhmi_messages_media_source_message, XHMI_MESSAGES, MEDIA_SOURCE_MESSAGE, GObject)

/**
 * xhmi_messages_media_source_message_new:
 * kind: field in this object.
 * uri: field in this object.
 * bytes: field in this object.
 * bytes_length: length of @bytes.
 *
 * Creates a new #MediaSourceMessage object.
 *
 * Returns: a new #XhmiMessagesMediaSourceMessage
 */
XhmiMessagesMediaSourceMessage* xhmi_messages_media_source_message_new(XhmiMessagesSourceKindMessage kind, const gchar* uri, const uint8_t* bytes, size_t bytes_length);

/**
 * xhmi_messages_media_source_message_get_kind
 * @object: a #XhmiMessagesMediaSourceMessage.
 *
 * Discriminator. / 种类。
 *
 * Returns: the field value.
 */
XhmiMessagesSourceKindMessage xhmi_messages_media_source_message_get_kind(XhmiMessagesMediaSourceMessage* object);

/**
 * xhmi_messages_media_source_message_get_uri
 * @object: a #XhmiMessagesMediaSourceMessage.
 *
 * File path or resolved asset key. / 文件路径或已解析的 asset 键。
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_media_source_message_get_uri(XhmiMessagesMediaSourceMessage* object);

/**
 * xhmi_messages_media_source_message_get_bytes
 * @object: a #XhmiMessagesMediaSourceMessage.
 * @length: location to write the length of this value.
 *
 * In-memory payload for [SourceKindMessage.bytes]. / 字节源载荷。
 *
 * Returns: the field value.
 */
const uint8_t* xhmi_messages_media_source_message_get_bytes(XhmiMessagesMediaSourceMessage* object, size_t* length);

/**
 * xhmi_messages_media_source_message_equals:
 * @a: a #XhmiMessagesMediaSourceMessage.
 * @b: another #XhmiMessagesMediaSourceMessage.
 *
 * Checks if two #XhmiMessagesMediaSourceMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_media_source_message_equals(XhmiMessagesMediaSourceMessage* a, XhmiMessagesMediaSourceMessage* b);

/**
 * xhmi_messages_media_source_message_hash:
 * @object: a #XhmiMessagesMediaSourceMessage.
 *
 * Calculates a hash code for a #XhmiMessagesMediaSourceMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_media_source_message_hash(XhmiMessagesMediaSourceMessage* object);

/**
 * xhmi_messages_media_source_message_to_string:
 * @object: a #XhmiMessagesMediaSourceMessage.
 *
 * Returns a string representation of a #XhmiMessagesMediaSourceMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_media_source_message_to_string(XhmiMessagesMediaSourceMessage* object);

/**
 * XhmiMessagesPixelSizeMessage:
 *
 * Wire pixel size. / 像素尺寸传输结构。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesPixelSizeMessage, xhmi_messages_pixel_size_message, XHMI_MESSAGES, PIXEL_SIZE_MESSAGE, GObject)

/**
 * xhmi_messages_pixel_size_message_new:
 * width: field in this object.
 * height: field in this object.
 *
 * Creates a new #PixelSizeMessage object.
 *
 * Returns: a new #XhmiMessagesPixelSizeMessage
 */
XhmiMessagesPixelSizeMessage* xhmi_messages_pixel_size_message_new(int64_t width, int64_t height);

/**
 * xhmi_messages_pixel_size_message_get_width
 * @object: a #XhmiMessagesPixelSizeMessage.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
int64_t xhmi_messages_pixel_size_message_get_width(XhmiMessagesPixelSizeMessage* object);

/**
 * xhmi_messages_pixel_size_message_get_height
 * @object: a #XhmiMessagesPixelSizeMessage.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
int64_t xhmi_messages_pixel_size_message_get_height(XhmiMessagesPixelSizeMessage* object);

/**
 * xhmi_messages_pixel_size_message_equals:
 * @a: a #XhmiMessagesPixelSizeMessage.
 * @b: another #XhmiMessagesPixelSizeMessage.
 *
 * Checks if two #XhmiMessagesPixelSizeMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_pixel_size_message_equals(XhmiMessagesPixelSizeMessage* a, XhmiMessagesPixelSizeMessage* b);

/**
 * xhmi_messages_pixel_size_message_hash:
 * @object: a #XhmiMessagesPixelSizeMessage.
 *
 * Calculates a hash code for a #XhmiMessagesPixelSizeMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_pixel_size_message_hash(XhmiMessagesPixelSizeMessage* object);

/**
 * xhmi_messages_pixel_size_message_to_string:
 * @object: a #XhmiMessagesPixelSizeMessage.
 *
 * Returns a string representation of a #XhmiMessagesPixelSizeMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_pixel_size_message_to_string(XhmiMessagesPixelSizeMessage* object);

/**
 * XhmiMessagesGpsLocationMessage:
 *
 * Wire GPS. / GPS 传输结构。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesGpsLocationMessage, xhmi_messages_gps_location_message, XHMI_MESSAGES, GPS_LOCATION_MESSAGE, GObject)

/**
 * xhmi_messages_gps_location_message_new:
 * latitude: field in this object.
 * longitude: field in this object.
 * altitude_meters: field in this object.
 *
 * Creates a new #GpsLocationMessage object.
 *
 * Returns: a new #XhmiMessagesGpsLocationMessage
 */
XhmiMessagesGpsLocationMessage* xhmi_messages_gps_location_message_new(double latitude, double longitude, double* altitude_meters);

/**
 * xhmi_messages_gps_location_message_get_latitude
 * @object: a #XhmiMessagesGpsLocationMessage.
 *
 * Gets the value of the latitude field of @object.
 *
 * Returns: the field value.
 */
double xhmi_messages_gps_location_message_get_latitude(XhmiMessagesGpsLocationMessage* object);

/**
 * xhmi_messages_gps_location_message_get_longitude
 * @object: a #XhmiMessagesGpsLocationMessage.
 *
 * Gets the value of the longitude field of @object.
 *
 * Returns: the field value.
 */
double xhmi_messages_gps_location_message_get_longitude(XhmiMessagesGpsLocationMessage* object);

/**
 * xhmi_messages_gps_location_message_get_altitude_meters
 * @object: a #XhmiMessagesGpsLocationMessage.
 *
 * Gets the value of the altitudeMeters field of @object.
 *
 * Returns: the field value.
 */
double* xhmi_messages_gps_location_message_get_altitude_meters(XhmiMessagesGpsLocationMessage* object);

/**
 * xhmi_messages_gps_location_message_equals:
 * @a: a #XhmiMessagesGpsLocationMessage.
 * @b: another #XhmiMessagesGpsLocationMessage.
 *
 * Checks if two #XhmiMessagesGpsLocationMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_gps_location_message_equals(XhmiMessagesGpsLocationMessage* a, XhmiMessagesGpsLocationMessage* b);

/**
 * xhmi_messages_gps_location_message_hash:
 * @object: a #XhmiMessagesGpsLocationMessage.
 *
 * Calculates a hash code for a #XhmiMessagesGpsLocationMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_gps_location_message_hash(XhmiMessagesGpsLocationMessage* object);

/**
 * xhmi_messages_gps_location_message_to_string:
 * @object: a #XhmiMessagesGpsLocationMessage.
 *
 * Returns a string representation of a #XhmiMessagesGpsLocationMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_gps_location_message_to_string(XhmiMessagesGpsLocationMessage* object);

/**
 * XhmiMessagesMetadataTagMessage:
 *
 * Wire leftover tag. / 残留标签传输结构。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesMetadataTagMessage, xhmi_messages_metadata_tag_message, XHMI_MESSAGES, METADATA_TAG_MESSAGE, GObject)

/**
 * xhmi_messages_metadata_tag_message_new:
 * name: field in this object.
 * display_value: field in this object.
 * string_value: field in this object.
 * int_value: field in this object.
 * double_value: field in this object.
 *
 * Creates a new #MetadataTagMessage object.
 *
 * Returns: a new #XhmiMessagesMetadataTagMessage
 */
XhmiMessagesMetadataTagMessage* xhmi_messages_metadata_tag_message_new(const gchar* name, const gchar* display_value, const gchar* string_value, int64_t* int_value, double* double_value);

/**
 * xhmi_messages_metadata_tag_message_get_name
 * @object: a #XhmiMessagesMetadataTagMessage.
 *
 * Gets the value of the name field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_metadata_tag_message_get_name(XhmiMessagesMetadataTagMessage* object);

/**
 * xhmi_messages_metadata_tag_message_get_display_value
 * @object: a #XhmiMessagesMetadataTagMessage.
 *
 * Gets the value of the displayValue field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_metadata_tag_message_get_display_value(XhmiMessagesMetadataTagMessage* object);

/**
 * xhmi_messages_metadata_tag_message_get_string_value
 * @object: a #XhmiMessagesMetadataTagMessage.
 *
 * Gets the value of the stringValue field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_metadata_tag_message_get_string_value(XhmiMessagesMetadataTagMessage* object);

/**
 * xhmi_messages_metadata_tag_message_get_int_value
 * @object: a #XhmiMessagesMetadataTagMessage.
 *
 * Gets the value of the intValue field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_metadata_tag_message_get_int_value(XhmiMessagesMetadataTagMessage* object);

/**
 * xhmi_messages_metadata_tag_message_get_double_value
 * @object: a #XhmiMessagesMetadataTagMessage.
 *
 * Gets the value of the doubleValue field of @object.
 *
 * Returns: the field value.
 */
double* xhmi_messages_metadata_tag_message_get_double_value(XhmiMessagesMetadataTagMessage* object);

/**
 * xhmi_messages_metadata_tag_message_equals:
 * @a: a #XhmiMessagesMetadataTagMessage.
 * @b: another #XhmiMessagesMetadataTagMessage.
 *
 * Checks if two #XhmiMessagesMetadataTagMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_metadata_tag_message_equals(XhmiMessagesMetadataTagMessage* a, XhmiMessagesMetadataTagMessage* b);

/**
 * xhmi_messages_metadata_tag_message_hash:
 * @object: a #XhmiMessagesMetadataTagMessage.
 *
 * Calculates a hash code for a #XhmiMessagesMetadataTagMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_metadata_tag_message_hash(XhmiMessagesMetadataTagMessage* object);

/**
 * xhmi_messages_metadata_tag_message_to_string:
 * @object: a #XhmiMessagesMetadataTagMessage.
 *
 * Returns a string representation of a #XhmiMessagesMetadataTagMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_metadata_tag_message_to_string(XhmiMessagesMetadataTagMessage* object);

/**
 * XhmiMessagesPngTextChunkMessage:
 *
 * Wire PNG text chunk. / PNG 文本块传输结构。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesPngTextChunkMessage, xhmi_messages_png_text_chunk_message, XHMI_MESSAGES, PNG_TEXT_CHUNK_MESSAGE, GObject)

/**
 * xhmi_messages_png_text_chunk_message_new:
 * key: field in this object.
 * value: field in this object.
 *
 * Creates a new #PngTextChunkMessage object.
 *
 * Returns: a new #XhmiMessagesPngTextChunkMessage
 */
XhmiMessagesPngTextChunkMessage* xhmi_messages_png_text_chunk_message_new(const gchar* key, const gchar* value);

/**
 * xhmi_messages_png_text_chunk_message_get_key
 * @object: a #XhmiMessagesPngTextChunkMessage.
 *
 * Gets the value of the key field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_png_text_chunk_message_get_key(XhmiMessagesPngTextChunkMessage* object);

/**
 * xhmi_messages_png_text_chunk_message_get_value
 * @object: a #XhmiMessagesPngTextChunkMessage.
 *
 * Gets the value of the value field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_png_text_chunk_message_get_value(XhmiMessagesPngTextChunkMessage* object);

/**
 * xhmi_messages_png_text_chunk_message_equals:
 * @a: a #XhmiMessagesPngTextChunkMessage.
 * @b: another #XhmiMessagesPngTextChunkMessage.
 *
 * Checks if two #XhmiMessagesPngTextChunkMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_png_text_chunk_message_equals(XhmiMessagesPngTextChunkMessage* a, XhmiMessagesPngTextChunkMessage* b);

/**
 * xhmi_messages_png_text_chunk_message_hash:
 * @object: a #XhmiMessagesPngTextChunkMessage.
 *
 * Calculates a hash code for a #XhmiMessagesPngTextChunkMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_png_text_chunk_message_hash(XhmiMessagesPngTextChunkMessage* object);

/**
 * xhmi_messages_png_text_chunk_message_to_string:
 * @object: a #XhmiMessagesPngTextChunkMessage.
 *
 * Returns a string representation of a #XhmiMessagesPngTextChunkMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_png_text_chunk_message_to_string(XhmiMessagesPngTextChunkMessage* object);

/**
 * XhmiMessagesImageMetadataMessage:
 *
 * Wire image metadata. Dates are ISO-8601 (no timezone) or empty.
 * 图片元数据传输结构。日期为无时区 ISO-8601 或空。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesImageMetadataMessage, xhmi_messages_image_metadata_message, XHMI_MESSAGES, IMAGE_METADATA_MESSAGE, GObject)

/**
 * xhmi_messages_image_metadata_message_new:
 * make: field in this object.
 * model: field in this object.
 * software: field in this object.
 * size: field in this object.
 * orientation: field in this object.
 * date_time_original: field in this object.
 * date_time_digitized: field in this object.
 * date_time_modified: field in this object.
 * gps: field in this object.
 * has_motion_photo: field in this object.
 * png_text: field in this object.
 * extra_tags: field in this object.
 *
 * Creates a new #ImageMetadataMessage object.
 *
 * Returns: a new #XhmiMessagesImageMetadataMessage
 */
XhmiMessagesImageMetadataMessage* xhmi_messages_image_metadata_message_new(const gchar* make, const gchar* model, const gchar* software, XhmiMessagesPixelSizeMessage* size, int64_t* orientation, const gchar* date_time_original, const gchar* date_time_digitized, const gchar* date_time_modified, XhmiMessagesGpsLocationMessage* gps, gboolean has_motion_photo, FlValue* png_text, FlValue* extra_tags);

/**
 * xhmi_messages_image_metadata_message_get_make
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the make field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_image_metadata_message_get_make(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_model
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the model field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_image_metadata_message_get_model(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_software
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the software field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_image_metadata_message_get_software(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_size
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the size field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesPixelSizeMessage* xhmi_messages_image_metadata_message_get_size(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_orientation
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the orientation field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_image_metadata_message_get_orientation(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_date_time_original
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the dateTimeOriginal field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_image_metadata_message_get_date_time_original(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_date_time_digitized
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the dateTimeDigitized field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_image_metadata_message_get_date_time_digitized(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_date_time_modified
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the dateTimeModified field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_image_metadata_message_get_date_time_modified(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_gps
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the gps field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesGpsLocationMessage* xhmi_messages_image_metadata_message_get_gps(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_has_motion_photo
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the hasMotionPhoto field of @object.
 *
 * Returns: the field value.
 */
gboolean xhmi_messages_image_metadata_message_get_has_motion_photo(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_png_text
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the pngText field of @object.
 *
 * Returns: the field value.
 */
FlValue* xhmi_messages_image_metadata_message_get_png_text(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_get_extra_tags
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Gets the value of the extraTags field of @object.
 *
 * Returns: the field value.
 */
FlValue* xhmi_messages_image_metadata_message_get_extra_tags(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_equals:
 * @a: a #XhmiMessagesImageMetadataMessage.
 * @b: another #XhmiMessagesImageMetadataMessage.
 *
 * Checks if two #XhmiMessagesImageMetadataMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_image_metadata_message_equals(XhmiMessagesImageMetadataMessage* a, XhmiMessagesImageMetadataMessage* b);

/**
 * xhmi_messages_image_metadata_message_hash:
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Calculates a hash code for a #XhmiMessagesImageMetadataMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_image_metadata_message_hash(XhmiMessagesImageMetadataMessage* object);

/**
 * xhmi_messages_image_metadata_message_to_string:
 * @object: a #XhmiMessagesImageMetadataMessage.
 *
 * Returns a string representation of a #XhmiMessagesImageMetadataMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_image_metadata_message_to_string(XhmiMessagesImageMetadataMessage* object);

/**
 * XhmiMessagesVideoMetadataMessage:
 *
 * Wire video metadata. / 视频元数据传输结构。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesVideoMetadataMessage, xhmi_messages_video_metadata_message, XHMI_MESSAGES, VIDEO_METADATA_MESSAGE, GObject)

/**
 * xhmi_messages_video_metadata_message_new:
 * duration_ms: field in this object.
 * size: field in this object.
 * bitrate: field in this object.
 * rotation_degrees: field in this object.
 * make: field in this object.
 * model: field in this object.
 * gps: field in this object.
 * extra_tags: field in this object.
 *
 * Creates a new #VideoMetadataMessage object.
 *
 * Returns: a new #XhmiMessagesVideoMetadataMessage
 */
XhmiMessagesVideoMetadataMessage* xhmi_messages_video_metadata_message_new(int64_t* duration_ms, XhmiMessagesPixelSizeMessage* size, int64_t* bitrate, int64_t* rotation_degrees, const gchar* make, const gchar* model, XhmiMessagesGpsLocationMessage* gps, FlValue* extra_tags);

/**
 * xhmi_messages_video_metadata_message_get_duration_ms
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Gets the value of the durationMs field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_video_metadata_message_get_duration_ms(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_get_size
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Gets the value of the size field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesPixelSizeMessage* xhmi_messages_video_metadata_message_get_size(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_get_bitrate
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Gets the value of the bitrate field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_video_metadata_message_get_bitrate(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_get_rotation_degrees
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Gets the value of the rotationDegrees field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_video_metadata_message_get_rotation_degrees(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_get_make
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Gets the value of the make field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_video_metadata_message_get_make(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_get_model
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Gets the value of the model field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_video_metadata_message_get_model(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_get_gps
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Gets the value of the gps field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesGpsLocationMessage* xhmi_messages_video_metadata_message_get_gps(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_get_extra_tags
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Gets the value of the extraTags field of @object.
 *
 * Returns: the field value.
 */
FlValue* xhmi_messages_video_metadata_message_get_extra_tags(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_equals:
 * @a: a #XhmiMessagesVideoMetadataMessage.
 * @b: another #XhmiMessagesVideoMetadataMessage.
 *
 * Checks if two #XhmiMessagesVideoMetadataMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_video_metadata_message_equals(XhmiMessagesVideoMetadataMessage* a, XhmiMessagesVideoMetadataMessage* b);

/**
 * xhmi_messages_video_metadata_message_hash:
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Calculates a hash code for a #XhmiMessagesVideoMetadataMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_video_metadata_message_hash(XhmiMessagesVideoMetadataMessage* object);

/**
 * xhmi_messages_video_metadata_message_to_string:
 * @object: a #XhmiMessagesVideoMetadataMessage.
 *
 * Returns a string representation of a #XhmiMessagesVideoMetadataMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_video_metadata_message_to_string(XhmiMessagesVideoMetadataMessage* object);

/**
 * XhmiMessagesAudioMetadataMessage:
 *
 * Wire audio metadata. / 音频元数据传输结构。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesAudioMetadataMessage, xhmi_messages_audio_metadata_message, XHMI_MESSAGES, AUDIO_METADATA_MESSAGE, GObject)

/**
 * xhmi_messages_audio_metadata_message_new:
 * duration_ms: field in this object.
 * bitrate: field in this object.
 * sample_rate: field in this object.
 * channel_count: field in this object.
 * make: field in this object.
 * model: field in this object.
 * gps: field in this object.
 * extra_tags: field in this object.
 *
 * Creates a new #AudioMetadataMessage object.
 *
 * Returns: a new #XhmiMessagesAudioMetadataMessage
 */
XhmiMessagesAudioMetadataMessage* xhmi_messages_audio_metadata_message_new(int64_t* duration_ms, int64_t* bitrate, int64_t* sample_rate, int64_t* channel_count, const gchar* make, const gchar* model, XhmiMessagesGpsLocationMessage* gps, FlValue* extra_tags);

/**
 * xhmi_messages_audio_metadata_message_get_duration_ms
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Gets the value of the durationMs field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_audio_metadata_message_get_duration_ms(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_get_bitrate
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Gets the value of the bitrate field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_audio_metadata_message_get_bitrate(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_get_sample_rate
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Gets the value of the sampleRate field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_audio_metadata_message_get_sample_rate(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_get_channel_count
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Gets the value of the channelCount field of @object.
 *
 * Returns: the field value.
 */
int64_t* xhmi_messages_audio_metadata_message_get_channel_count(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_get_make
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Gets the value of the make field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_audio_metadata_message_get_make(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_get_model
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Gets the value of the model field of @object.
 *
 * Returns: the field value.
 */
const gchar* xhmi_messages_audio_metadata_message_get_model(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_get_gps
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Gets the value of the gps field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesGpsLocationMessage* xhmi_messages_audio_metadata_message_get_gps(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_get_extra_tags
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Gets the value of the extraTags field of @object.
 *
 * Returns: the field value.
 */
FlValue* xhmi_messages_audio_metadata_message_get_extra_tags(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_equals:
 * @a: a #XhmiMessagesAudioMetadataMessage.
 * @b: another #XhmiMessagesAudioMetadataMessage.
 *
 * Checks if two #XhmiMessagesAudioMetadataMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_audio_metadata_message_equals(XhmiMessagesAudioMetadataMessage* a, XhmiMessagesAudioMetadataMessage* b);

/**
 * xhmi_messages_audio_metadata_message_hash:
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Calculates a hash code for a #XhmiMessagesAudioMetadataMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_audio_metadata_message_hash(XhmiMessagesAudioMetadataMessage* object);

/**
 * xhmi_messages_audio_metadata_message_to_string:
 * @object: a #XhmiMessagesAudioMetadataMessage.
 *
 * Returns a string representation of a #XhmiMessagesAudioMetadataMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_audio_metadata_message_to_string(XhmiMessagesAudioMetadataMessage* object);

/**
 * XhmiMessagesMediaMetadataMessage:
 *
 * Tagged union of metadata results. / 带种类判别的元数据联合。
 */

G_DECLARE_FINAL_TYPE(XhmiMessagesMediaMetadataMessage, xhmi_messages_media_metadata_message, XHMI_MESSAGES, MEDIA_METADATA_MESSAGE, GObject)

/**
 * xhmi_messages_media_metadata_message_new:
 * kind: field in this object.
 * image: field in this object.
 * video: field in this object.
 * audio: field in this object.
 *
 * Creates a new #MediaMetadataMessage object.
 *
 * Returns: a new #XhmiMessagesMediaMetadataMessage
 */
XhmiMessagesMediaMetadataMessage* xhmi_messages_media_metadata_message_new(XhmiMessagesMediaKindMessage kind, XhmiMessagesImageMetadataMessage* image, XhmiMessagesVideoMetadataMessage* video, XhmiMessagesAudioMetadataMessage* audio);

/**
 * xhmi_messages_media_metadata_message_get_kind
 * @object: a #XhmiMessagesMediaMetadataMessage.
 *
 * Gets the value of the kind field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesMediaKindMessage xhmi_messages_media_metadata_message_get_kind(XhmiMessagesMediaMetadataMessage* object);

/**
 * xhmi_messages_media_metadata_message_get_image
 * @object: a #XhmiMessagesMediaMetadataMessage.
 *
 * Gets the value of the image field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesImageMetadataMessage* xhmi_messages_media_metadata_message_get_image(XhmiMessagesMediaMetadataMessage* object);

/**
 * xhmi_messages_media_metadata_message_get_video
 * @object: a #XhmiMessagesMediaMetadataMessage.
 *
 * Gets the value of the video field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesVideoMetadataMessage* xhmi_messages_media_metadata_message_get_video(XhmiMessagesMediaMetadataMessage* object);

/**
 * xhmi_messages_media_metadata_message_get_audio
 * @object: a #XhmiMessagesMediaMetadataMessage.
 *
 * Gets the value of the audio field of @object.
 *
 * Returns: the field value.
 */
XhmiMessagesAudioMetadataMessage* xhmi_messages_media_metadata_message_get_audio(XhmiMessagesMediaMetadataMessage* object);

/**
 * xhmi_messages_media_metadata_message_equals:
 * @a: a #XhmiMessagesMediaMetadataMessage.
 * @b: another #XhmiMessagesMediaMetadataMessage.
 *
 * Checks if two #XhmiMessagesMediaMetadataMessage objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean xhmi_messages_media_metadata_message_equals(XhmiMessagesMediaMetadataMessage* a, XhmiMessagesMediaMetadataMessage* b);

/**
 * xhmi_messages_media_metadata_message_hash:
 * @object: a #XhmiMessagesMediaMetadataMessage.
 *
 * Calculates a hash code for a #XhmiMessagesMediaMetadataMessage object.
 *
 * Returns: the hash code.
 */
guint xhmi_messages_media_metadata_message_hash(XhmiMessagesMediaMetadataMessage* object);

/**
 * xhmi_messages_media_metadata_message_to_string:
 * @object: a #XhmiMessagesMediaMetadataMessage.
 *
 * Returns a string representation of a #XhmiMessagesMediaMetadataMessage object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* xhmi_messages_media_metadata_message_to_string(XhmiMessagesMediaMetadataMessage* object);

G_DECLARE_FINAL_TYPE(XhmiMessagesMessageCodec, xhmi_messages_message_codec, XHMI_MESSAGES, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int xhmi_messages_source_kind_message_type_id;
extern const int xhmi_messages_media_kind_message_type_id;
extern const int xhmi_messages_media_source_message_type_id;
extern const int xhmi_messages_pixel_size_message_type_id;
extern const int xhmi_messages_gps_location_message_type_id;
extern const int xhmi_messages_metadata_tag_message_type_id;
extern const int xhmi_messages_png_text_chunk_message_type_id;
extern const int xhmi_messages_image_metadata_message_type_id;
extern const int xhmi_messages_video_metadata_message_type_id;
extern const int xhmi_messages_audio_metadata_message_type_id;
extern const int xhmi_messages_media_metadata_message_type_id;

G_DECLARE_FINAL_TYPE(XhmiMessagesMediaInfoHostApi, xhmi_messages_media_info_host_api, XHMI_MESSAGES, MEDIA_INFO_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(XhmiMessagesMediaInfoHostApiResponseHandle, xhmi_messages_media_info_host_api_response_handle, XHMI_MESSAGES, MEDIA_INFO_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * XhmiMessagesMediaInfoHostApiVTable:
 *
 * Table of functions exposed by MediaInfoHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*read)(XhmiMessagesMediaSourceMessage* source, XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, gpointer user_data);
  void (*read_image)(XhmiMessagesMediaSourceMessage* source, XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, gpointer user_data);
  void (*read_av)(XhmiMessagesMediaSourceMessage* source, XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, gpointer user_data);
  void (*probe)(XhmiMessagesMediaSourceMessage* source, XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, gpointer user_data);
  void (*read_motion_photo)(XhmiMessagesMediaSourceMessage* source, XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, gpointer user_data);
} XhmiMessagesMediaInfoHostApiVTable;

/**
 * xhmi_messages_media_info_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the MediaInfoHostApi API.
 */
void xhmi_messages_media_info_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const XhmiMessagesMediaInfoHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * xhmi_messages_media_info_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the MediaInfoHostApi API.
 */
void xhmi_messages_media_info_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * xhmi_messages_media_info_host_api_respond_read:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to MediaInfoHostApi.read. 
 */
void xhmi_messages_media_info_host_api_respond_read(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, XhmiMessagesMediaMetadataMessage* return_value);

/**
 * xhmi_messages_media_info_host_api_respond_error_read:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MediaInfoHostApi.read. 
 */
void xhmi_messages_media_info_host_api_respond_error_read(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xhmi_messages_media_info_host_api_respond_read_image:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to MediaInfoHostApi.readImage. 
 */
void xhmi_messages_media_info_host_api_respond_read_image(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, XhmiMessagesImageMetadataMessage* return_value);

/**
 * xhmi_messages_media_info_host_api_respond_error_read_image:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MediaInfoHostApi.readImage. 
 */
void xhmi_messages_media_info_host_api_respond_error_read_image(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xhmi_messages_media_info_host_api_respond_read_av:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to MediaInfoHostApi.readAv. 
 */
void xhmi_messages_media_info_host_api_respond_read_av(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, XhmiMessagesMediaMetadataMessage* return_value);

/**
 * xhmi_messages_media_info_host_api_respond_error_read_av:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MediaInfoHostApi.readAv. 
 */
void xhmi_messages_media_info_host_api_respond_error_read_av(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xhmi_messages_media_info_host_api_respond_probe:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to MediaInfoHostApi.probe. 
 */
void xhmi_messages_media_info_host_api_respond_probe(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, XhmiMessagesMediaKindMessage return_value);

/**
 * xhmi_messages_media_info_host_api_respond_error_probe:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MediaInfoHostApi.probe. 
 */
void xhmi_messages_media_info_host_api_respond_error_probe(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * xhmi_messages_media_info_host_api_respond_read_motion_photo:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to MediaInfoHostApi.readMotionPhoto. 
 */
void xhmi_messages_media_info_host_api_respond_read_motion_photo(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, XhmiMessagesVideoMetadataMessage* return_value);

/**
 * xhmi_messages_media_info_host_api_respond_error_read_motion_photo:
 * @response_handle: a #XhmiMessagesMediaInfoHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to MediaInfoHostApi.readMotionPhoto. 
 */
void xhmi_messages_media_info_host_api_respond_error_read_motion_photo(XhmiMessagesMediaInfoHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
