// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.xuehua.xue_hua_media_info_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Kind of a [MediaSourceMessage]. / [MediaSourceMessage] 的种类。 */
enum class SourceKindMessage(val raw: Int) {
  /** Local filesystem path. / 本地文件路径。 */
  FILE(0),
  /** In-memory bytes. / 内存字节。 */
  BYTES(1),
  /** Flutter asset key (already resolved). / 已解析的 Flutter Asset 键。 */
  ASSET(2);

  companion object {
    fun ofRaw(raw: Int): SourceKindMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Detected media kind. / 检测到的媒体种类。 */
enum class MediaKindMessage(val raw: Int) {
  /** Still image. / 静态图片。 */
  IMAGE(0),
  /** Container with a video track. / 含视频轨的容器。 */
  VIDEO(1),
  /** Audio-only container. / 纯音频容器。 */
  AUDIO(2);

  companion object {
    fun ofRaw(raw: Int): MediaKindMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Wire representation of a media source. / 媒体源的跨端传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaSourceMessage (
  /** Discriminator. / 种类。 */
  val kind: SourceKindMessage,
  /** File path or resolved asset key. / 文件路径或已解析的 asset 键。 */
  val uri: String? = null,
  /** In-memory payload for [SourceKindMessage.bytes]. / 字节源载荷。 */
  val bytes: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaSourceMessage {
      val kind = pigeonVar_list[0] as SourceKindMessage
      val uri = pigeonVar_list[1] as String?
      val bytes = pigeonVar_list[2] as ByteArray?
      return MediaSourceMessage(kind, uri, bytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      uri,
      bytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaSourceMessage
    return MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.uri, other.uri) && MessagesPigeonUtils.deepEquals(this.bytes, other.bytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.uri)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bytes)
    return result
  }
  override fun toString(): String {
    return "MediaSourceMessage(kind=$kind, uri=$uri, bytes=${bytes?.contentToString()})"
  }
}

/**
 * Wire pixel size. / 像素尺寸传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PixelSizeMessage (
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PixelSizeMessage {
      val width = pigeonVar_list[0] as Long
      val height = pigeonVar_list[1] as Long
      return PixelSizeMessage(width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PixelSizeMessage
    return MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "PixelSizeMessage(width=$width, height=$height)"
  }
}

/**
 * Wire GPS. / GPS 传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GpsLocationMessage (
  val latitude: Double,
  val longitude: Double,
  val altitudeMeters: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GpsLocationMessage {
      val latitude = pigeonVar_list[0] as Double
      val longitude = pigeonVar_list[1] as Double
      val altitudeMeters = pigeonVar_list[2] as Double?
      return GpsLocationMessage(latitude, longitude, altitudeMeters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
      altitudeMeters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GpsLocationMessage
    return MessagesPigeonUtils.deepEquals(this.latitude, other.latitude) && MessagesPigeonUtils.deepEquals(this.longitude, other.longitude) && MessagesPigeonUtils.deepEquals(this.altitudeMeters, other.altitudeMeters)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.latitude)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.longitude)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.altitudeMeters)
    return result
  }
  override fun toString(): String {
    return "GpsLocationMessage(latitude=$latitude, longitude=$longitude, altitudeMeters=$altitudeMeters)"
  }
}

/**
 * Wire leftover tag. / 残留标签传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MetadataTagMessage (
  val name: String,
  val displayValue: String,
  val stringValue: String? = null,
  val intValue: Long? = null,
  val doubleValue: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MetadataTagMessage {
      val name = pigeonVar_list[0] as String
      val displayValue = pigeonVar_list[1] as String
      val stringValue = pigeonVar_list[2] as String?
      val intValue = pigeonVar_list[3] as Long?
      val doubleValue = pigeonVar_list[4] as Double?
      return MetadataTagMessage(name, displayValue, stringValue, intValue, doubleValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      displayValue,
      stringValue,
      intValue,
      doubleValue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MetadataTagMessage
    return MessagesPigeonUtils.deepEquals(this.name, other.name) && MessagesPigeonUtils.deepEquals(this.displayValue, other.displayValue) && MessagesPigeonUtils.deepEquals(this.stringValue, other.stringValue) && MessagesPigeonUtils.deepEquals(this.intValue, other.intValue) && MessagesPigeonUtils.deepEquals(this.doubleValue, other.doubleValue)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.name)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.displayValue)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.stringValue)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.intValue)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.doubleValue)
    return result
  }
  override fun toString(): String {
    return "MetadataTagMessage(name=$name, displayValue=$displayValue, stringValue=$stringValue, intValue=$intValue, doubleValue=$doubleValue)"
  }
}

/**
 * Wire PNG text chunk. / PNG 文本块传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PngTextChunkMessage (
  val key: String,
  val value: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PngTextChunkMessage {
      val key = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as String
      return PngTextChunkMessage(key, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      key,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PngTextChunkMessage
    return MessagesPigeonUtils.deepEquals(this.key, other.key) && MessagesPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.key)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.value)
    return result
  }
  override fun toString(): String {
    return "PngTextChunkMessage(key=$key, value=$value)"
  }
}

/**
 * Wire image metadata. Dates are ISO-8601 (no timezone) or empty.
 * 图片元数据传输结构。日期为无时区 ISO-8601 或空。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ImageMetadataMessage (
  val make: String? = null,
  val model: String? = null,
  val software: String? = null,
  val size: PixelSizeMessage? = null,
  val orientation: Long? = null,
  val dateTimeOriginal: String? = null,
  val dateTimeDigitized: String? = null,
  val dateTimeModified: String? = null,
  val gps: GpsLocationMessage? = null,
  val hasMotionPhoto: Boolean,
  val pngText: List<PngTextChunkMessage>,
  val extraTags: List<MetadataTagMessage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageMetadataMessage {
      val make = pigeonVar_list[0] as String?
      val model = pigeonVar_list[1] as String?
      val software = pigeonVar_list[2] as String?
      val size = pigeonVar_list[3] as PixelSizeMessage?
      val orientation = pigeonVar_list[4] as Long?
      val dateTimeOriginal = pigeonVar_list[5] as String?
      val dateTimeDigitized = pigeonVar_list[6] as String?
      val dateTimeModified = pigeonVar_list[7] as String?
      val gps = pigeonVar_list[8] as GpsLocationMessage?
      val hasMotionPhoto = pigeonVar_list[9] as Boolean
      val pngText = pigeonVar_list[10] as List<PngTextChunkMessage>
      val extraTags = pigeonVar_list[11] as List<MetadataTagMessage>
      return ImageMetadataMessage(make, model, software, size, orientation, dateTimeOriginal, dateTimeDigitized, dateTimeModified, gps, hasMotionPhoto, pngText, extraTags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      make,
      model,
      software,
      size,
      orientation,
      dateTimeOriginal,
      dateTimeDigitized,
      dateTimeModified,
      gps,
      hasMotionPhoto,
      pngText,
      extraTags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ImageMetadataMessage
    return MessagesPigeonUtils.deepEquals(this.make, other.make) && MessagesPigeonUtils.deepEquals(this.model, other.model) && MessagesPigeonUtils.deepEquals(this.software, other.software) && MessagesPigeonUtils.deepEquals(this.size, other.size) && MessagesPigeonUtils.deepEquals(this.orientation, other.orientation) && MessagesPigeonUtils.deepEquals(this.dateTimeOriginal, other.dateTimeOriginal) && MessagesPigeonUtils.deepEquals(this.dateTimeDigitized, other.dateTimeDigitized) && MessagesPigeonUtils.deepEquals(this.dateTimeModified, other.dateTimeModified) && MessagesPigeonUtils.deepEquals(this.gps, other.gps) && MessagesPigeonUtils.deepEquals(this.hasMotionPhoto, other.hasMotionPhoto) && MessagesPigeonUtils.deepEquals(this.pngText, other.pngText) && MessagesPigeonUtils.deepEquals(this.extraTags, other.extraTags)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.make)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.model)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.software)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.size)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.orientation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.dateTimeOriginal)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.dateTimeDigitized)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.dateTimeModified)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasMotionPhoto)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.pngText)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extraTags)
    return result
  }
  override fun toString(): String {
    return "ImageMetadataMessage(make=$make, model=$model, software=$software, size=$size, orientation=$orientation, dateTimeOriginal=$dateTimeOriginal, dateTimeDigitized=$dateTimeDigitized, dateTimeModified=$dateTimeModified, gps=$gps, hasMotionPhoto=$hasMotionPhoto, pngText=$pngText, extraTags=$extraTags)"
  }
}

/**
 * Wire video metadata. / 视频元数据传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoMetadataMessage (
  val durationMs: Long? = null,
  val size: PixelSizeMessage? = null,
  val bitrate: Long? = null,
  val rotationDegrees: Long? = null,
  val make: String? = null,
  val model: String? = null,
  val gps: GpsLocationMessage? = null,
  val extraTags: List<MetadataTagMessage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoMetadataMessage {
      val durationMs = pigeonVar_list[0] as Long?
      val size = pigeonVar_list[1] as PixelSizeMessage?
      val bitrate = pigeonVar_list[2] as Long?
      val rotationDegrees = pigeonVar_list[3] as Long?
      val make = pigeonVar_list[4] as String?
      val model = pigeonVar_list[5] as String?
      val gps = pigeonVar_list[6] as GpsLocationMessage?
      val extraTags = pigeonVar_list[7] as List<MetadataTagMessage>
      return VideoMetadataMessage(durationMs, size, bitrate, rotationDegrees, make, model, gps, extraTags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      durationMs,
      size,
      bitrate,
      rotationDegrees,
      make,
      model,
      gps,
      extraTags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoMetadataMessage
    return MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.size, other.size) && MessagesPigeonUtils.deepEquals(this.bitrate, other.bitrate) && MessagesPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && MessagesPigeonUtils.deepEquals(this.make, other.make) && MessagesPigeonUtils.deepEquals(this.model, other.model) && MessagesPigeonUtils.deepEquals(this.gps, other.gps) && MessagesPigeonUtils.deepEquals(this.extraTags, other.extraTags)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.size)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitrate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.make)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.model)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extraTags)
    return result
  }
  override fun toString(): String {
    return "VideoMetadataMessage(durationMs=$durationMs, size=$size, bitrate=$bitrate, rotationDegrees=$rotationDegrees, make=$make, model=$model, gps=$gps, extraTags=$extraTags)"
  }
}

/**
 * Wire audio metadata. / 音频元数据传输结构。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AudioMetadataMessage (
  val durationMs: Long? = null,
  val bitrate: Long? = null,
  val sampleRate: Long? = null,
  val channelCount: Long? = null,
  val make: String? = null,
  val model: String? = null,
  val gps: GpsLocationMessage? = null,
  val extraTags: List<MetadataTagMessage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioMetadataMessage {
      val durationMs = pigeonVar_list[0] as Long?
      val bitrate = pigeonVar_list[1] as Long?
      val sampleRate = pigeonVar_list[2] as Long?
      val channelCount = pigeonVar_list[3] as Long?
      val make = pigeonVar_list[4] as String?
      val model = pigeonVar_list[5] as String?
      val gps = pigeonVar_list[6] as GpsLocationMessage?
      val extraTags = pigeonVar_list[7] as List<MetadataTagMessage>
      return AudioMetadataMessage(durationMs, bitrate, sampleRate, channelCount, make, model, gps, extraTags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      durationMs,
      bitrate,
      sampleRate,
      channelCount,
      make,
      model,
      gps,
      extraTags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AudioMetadataMessage
    return MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.bitrate, other.bitrate) && MessagesPigeonUtils.deepEquals(this.sampleRate, other.sampleRate) && MessagesPigeonUtils.deepEquals(this.channelCount, other.channelCount) && MessagesPigeonUtils.deepEquals(this.make, other.make) && MessagesPigeonUtils.deepEquals(this.model, other.model) && MessagesPigeonUtils.deepEquals(this.gps, other.gps) && MessagesPigeonUtils.deepEquals(this.extraTags, other.extraTags)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bitrate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sampleRate)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.channelCount)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.make)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.model)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gps)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.extraTags)
    return result
  }
  override fun toString(): String {
    return "AudioMetadataMessage(durationMs=$durationMs, bitrate=$bitrate, sampleRate=$sampleRate, channelCount=$channelCount, make=$make, model=$model, gps=$gps, extraTags=$extraTags)"
  }
}

/**
 * Tagged union of metadata results. / 带种类判别的元数据联合。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaMetadataMessage (
  val kind: MediaKindMessage,
  val image: ImageMetadataMessage? = null,
  val video: VideoMetadataMessage? = null,
  val audio: AudioMetadataMessage? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaMetadataMessage {
      val kind = pigeonVar_list[0] as MediaKindMessage
      val image = pigeonVar_list[1] as ImageMetadataMessage?
      val video = pigeonVar_list[2] as VideoMetadataMessage?
      val audio = pigeonVar_list[3] as AudioMetadataMessage?
      return MediaMetadataMessage(kind, image, video, audio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      image,
      video,
      audio,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaMetadataMessage
    return MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.image, other.image) && MessagesPigeonUtils.deepEquals(this.video, other.video) && MessagesPigeonUtils.deepEquals(this.audio, other.audio)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.image)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.video)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.audio)
    return result
  }
  override fun toString(): String {
    return "MediaMetadataMessage(kind=$kind, image=$image, video=$video, audio=$audio)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SourceKindMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaKindMessage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaSourceMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PixelSizeMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GpsLocationMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MetadataTagMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PngTextChunkMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageMetadataMessage.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoMetadataMessage.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioMetadataMessage.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaMetadataMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SourceKindMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is MediaKindMessage -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is MediaSourceMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PixelSizeMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is GpsLocationMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MetadataTagMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PngTextChunkMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ImageMetadataMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is VideoMetadataMessage -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is AudioMetadataMessage -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is MediaMetadataMessage -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API implemented natively for media metadata reads.
 * 由原生端实现的媒体元数据读取接口。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface MediaInfoHostApi {
  /** Auto-detect and read in one I/O. / 一次 I/O 自动识别并读取。 */
  fun read(source: MediaSourceMessage, callback: (Result<MediaMetadataMessage>) -> Unit)
  /** Read still-image metadata. / 读取静态图片元数据。 */
  fun readImage(source: MediaSourceMessage, callback: (Result<ImageMetadataMessage>) -> Unit)
  /** Read a video or audio-only container. / 读取视频或纯音频容器。 */
  fun readAv(source: MediaSourceMessage, callback: (Result<MediaMetadataMessage>) -> Unit)
  /** Header-only kind detection. / 仅检查文件头。 */
  fun probe(source: MediaSourceMessage, callback: (Result<MediaKindMessage>) -> Unit)
  /** Extract Motion Photo embedded MP4 metadata. / 提取动态照片内嵌 MP4。 */
  fun readMotionPhoto(source: MediaSourceMessage, callback: (Result<VideoMetadataMessage>) -> Unit)

  companion object {
    /** The codec used by MediaInfoHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `MediaInfoHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MediaInfoHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.read$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as MediaSourceMessage
            api.read(sourceArg) { result: Result<MediaMetadataMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as MediaSourceMessage
            api.readImage(sourceArg) { result: Result<ImageMetadataMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readAv$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as MediaSourceMessage
            api.readAv(sourceArg) { result: Result<MediaMetadataMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.probe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as MediaSourceMessage
            api.probe(sourceArg) { result: Result<MediaKindMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.xue_hua_media_info_platform_interface.MediaInfoHostApi.readMotionPhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as MediaSourceMessage
            api.readMotionPhoto(sourceArg) { result: Result<VideoMetadataMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
