// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

MediaMetadataParser createMediaMetadataParser() =>
    RustLib.instance.api.crateApiParserCreateMediaMetadataParser();

ImageExif parseImageExifFromFile({
  required MediaMetadataParser parser,
  required String path,
}) => RustLib.instance.api.crateApiParserParseImageExifFromFile(
  parser: parser,
  path: path,
);

ImageExif parseImageExifFromBytes({
  required MediaMetadataParser parser,
  required List<int> data,
}) => RustLib.instance.api.crateApiParserParseImageExifFromBytes(
  parser: parser,
  data: data,
);

VideoTrack parseVideoMetadataFromFile({
  required MediaMetadataParser parser,
  required String path,
}) => RustLib.instance.api.crateApiParserParseVideoMetadataFromFile(
  parser: parser,
  path: path,
);

VideoTrack parseVideoMetadataFromBytes({
  required MediaMetadataParser parser,
  required List<int> data,
}) => RustLib.instance.api.crateApiParserParseVideoMetadataFromBytes(
  parser: parser,
  data: data,
);

FullImageMetadata parseFullImageMetadataFromFile({
  required MediaMetadataParser parser,
  required String path,
}) => RustLib.instance.api.crateApiParserParseFullImageMetadataFromFile(
  parser: parser,
  path: path,
);

FullImageMetadata parseFullImageMetadataFromBytes({
  required MediaMetadataParser parser,
  required List<int> data,
}) => RustLib.instance.api.crateApiParserParseFullImageMetadataFromBytes(
  parser: parser,
  data: data,
);

VideoTrack parseEmbeddedVideoFromFile({
  required MediaMetadataParser parser,
  required String path,
}) => RustLib.instance.api.crateApiParserParseEmbeddedVideoFromFile(
  parser: parser,
  path: path,
);

VideoTrack parseEmbeddedVideoFromBytes({
  required MediaMetadataParser parser,
  required List<int> data,
}) => RustLib.instance.api.crateApiParserParseEmbeddedVideoFromBytes(
  parser: parser,
  data: data,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MediaMetadataParser>>
abstract class MediaMetadataParser implements RustOpaqueInterface {}
