// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'parser.dart';
import 'types.dart';

Future<ImageExif> parseImageExifFromFileAsync({
  required MediaMetadataParser parser,
  required String path,
}) => RustLib.instance.api.crateApiParserAsyncParseImageExifFromFileAsync(
  parser: parser,
  path: path,
);

Future<ImageExif> parseImageExifFromBytesAsync({
  required MediaMetadataParser parser,
  required List<int> data,
}) => RustLib.instance.api.crateApiParserAsyncParseImageExifFromBytesAsync(
  parser: parser,
  data: data,
);

Future<VideoTrack> parseVideoMetadataFromFileAsync({
  required MediaMetadataParser parser,
  required String path,
}) => RustLib.instance.api.crateApiParserAsyncParseVideoMetadataFromFileAsync(
  parser: parser,
  path: path,
);

Future<VideoTrack> parseVideoMetadataFromBytesAsync({
  required MediaMetadataParser parser,
  required List<int> data,
}) => RustLib.instance.api.crateApiParserAsyncParseVideoMetadataFromBytesAsync(
  parser: parser,
  data: data,
);

Future<FullImageMetadata> parseFullImageMetadataFromFileAsync({
  required MediaMetadataParser parser,
  required String path,
}) =>
    RustLib.instance.api.crateApiParserAsyncParseFullImageMetadataFromFileAsync(
      parser: parser,
      path: path,
    );

Future<FullImageMetadata> parseFullImageMetadataFromBytesAsync({
  required MediaMetadataParser parser,
  required List<int> data,
}) => RustLib.instance.api
    .crateApiParserAsyncParseFullImageMetadataFromBytesAsync(
      parser: parser,
      data: data,
    );

Future<VideoTrack> parseEmbeddedVideoFromFileAsync({
  required MediaMetadataParser parser,
  required String path,
}) => RustLib.instance.api.crateApiParserAsyncParseEmbeddedVideoFromFileAsync(
  parser: parser,
  path: path,
);

Future<VideoTrack> parseEmbeddedVideoFromBytesAsync({
  required MediaMetadataParser parser,
  required List<int> data,
}) => RustLib.instance.api.crateApiParserAsyncParseEmbeddedVideoFromBytesAsync(
  parser: parser,
  data: data,
);
