// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

MediaMetadata readMediaMetadataFromFile({required String path}) =>
    RustLib.instance.api.crateApiReaderReadMediaMetadataFromFile(path: path);

MediaMetadata readMediaMetadataFromBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderReadMediaMetadataFromBytes(data: data);

ImageExif readImageExifFromFile({required String path}) =>
    RustLib.instance.api.crateApiReaderReadImageExifFromFile(path: path);

ImageExif readImageExifFromBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderReadImageExifFromBytes(data: data);

ImageExif readImageExifLazyFromFile({required String path}) =>
    RustLib.instance.api.crateApiReaderReadImageExifLazyFromFile(path: path);

ImageExif readImageExifLazyFromBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderReadImageExifLazyFromBytes(data: data);

VideoTrack readVideoMetadataFromFile({required String path}) =>
    RustLib.instance.api.crateApiReaderReadVideoMetadataFromFile(path: path);

VideoTrack readVideoMetadataFromBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderReadVideoMetadataFromBytes(data: data);

FullImageMetadata readFullImageMetadataFromFile({required String path}) =>
    RustLib.instance.api.crateApiReaderReadFullImageMetadataFromFile(
      path: path,
    );

FullImageMetadata readFullImageMetadataFromBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderReadFullImageMetadataFromBytes(
      data: data,
    );

MediaKind detectMediaKindFromFile({required String path}) =>
    RustLib.instance.api.crateApiReaderDetectMediaKindFromFile(path: path);

MediaKind detectMediaKindFromBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderDetectMediaKindFromBytes(data: data);

VideoTrack readEmbeddedVideoFromFile({required String path}) =>
    RustLib.instance.api.crateApiReaderReadEmbeddedVideoFromFile(path: path);

VideoTrack readEmbeddedVideoFromBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderReadEmbeddedVideoFromBytes(data: data);
