// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<MediaMetadata> readMediaMetadataFromFileAsync({required String path}) =>
    RustLib.instance.api.crateApiReaderAsyncReadMediaMetadataFromFileAsync(
      path: path,
    );

Future<MediaMetadata> readMediaMetadataFromBytesAsync({
  required List<int> data,
}) => RustLib.instance.api.crateApiReaderAsyncReadMediaMetadataFromBytesAsync(
  data: data,
);

Future<ImageExif> readImageExifFromFileAsync({required String path}) => RustLib
    .instance
    .api
    .crateApiReaderAsyncReadImageExifFromFileAsync(path: path);

Future<ImageExif> readImageExifFromBytesAsync({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderAsyncReadImageExifFromBytesAsync(
      data: data,
    );

Future<ImageExif> readImageExifLazyFromFileAsync({required String path}) =>
    RustLib.instance.api.crateApiReaderAsyncReadImageExifLazyFromFileAsync(
      path: path,
    );

Future<ImageExif> readImageExifLazyFromBytesAsync({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderAsyncReadImageExifLazyFromBytesAsync(
      data: data,
    );

Future<VideoTrack> readVideoMetadataFromFileAsync({required String path}) =>
    RustLib.instance.api.crateApiReaderAsyncReadVideoMetadataFromFileAsync(
      path: path,
    );

Future<VideoTrack> readVideoMetadataFromBytesAsync({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderAsyncReadVideoMetadataFromBytesAsync(
      data: data,
    );

Future<FullImageMetadata> readFullImageMetadataFromFileAsync({
  required String path,
}) => RustLib.instance.api
    .crateApiReaderAsyncReadFullImageMetadataFromFileAsync(path: path);

Future<FullImageMetadata> readFullImageMetadataFromBytesAsync({
  required List<int> data,
}) => RustLib.instance.api
    .crateApiReaderAsyncReadFullImageMetadataFromBytesAsync(data: data);

Future<MediaKind> detectMediaKindFromFileAsync({required String path}) =>
    RustLib.instance.api.crateApiReaderAsyncDetectMediaKindFromFileAsync(
      path: path,
    );

Future<MediaKind> detectMediaKindFromBytesAsync({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderAsyncDetectMediaKindFromBytesAsync(
      data: data,
    );

Future<VideoTrack> readEmbeddedVideoFromFileAsync({required String path}) =>
    RustLib.instance.api.crateApiReaderAsyncReadEmbeddedVideoFromFileAsync(
      path: path,
    );

Future<VideoTrack> readEmbeddedVideoFromBytesAsync({required List<int> data}) =>
    RustLib.instance.api.crateApiReaderAsyncReadEmbeddedVideoFromBytesAsync(
      data: data,
    );
