// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

enum AltitudeRefDto { unknown, aboveSeaLevel, belowSeaLevel }

class FullImageMetadataDto {
  final ImageExifDto? exif;
  final List<PngTextMetadataDto> pngTextChunks;

  const FullImageMetadataDto({this.exif, required this.pngTextChunks});

  @override
  int get hashCode => exif.hashCode ^ pngTextChunks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FullImageMetadataDto &&
          runtimeType == other.runtimeType &&
          exif == other.exif &&
          pngTextChunks == other.pngTextChunks;
}

class GpsLocationDto {
  final double? latitude;
  final double? longitude;
  final double? altitudeMeters;
  final LatitudeRefDto latitudeRef;
  final LongitudeRefDto longitudeRef;
  final AltitudeRefDto altitudeRef;
  final String iso6709;

  const GpsLocationDto({
    this.latitude,
    this.longitude,
    this.altitudeMeters,
    required this.latitudeRef,
    required this.longitudeRef,
    required this.altitudeRef,
    required this.iso6709,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^
      longitude.hashCode ^
      altitudeMeters.hashCode ^
      latitudeRef.hashCode ^
      longitudeRef.hashCode ^
      altitudeRef.hashCode ^
      iso6709.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpsLocationDto &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          altitudeMeters == other.altitudeMeters &&
          latitudeRef == other.latitudeRef &&
          longitudeRef == other.longitudeRef &&
          altitudeRef == other.altitudeRef &&
          iso6709 == other.iso6709;
}

class ImageExifDto {
  final List<MetadataEntryDto> entries;
  final GpsLocationDto? gps;
  final bool hasEmbeddedVideo;
  final List<ParseErrorDto> parseErrors;

  const ImageExifDto({
    required this.entries,
    this.gps,
    required this.hasEmbeddedVideo,
    required this.parseErrors,
  });

  @override
  int get hashCode =>
      entries.hashCode ^
      gps.hashCode ^
      hasEmbeddedVideo.hashCode ^
      parseErrors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageExifDto &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          gps == other.gps &&
          hasEmbeddedVideo == other.hasEmbeddedVideo &&
          parseErrors == other.parseErrors;
}

enum LatitudeRefDto { north, south }

enum LongitudeRefDto { east, west }

class MediaInfoError implements FrbException {
  final MediaInfoErrorCode code;
  final String message;

  const MediaInfoError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInfoError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

enum MediaInfoErrorCode {
  io,
  unsupportedFormat,
  exifNotFound,
  trackNotFound,
  malformed,
  unexpectedEof,
  other,
}

enum MediaKindDto { image, videoOrAudio }

@freezed
sealed class MediaMetadataDto with _$MediaMetadataDto {
  const MediaMetadataDto._();

  const factory MediaMetadataDto.imageExif(ImageExifDto field0) =
      MediaMetadataDto_ImageExif;
  const factory MediaMetadataDto.videoTrack(VideoTrackDto field0) =
      MediaMetadataDto_VideoTrack;
}

class MetadataEntryDto {
  final String tagName;
  final int tagCode;
  final int ifdIndex;
  final MetadataValueKind valueKind;
  final String displayValue;
  final MetadataValueDto? rawValue;

  const MetadataEntryDto({
    required this.tagName,
    required this.tagCode,
    required this.ifdIndex,
    required this.valueKind,
    required this.displayValue,
    this.rawValue,
  });

  @override
  int get hashCode =>
      tagName.hashCode ^
      tagCode.hashCode ^
      ifdIndex.hashCode ^
      valueKind.hashCode ^
      displayValue.hashCode ^
      rawValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataEntryDto &&
          runtimeType == other.runtimeType &&
          tagName == other.tagName &&
          tagCode == other.tagCode &&
          ifdIndex == other.ifdIndex &&
          valueKind == other.valueKind &&
          displayValue == other.displayValue &&
          rawValue == other.rawValue;
}

@freezed
sealed class MetadataValueDto with _$MetadataValueDto {
  const MetadataValueDto._();

  const factory MetadataValueDto.text(String field0) = MetadataValueDto_Text;
  const factory MetadataValueDto.integer(PlatformInt64 field0) =
      MetadataValueDto_Integer;
  const factory MetadataValueDto.float(double field0) = MetadataValueDto_Float;
  const factory MetadataValueDto.rational(RationalDto field0) =
      MetadataValueDto_Rational;
  const factory MetadataValueDto.signedRational(RationalDto field0) =
      MetadataValueDto_SignedRational;
  const factory MetadataValueDto.dateTime(String field0) =
      MetadataValueDto_DateTime;
  const factory MetadataValueDto.naiveDateTime(String field0) =
      MetadataValueDto_NaiveDateTime;
  const factory MetadataValueDto.bytes(String field0) = MetadataValueDto_Bytes;
  const factory MetadataValueDto.rationalArray(List<RationalDto> field0) =
      MetadataValueDto_RationalArray;
  const factory MetadataValueDto.signedRationalArray(List<RationalDto> field0) =
      MetadataValueDto_SignedRationalArray;
  const factory MetadataValueDto.u8Array(Uint8List field0) =
      MetadataValueDto_U8Array;
  const factory MetadataValueDto.u16Array(Int32List field0) =
      MetadataValueDto_U16Array;
  const factory MetadataValueDto.u32Array(Int64List field0) =
      MetadataValueDto_U32Array;
}

enum MetadataValueKind {
  text,
  integer,
  float,
  rational,
  signedRational,
  dateTime,
  naiveDateTime,
  bytes,
  rationalArray,
  signedRationalArray,
  u8Array,
  u16Array,
  u32Array,
}

class ParseErrorDto {
  final int ifdIndex;
  final String tagName;
  final int tagCode;
  final String message;

  const ParseErrorDto({
    required this.ifdIndex,
    required this.tagName,
    required this.tagCode,
    required this.message,
  });

  @override
  int get hashCode =>
      ifdIndex.hashCode ^
      tagName.hashCode ^
      tagCode.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseErrorDto &&
          runtimeType == other.runtimeType &&
          ifdIndex == other.ifdIndex &&
          tagName == other.tagName &&
          tagCode == other.tagCode &&
          message == other.message;
}

class PngTextMetadataDto {
  final String key;
  final String value;

  const PngTextMetadataDto({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PngTextMetadataDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class RationalDto {
  final PlatformInt64 numerator;
  final PlatformInt64 denominator;

  const RationalDto({required this.numerator, required this.denominator});

  @override
  int get hashCode => numerator.hashCode ^ denominator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RationalDto &&
          runtimeType == other.runtimeType &&
          numerator == other.numerator &&
          denominator == other.denominator;
}

class VideoTrackDto {
  final List<MetadataEntryDto> entries;
  final GpsLocationDto? gps;
  final List<ParseErrorDto> parseErrors;

  const VideoTrackDto({
    required this.entries,
    this.gps,
    required this.parseErrors,
  });

  @override
  int get hashCode => entries.hashCode ^ gps.hashCode ^ parseErrors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoTrackDto &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          gps == other.gps &&
          parseErrors == other.parseErrors;
}
