// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

enum AltitudeRef { unknown, aboveSeaLevel, belowSeaLevel }

class FullImageMetadata {
  final ImageExif? exif;
  final List<PngTextMetadata> pngTextChunks;

  const FullImageMetadata({this.exif, required this.pngTextChunks});

  @override
  int get hashCode => exif.hashCode ^ pngTextChunks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FullImageMetadata &&
          runtimeType == other.runtimeType &&
          exif == other.exif &&
          pngTextChunks == other.pngTextChunks;
}

class GpsLocation {
  final double? latitude;
  final double? longitude;
  final double? altitudeMeters;
  final LatitudeRef latitudeRef;
  final LongitudeRef longitudeRef;
  final AltitudeRef altitudeRef;
  final String iso6709;

  const GpsLocation({
    this.latitude,
    this.longitude,
    this.altitudeMeters,
    required this.latitudeRef,
    required this.longitudeRef,
    required this.altitudeRef,
    required this.iso6709,
  });

  @override
  int get hashCode =>
      latitude.hashCode ^
      longitude.hashCode ^
      altitudeMeters.hashCode ^
      latitudeRef.hashCode ^
      longitudeRef.hashCode ^
      altitudeRef.hashCode ^
      iso6709.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpsLocation &&
          runtimeType == other.runtimeType &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          altitudeMeters == other.altitudeMeters &&
          latitudeRef == other.latitudeRef &&
          longitudeRef == other.longitudeRef &&
          altitudeRef == other.altitudeRef &&
          iso6709 == other.iso6709;
}

class ImageExif {
  final List<MetadataEntry> entries;
  final GpsLocation? gps;
  final bool hasEmbeddedVideo;
  final List<ParseError> parseErrors;

  const ImageExif({
    required this.entries,
    this.gps,
    required this.hasEmbeddedVideo,
    required this.parseErrors,
  });

  @override
  int get hashCode =>
      entries.hashCode ^
      gps.hashCode ^
      hasEmbeddedVideo.hashCode ^
      parseErrors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageExif &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          gps == other.gps &&
          hasEmbeddedVideo == other.hasEmbeddedVideo &&
          parseErrors == other.parseErrors;
}

enum LatitudeRef { north, south }

enum LongitudeRef { east, west }

class MediaInfoError implements FrbException {
  final MediaInfoErrorCode code;
  final String message;

  const MediaInfoError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInfoError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

enum MediaInfoErrorCode {
  io,
  unsupportedFormat,
  exifNotFound,
  trackNotFound,
  malformed,
  unexpectedEof,
  other,
}

enum MediaKind { image, videoOrAudio }

@freezed
sealed class MediaMetadata with _$MediaMetadata {
  const MediaMetadata._();

  const factory MediaMetadata.imageExif(ImageExif field0) =
      MediaMetadata_ImageExif;
  const factory MediaMetadata.videoTrack(VideoTrack field0) =
      MediaMetadata_VideoTrack;
}

class MetadataEntry {
  final String tagName;
  final int tagCode;
  final int ifdIndex;
  final MetadataValueKind valueKind;
  final String displayValue;
  final MetadataValue? rawValue;

  const MetadataEntry({
    required this.tagName,
    required this.tagCode,
    required this.ifdIndex,
    required this.valueKind,
    required this.displayValue,
    this.rawValue,
  });

  @override
  int get hashCode =>
      tagName.hashCode ^
      tagCode.hashCode ^
      ifdIndex.hashCode ^
      valueKind.hashCode ^
      displayValue.hashCode ^
      rawValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataEntry &&
          runtimeType == other.runtimeType &&
          tagName == other.tagName &&
          tagCode == other.tagCode &&
          ifdIndex == other.ifdIndex &&
          valueKind == other.valueKind &&
          displayValue == other.displayValue &&
          rawValue == other.rawValue;
}

@freezed
sealed class MetadataValue with _$MetadataValue {
  const MetadataValue._();

  const factory MetadataValue.text(String field0) = MetadataValue_Text;
  const factory MetadataValue.integer(PlatformInt64 field0) =
      MetadataValue_Integer;
  const factory MetadataValue.float(double field0) = MetadataValue_Float;
  const factory MetadataValue.rational(Rational field0) =
      MetadataValue_Rational;
  const factory MetadataValue.signedRational(Rational field0) =
      MetadataValue_SignedRational;
  const factory MetadataValue.dateTime(String field0) = MetadataValue_DateTime;
  const factory MetadataValue.naiveDateTime(String field0) =
      MetadataValue_NaiveDateTime;
  const factory MetadataValue.bytes(String field0) = MetadataValue_Bytes;
  const factory MetadataValue.rationalArray(List<Rational> field0) =
      MetadataValue_RationalArray;
  const factory MetadataValue.signedRationalArray(List<Rational> field0) =
      MetadataValue_SignedRationalArray;
  const factory MetadataValue.u8Array(Uint8List field0) = MetadataValue_U8Array;
  const factory MetadataValue.u16Array(Int32List field0) =
      MetadataValue_U16Array;
  const factory MetadataValue.u32Array(Int64List field0) =
      MetadataValue_U32Array;
}

enum MetadataValueKind {
  text,
  integer,
  float,
  rational,
  signedRational,
  dateTime,
  naiveDateTime,
  bytes,
  rationalArray,
  signedRationalArray,
  u8Array,
  u16Array,
  u32Array,
}

class ParseError {
  final int ifdIndex;
  final String tagName;
  final int tagCode;
  final String message;

  const ParseError({
    required this.ifdIndex,
    required this.tagName,
    required this.tagCode,
    required this.message,
  });

  @override
  int get hashCode =>
      ifdIndex.hashCode ^
      tagName.hashCode ^
      tagCode.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseError &&
          runtimeType == other.runtimeType &&
          ifdIndex == other.ifdIndex &&
          tagName == other.tagName &&
          tagCode == other.tagCode &&
          message == other.message;
}

class PngTextMetadata {
  final String key;
  final String value;

  const PngTextMetadata({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PngTextMetadata &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class Rational {
  final PlatformInt64 numerator;
  final PlatformInt64 denominator;

  const Rational({required this.numerator, required this.denominator});

  @override
  int get hashCode => numerator.hashCode ^ denominator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Rational &&
          runtimeType == other.runtimeType &&
          numerator == other.numerator &&
          denominator == other.denominator;
}

class VideoTrack {
  final List<MetadataEntry> entries;
  final GpsLocation? gps;
  final List<ParseError> parseErrors;

  const VideoTrack({
    required this.entries,
    this.gps,
    required this.parseErrors,
  });

  @override
  int get hashCode => entries.hashCode ^ gps.hashCode ^ parseErrors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoTrack &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          gps == other.gps &&
          parseErrors == other.parseErrors;
}
